# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Unterstützt die DMX Interfaces NanoDMX und DMXking (RS-232)'
        en: 'Supports DMX interfaces NanoDMX and DMXking (RS-232)'
    maintainer: 'bmx'
    tester: nobody                  # Who tests this plugin?
    state: develop                  # change to ready when done with development
    keywords: dmx gateway channel dimmer
    documentation: http://smarthomeng.de/user/plugins/dmx/user_doc.html        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.6.0                  # Plugin version
    sh_minversion: 1.4.0            # minimum shNG version to use this plugin
    #sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: unknown
    classname: DMX                  # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    serialport:
        type: str
        description:
            de: 'Serieller Port an dem das DMX Interface angeschlossen ist'
            en: 'Serial port at which the DMX interface is attached'
    interface:
        type: str
        default: 'nanodmx'
        valid_list:
          - 'nanodmx'
          - 'enttec'
          - 'development_only'
        description:
            de: 'Zu nutzendes Interface'
            en: 'Interface to be used'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    dmx_ch:
        type: list(int)
        description:
            de: 'Liste mit Kanälen die von diesem Item angesteuert werden'
            en: 'List of channels that are set by this item'

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

