# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: protocol                 # plugin type (gateway, interface, protocol, system, web)
    description:                   # Alternative: description in multiple languages
        de: 'Daten per UDP und TCP Protokoll sowie HTTP GET empfangen und per UDP senden'
        en: 'Receive data with UDP and TCP protocol as well as HTTP GET and send with UDP'
    maintainer: bmxp
    tester: onkelandy, psilo909
    state: ready
    keywords: network TCP UDP HTTP GET
    documentation: https://www.smarthomeng.de/developer/plugins/network/user_doc.html       # url of documentation (wiki) page

    version: 1.4.1                 # Plugin version
    sh_minversion: 1.6             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: Network             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    ip:
        type: ip
        default: '0.0.0.0'
        description:
            de: "IP Adresse auf der eingehende Verbindungen akzeptiert werden sollen (0.0.0.0 = alle)"
            en: "IP address on which incoming connections should be accepted (0.0.0.0 = all)"
    port:
        type: int
        default: 2727
        valid_min: 0
        valid_max: 65535
        description:
            de: "Port für eingehende Verbindungen"
            en: "Port for incomming connections"
    udp:
        type: str
        default: 'no'
        valid_list:
          - 'yes'
          - 'no'
        description:
            de: "Eingehende UDP Verbindungen akzeptieren"
            en: "Accept incoming UDP connections"
    tcp:
        type: str
        default: 'no'
        valid_list:
          - 'yes'
          - 'no'
        description:
            de: "Eingehende TCP Verbindungen akzeptieren"
            en: "Accept incoming TCP connections"
    http:
        type: str
        default: 'no'
        #valid_list:
        #  - yes
        #  - no
        description:
            de: "Eingehende HTTP Verbindungen akzeptieren (no oder Portnummer)"
            en: "Accept incoming HTTP connections (no or port number)"
    udp_acl:
        type: list
        default: '*'
        description:
            de: "Mit diesem Attribut kann man eine Liste von / eine einzelne IP Adresse definieren, von der UDP Updates kommen dürfen. Per Default wird jeder eingehende Request angenommen."
            en: "with this attribute you could specify a list or a single IP address to allow UDP updates from. By default it accepts every incoming request."
    tcp_acl:
        type: list
        default: '*'
        description:
            de: "Mit diesem Attribut kann man eine Liste von / eine einzelne IP Adresse definieren, von der TCP Updates kommen dürfen. Per Default wird jeder eingehende Request angenommen."
            en: "with this attribute you could specify a list or a single IP address to allow TCP updates from. By default it accepts every incoming request."
    http_acl:
        type: list
        default: '*'
        description:
            de:  "Mit diesem Attribut kann man eine Liste von / eine einzelne IP Adresse definieren, von der HTTP Updates kommen dürfen. Per Default wird jeder eingehende Request angenommen."
            en: "with this attribute you could specify a list or a single IP address to allow HTTP updates from. By default it accepts every incoming request."


item_attributes:
    # Definition of item attributes defined by this plugin
    nw:
        type: str
        valid_list:
            - yes
            - no
        description:
            de: 'Wenn dieses Attribut auf "True" (oder "yes", etc.) gesetzt wird, kann dieses Item über den generischen Listener des Network Plugins über TCP und/oder UDP aktualisiert werden.'
            en: "If this attribute is set to 'yes' you could update this item with the generic listener (TCP and/or UDP)."
    nw_acl:
        type: list
        description:
            de: "Wie bei dem generischen Plugin-Attribut tcp_acl/udp_acl, kann eine Liste oder eine einzelne IP Adresse konfiguriert werden. Nur von dieser/diesen darf das Item aktualisiert werden. Das Attribut überschreibt die Einstellung in der Pluginkonfiguration."
            en: "Like the generic tcp_acl/udp_acl a list or single IP address to limit updates from. This attribute is valid for TCP and UDP and overrides the generic tcp_acl/udp_acl."
    nw_udp_listen:
        type: str
        description:
            de: "Über die nw_udp_listen Einstellung kann ein dedizierter Listener spezifiziert werden. Das Argument kann ein Port oder IP:Port sein (z.B.: nw_udp_listen: 127.0.0.1:8888 or nw_udp_listen: 7777)."
            en: "You could specify the nw_udp_listen attribute to an item to create a dedicated listener. The argument could be a port or ip:port. (e.g.: nw_udp_listen: 127.0.0.1:8888 or nw_udp_listen: 7777)"
    nw_tcp_listen:
        type: str
        description:
            de: "Über die nw_tcp_listen Einstellung kann ein dedizierter Listener spezifiziert werden. Das Argument kann ein Port oder IP:Port sein (z.B.: nw_tcp_listen: 127.0.0.1:8888 or nw_tcp_listen: 7777)."
            en: "You could specify the nw_tcp_listen attribute to an item to create a dedicated listener. The argument could be a port or ip:port. (e.g.: nw_tcp_listen: 127.0.0.1:8888 or nw_tcp_listen: 7777)"
    nw_udp_send:
        type: str
        description:
            de: "Dieses Attribut erlaubt es, einen Host und einen Port zu konfigurieren, an den Updates gesendet werden (z.B.:  nw_udp_send: 10.0.0.1:8888)."
            en: "This attribute allows you to specify a host and port to send item updates to. (e.g.: nw_udp_send: 10.0.0.1:8888)"

plugin_functions:
# Definition of plugin functions defined by this plugin
#    def udp(self, host, port, data):
    udp:
        type: void
        description:
            de: "Senden einer Nachricht über UDP"
            en: "Sends a message using UDP"
        parameters:
            host:
                type: str
                description:
                    de: "Host oder IP Adresse des Zieles"
                    en: "Destination host or ip address"
            port:
                type: int
                description:
                    de: "Port auf dem Zielsystem"
                    en: "Port on destination system"
            data:
                type: foo
                description:
                    de: "Zu übertragende Daten"
                    en: "Data to transmit"


logic_parameters:
    # Definition of item attributes defined by this plugin
    nw:
        type: bool
        default: False
        valid_list:
          - True
          - False
        valid_list_description:
            de: ['Logik kann über TCP/UDP getriggert werden', 'Logik kann nicht über TCP/UDP getriggert werden']
            en: ['Logic can be triggered by TCP/UDP', 'Logic cannot be triggered by TCP/UDP']
        description:
            de: 'Wenn dieses Attribut auf "True" (oder "yes", etc.) gesetzt wird, kann diese Logik über den generischen Listener des Network Plugins über TCP und/oder UDP aufgerufen werden.'
            en: 'If this attribute is set to "True" (or "yes", etc.) you could trigger this logic with the generic listener (TCP and/or UDP).'
    nw_acl:
        type: list
        description:
            de: "Wie bei dem generischen Plugin-Attribut tcp_acl/udp_acl, kann eine Liste oder eine einzelne IP Adresse konfiguriert werden. Nur von dieser/diesen darf die Logik getriggered werden. Das Attribut \
                überschreibt die Einstellung in der Pluginkonfiguration."
            en: "Like the generic tcp_acl/udp_acl a list or single IP address to limit updates from. This attribute is valid for TCP and UDP and overrides the generic tcp_acl/udp_acl."

    nw_udp_listen:
        type: str
        description:
            de: "Über die nw_udp_listen Einstellung kann ein dedizierter Listener spezifiziert werden. Das Argument kann ein Port oder IP:Port sein (z.B.: nw_udp_listen: 127.0.0.1:8888 or nw_udp_listen: 7777)."
            en: "You could specify the nw_udp_listen attribute to an item to create a dedicated listener. The argument could be a port or ip:port. (e.g.: nw_udp_listen: 127.0.0.1:8888 or nw_udp_listen: 7777)"
    nw_tcp_listen:
        type: str
        description:
            de: "Über die nw_tcp_listen Einstellung kann ein dedizierter Listener spezifiziert werden. Das Argument kann ein Port oder IP:Port sein (z.B.: nw_tcp_listen: 127.0.0.1:8888 or nw_tcp_listen: 7777)."
            en: "You could specify the nw_udp_listen attribute to an item to create a dedicated listener. The argument could be a port or ip:port. (e.g.: nw_tcp_listen: 127.0.0.1:8888 or nw_tcp_listen: 7777)"

item_structs: NONE
