# This code needs to be copied into the existing <shNG>/etc/logging.yaml
# The corresponding logs can be found in <shNG>/var/log
#
# WARNING - changing to 'DEBUG can produce huge amounts of data within short time

loggers:
    plugins.trovis557x:
        handlers: [shng_details_file]
        level: WARNING
        # level: DEBUG
