# uncomment only if you want to have debug messages
# WARNING - can produce big amounts of data within short time

# loggers:
#    plugins.trovis557x:
#        handlers: [shng_details_file]
#        level: DEBUG
