# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                     # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Ermöglicht den Abruf deutscher Schulferien für die Bundesländer BW, BY, BE, BB, HB, HH, HE, MV, NI, NW, RP, SL, SN, ST, SH, TH.'
        en: 'Enables the retrieval of German school vacations for the provinces BW, BY, BE, BB, HB, HH, HE, MV, NI, NW, RP, SL, SN, ST, SH, TH.'
    maintainer: Marc René Frieß
#    tester:                        # Who tests this plugin?
    state: develop
    keywords: vacations
    documentation: 'http://smarthomeng.de/user/plugins_doc/config/vacations.html'   # url of documentation (wiki) page
    support: 'https://knx-user-forum.de/forum/supportforen/smarthome-py/1443788-support-thread-f%C3%BCr-das-vacations-plugin'

    version: 1.0.0                 # Plugin version
    sh_minversion: 1.6             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: Vacations           # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml

item_attributes: NONE
    # Definition of item attributes defined by this plugin

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin

    get_vacation:
        type: foo
        description:
            de: "Gibt ein \"Vacation\" Objekt (siehe https://pypi.org/project/ferien-api/), zu einem Datum zurück (aktuelles Datum, falls der Parameter leer gelassen wird)."
            en: "Returns a \"Vacation\" object (see https://pypi.org/project/ferien-api/) to a given date (Default, if parameter is left empty: now())."
        parameters:
            date:
                type: str
                mandatory: False
                description:
                    de: "Zu prüfendes Datum als String in der Form \"yyyy-mm-ddd\", \"yy-mm-dd\", \"dd.mm.yyyy\" oder \"dd.mm.yy\". Default, wenn Parameter nicht genutzt wird: now()"
                    en: "Date to check - in the form: \"yyyy-mm-ddd\", \"yy-mm-dd\", \"dd.mm.yyyy\" or \"dd.mm.yy\". (Default, if parameter is left empty: now())."
            province:
                type: str
                mandatory: False
                description:
                    de: "Zu prüfendes Bundesland. Default, falls Parameter leer gelassen wird: SHNG Einstellungen aus etc/holidays.yaml."
                    en: "Province to check. Default, if parameter is left empty: SHNG Settings from etc/holidays.yaml"
                valid-list:
                    - BW
                    - BY
                    - BE
                    - BB
                    - HB
                    - HH
                    - HE
                    - MV
                    - NI
                    - NW
                    - RP
                    - SL
                    - SN
                    - ST
                    - SH
                    - TH

    get_vacation_name:
        type: str
        description:
            de: "Gibt den Namen der Schulferien zu einem Datum zurück (aktuelles Datum, falls der Parameter leer gelassen wird)."
            en: "Returns the name of the German school vacations related to a given date (Default, if parameter is left empty: now())."
        parameters:
            date:
                type: str
                mandatory: False
                description:
                    de: "Zu prüfendes Datum als String in der Form \"yyyy-mm-ddd\", \"yy-mm-dd\", \"dd.mm.yyyy\" oder \"dd.mm.yy\". Default, wenn Parameter nicht genutzt wird: now()"
                    en: "Date to check - in the form: \"yyyy-mm-ddd\", \"yy-mm-dd\", \"dd.mm.yyyy\" or \"dd.mm.yy\". (Default, if parameter is left empty: now())."
            province:
                type: str
                mandatory: False
                description:
                    de: "Zu prüfendes Bundesland. Default, falls Parameter leer gelassen wird: SHNG Einstellungen aus etc/holidays.yaml."
                    en: "Province to check. Default, if parameter is left empty: SHNG Settings from etc/holidays.yaml"
                valid-list:
                    - BW
                    - BY
                    - BE
                    - BB
                    - HB
                    - HH
                    - HE
                    - MV
                    - NI
                    - NW
                    - RP
                    - SL
                    - SN
                    - ST
                    - SH
                    - TH

    is_vacation:
        type: bool
        description:
            de: "Prüft, ob zu einem angegebenen Datum (aktuelles, falls der Parameter leer gelassen wird), Schulferien sind."
            en: "Checks if there are school vacations at a given date. (Default, if parameter is left empty: now())."
        parameters:
            date:
                type: str
                mandatory: False
                description:
                    de: "Zu prüfendes Datum als String in der Form \"yyyy-mm-ddd\", \"yy-mm-dd\", \"dd.mm.yyyy\" oder \"dd.mm.yy\". Default, wenn Parameter nicht genutzt wird: now()"
                    en: "Date to check - in the form: \"yyyy-mm-ddd\", \"yy-mm-dd\", \"dd.mm.yyyy\" or \"dd.mm.yy\". (Default, if parameter is left empty: now())."
            province:
                type: str
                mandatory: False
                description:
                    de: "Zu prüfendes Bundesland. Default, falls Parameter leer gelassen wird: SHNG Einstellungen aus etc/holidays.yaml."
                    en: "Province to check. Default, if parameter is left empty: SHNG Settings from etc/holidays.yaml"
                valid-list:
                - BW
                - BY
                - BE
                - BB
                - HB
                - HH
                - HE
                - MV
                - NI
                - NW
                - RP
                - SL
                - SN
                - ST
                - SH
                - TH