#!/usr/bin/env python3
# vim: set encoding=utf-8 tabstop=4 softtabstop=4 shiftwidth=4 expandtab

"""commands/lookups for Viessmann model ALL"""

MODEL = 'ALL'

commands = {
    'Anlagentyp': {
        'read': True,
        'write': False,
        'opcode': '00f8',
        'reply_pattern': '*',
        'item_type': 'str',
        'dev_datatype': 'Hex',
        'params': {'value': 'VAL', 'len': 2},
        'lookup': 'devicetypes',
        'item_attrs': {'no_read_groups': True, 'initial': True},
    }  # getAnlTyp -- Information - Allgemein: Anlagentyp (204D)
}

lookups = {
    'devicetypes': {
        '2098': 'V200KW2',  # Protokoll: KW
        '2053': 'GWG_VBEM',  # Protokoll: GWG
        '20CB': 'VScotHO1_200_11',  # Protokoll: P300
        '2094': 'V200KW1',  # Protokoll: KW
        '209F': 'V200KO1B',  # Protokoll: P300
        '204D': 'V200WO1C',  # Protokoll: P300
        '20B8': 'V333MW1',
        '20A0': 'V100GC1',
        '20C2': 'VDensHO1',
        '20A4': 'V200GW1',
        '20C8': 'VPlusHO1',
        '2046': 'V200WO1',
        '2047': 'V200WO1',
        '2049': 'V200WO1',
        '2032': 'VBC550',
        '2033': 'VBC550',
    },
    'errors': {
        '00': 'Regelbetrieb (kein Fehler)',
        '0F': 'Wartung (fuer Reset Codieradresse 24 auf 0 stellen)',
        '10': 'Kurzschluss Aussentemperatursensor',
        '18': 'Unterbrechung Aussentemperatursensor',
        '19': 'Unterbrechung Kommunikation Aussentemperatursensor RF',
        '1D': 'Keine Kommunikation mit Sensor',
        '1E': 'Strömungssensor defekt',
        '1F': 'Strömungssensor defekt',
        '20': 'Kurzschluss Vorlauftemperatursensor',
        '21': 'Kurzschluss Ruecklauftemperatursensor',
        '28': 'Unterbrechung Aussentemperatursensor / Vorlauftemperatursensor Anlage',
        '29': 'Unterbrechung Ruecklauftemperatursensor',
        '30': 'Kurzschluss Kesseltemperatursensor',
        '38': 'Unterbrechung Kesseltemperatursensor',
        '40': 'Kurzschluss Vorlauftemperatursensor M2',
        '42': 'Unterbrechung Vorlauftemperatursensor M2',
        '44': 'Kurzschluss Vorlauftemperatursensor Heizkreis 3',
        '48': 'Unterbrechung Vorlauftemperatursensor Heizkreis 3',
        '50': 'Kurzschluss Speichertemperatursensor',
        '51': 'Kurzschluss Auslauftemperatursensor',
        '58': 'Unterbrechung Speichertemperatursensor',
        '59': 'Unterbrechung Auslauftemperatursensor',
        '70': 'Gasdruckwächter verhindert Brennerstart',
        '71': 'Netzspannung zu niedrig',
        '73': 'Rückmeldeeingang der internen Erweiterung H1 verhindert Brennerstart',
        '74': 'Masseschluss Temperaturbegrenzer',
        '75': 'Masseschluss interne Erweiterung H1/H2',
        '76': 'Masseschluss Gasdruckwächter',
        '80': 'Unzureichende Gasversorgung',
        '81': 'Kein Zündfunke vorhanden',
        '82': 'Flammensignal ist bei Brennerstart nicht vorhanden oder zu gering',
        '83': 'Flammensignal ist bei Brennerstart bereits vorhanden',
        '84': 'Geräteinterner CO-Grenzwert überschritten',
        '85': 'Gasversorgung während der Kalibrierung unzureichend',
        '90': 'Kurzschluss Temperatursensor 7',
        '91': 'Kurzschluss Temperatursensor 10',
        '92': 'Solar: Kurzschluss Kollektortemperatursensor',
        '93': 'Solar: Kurzschluss Sensor S3',
        '94': 'Solar: Kurzschluss Speichertemperatursensor',
        '9A': 'Solar: Unterbrechung Kollektortemperatursensor',
        '9B': 'Solar: Unterbrechung Sensor S3',
        '9C': 'Solar: Unterbrechung Speichertemperatursensor',
        '9E': 'Solar: Zu geringer bzw. kein Volumenstrom oder Temperaturwächter ausgeloest',
        '9F': 'Solar: Fehlermeldung Solarteil (siehe Solarregler)',
        'A4': 'Amx. Anlagendruck überschritten',
        'A7': 'Bedienteil defekt',
        'A8': 'Luft in der internen Umwaelzpumpe oder Mindest-Volumenstrom nicht erreicht',
        'B0': 'Kurzschluss Abgastemperatursensor',
        'B1': 'Kommunikationsfehler Bedieneinheit',
        'B4': 'Interner Fehler (Elektronik)',
        'B5': 'Interner Fehler (Elektronik)',
        'B6': 'Ungueltige Hardwarekennung (Elektronik)',
        'B7': 'Interner Fehler (Kesselkodierstecker)',
        'B8': 'Unterbrechung Abgastemperatursensor',
        'B9': 'Interner Fehler (Dateneingabe wiederholen)',
        'V': 'Kommunikationsfehler Erweiterungssatz fuer Mischerkreis M2',
        'BB': 'Kommunikationsfehler Erweiterungssatz fuer Mischerkreis 3',
        'BC': 'Kommunikationsfehler Fernbedienung Vitorol, Heizkreis M1',
        'BD': 'Kommunikationsfehler Fernbedienung Vitorol, Heizkreis M2',
        'BE': 'Falsche Codierung Fernbedienung Vitorol',
        'BF': 'Falsches Kommunikationsmodul LON',
        'C1': 'Externe Sicherheitseinrichtung (Kessel kuehlt aus)',
        'C2': 'Kommunikationsfehler Solarregelung',
        'C3': 'Kommunikationsfehler Erweiterung AM1',
        'C4': 'Kommunikationsfehler Erweiterumg Open Therm',
        'C5': 'Kommunikationsfehler drehzahlgeregelte Heizkreispumpe, Heizkreis M1',
        'C6': 'Kommunikationsfehler drehzahlgeregelte Heizkreispumpe, Heizkreis M2',
        'C7': 'Falsche Codierung der Heizkreispumpe',
        'C8': 'Kommunikationsfehler drehzahlgeregelte, externe Heizkreispumpe 3',
        'C9': 'Stoermeldeeingang am Schaltmodul-V aktiv',
        'CD': 'Kommunikationsfehler Vitocom 100 (KM-BUS)',
        'CE': 'Kommunikationsfehler Schaltmodul-V',
        'CF': 'Kommunikationsfehler LON Modul',
        'D1': 'Brennerstoerung',
        'D4': 'Sicherheitstemperaturbegrenzer hat ausgeloest oder Stoermeldemodul nicht richtig gesteckt',
        'D6': 'Eingang DE1 an Erweiterung EA1 meldet eine Stoerung',
        'D7': 'Eingang DE2 an Erweiterung EA1 meldet eine Stoerung',
        'D8': 'Eingang DE3 an Erweiterung EA1 meldet eine Stoerung',
        'D': 'Kurzschluss Raumtemperatursensor, Heizkreis M1',
        'DB': 'Kurzschluss Raumtemperatursensor, Heizkreis M2',
        'DC': 'Kurzschluss Raumtemperatursensor, Heizkreis 3',
        'DD': 'Unterbrechung Raumtemperatursensor, Heizkreis M1',
        'DE': 'Unterbrechung Raumtemperatursensor, Heizkreis M2',
        'DF': 'Unterbrechung Raumtemperatursensor, Heizkreis 3',
        'E0': 'Fehler externer LON Teilnehmer',
        'E1': 'Isolationsstrom waehrend des Kalibrierens zu hoch',
        'E3': 'Zu geringe Wärmeabnahme während des Kalibrierens, Temperaturwächter hat ausgeschaltet',
        'E4': 'Fehler Versorgungsspannung',
        'E5': 'Interner Fehler, Flammenverstärker(Ionisationselektrode)',
        'E6': 'Abgas- / Zuluftsystem verstopft, Anlagendruck zu niedrig',
        'E7': 'Ionisationsstrom waehrend des Kalibrierens zu gering',
        'E8': 'Ionisationsstrom nicht im gültigen Bereich',
        'EA': 'Ionisationsstrom waehrend des Kalibrierens nicht im gueltigen Bereich',
        'EB': 'Wiederholter Flammenverlust waehrend des Kalibrierens',
        'EC': 'Parameterfehler waehrend des Kalibrierens',
        'ED': 'Interner Fehler',
        'EE': 'Flammensignal ist bei Brennerstart nicht vorhanden oder zu gering',
        'EF': 'Flammenverlust direkt nach Flammenbildung (waehrend der Sicherheitszeit)',
        'F0': 'Interner Fehler (Regelung tauschen)',
        'F1': 'Abgastemperaturbegrenzer ausgeloest',
        'F2': 'Temperaturbegrenzer ausgeloest',
        'F3': 'Flammensigal beim Brennerstart bereits vorhanden',
        'F4': 'Flammensigal nicht vorhanden',
        'F7': 'Differenzdrucksensor defekt, Kurzschluss ider Wasserdrucksensor',
        'F8': 'Brennstoffventil schliesst zu spaet',
        'F9': 'Geblaesedrehzahl beim Brennerstart zu niedrig',
        'FA': 'Geblaesestillstand nicht erreicht',
        'FC': 'Gaskombiregler defekt oder fehlerhafte Ansteuerung Modulationsventil oder Abgasweg versperrt',
        'FD': 'Fehler Gasfeuerungsautomat, Kesselkodierstecker fehlt(in Verbindung mit B7)',
        'FE': 'Starkes Stoerfeld (EMV) in der Naehe oder Elektronik defekt',
        'FF': 'Starkes Stoerfeld (EMV) in der Naehe oder interner Fehler',
    },
    'operatingmodes': {
        '00': 'Abschaltbetrieb',
        '01': 'Reduzierter Betrieb',
        '02': 'Normalbetrieb',
        '03': 'Dauernd Normalbetrieb',
    },
    'returnstatus': {'00': '0', '01': '1', '03': '2', 'AA': 'NOT OK'},
    'setreturnstatus': {'00': 'OK', '05': 'SYNC (NOT OK)'},
}
