# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Unterstützung für Smartmeter, die DLMS (Device Language Message Specification, IEC 62056-21) nutzen und OBIS Codes liefern'
        en: 'Support for smartmeter using DLMS (Device Language Message Specification, IEC 62056-21) and delivering OBIS codes'
    maintainer: bmxp
    tester: NONE                   # Who tests this plugin?
    state: ready
    keywords: dlms obis smartmeter
    #documentation: http://smarthomeng.de/user/plugins/dlms/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1002464-support-thread-für-dlms-plugin

    version: 1.9.5                 # Plugin version
    sh_minversion: '1.8'             # minimum shNG version to use this plugin
    #sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    py_minversion: '3.6'             # minimum Python version to use for this plugin, due to f-strings
    # py_maxversion:               # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: DLMS                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    serialport:
        type: str
        description:
            de: 'Serieller Port an dem der Smartmeter angeschlossen ist'
            en: 'serial port at which the smartmeter is attached'
    baudrate:
        type: int
        valid_min: 50
        default: 300
        description:
            de: 'Baudrate bei der die Kommunikation erfolgen soll'
            en: 'Baudrate at which the communikation should take place'
    baudrate_fix:
        type: bool
        default: False
        description:
            de: 'Baudrate beibehalten trotz Änderungsanforderung'
            en: 'Keep up baudrate in communication despite of change request'
    update_cycle:
        type: int
        valid_min: 0
        default: 60
        description:
            de: 'Zeitlicher Abstand zwischen zwei Abfragen des Smartmeters in Sekunden, setzen auf 0 schaltet cycle aus'
            en: 'Time between two queries of smartmeter in seconds, set to zero will switch off usage of cycle'
    update_cycle_start_offset:
        type: int
        valid_min: 0
        default: 0
        description:
            de: 'Zeit die beim Start des Plugins zusätzlich gewartet wird, damit sich verschiedene Instanzen die gleiche Schnittstellen abfragen nicht in die Quere kommen'
            en: 'Time which gets added to the start of first query. This prevents interference between two instances using the same interface'
    update_crontab:
        type: str
        description:
            de: 'Abfragen des Smartmeters mit Festlegung via Crontab'
            en: 'Queries of smartmeter by means of a crontab'
    device_address:
        type: str
        default: ''
        description:
            de: 'Interne Unteradresse des Smartmeters'
            en: 'Internal subadress of smartmeter'
    querycode:
        type: str
        default: '?'
        description:
            de: 'Abfragecode für den Smartmeter, default ist `?`, einige Smartmeter akzeptieren z.B. `2`'
            en: 'querycode of smartmeter, defaults to `?`, some smartmeter accept e.g. `2`'
    timeout:
        type: int
        default: 2
        description:
            de: 'Timeout in Sekunden nach dem der Lesevorgang automatisch beendet wird'
            en: 'timeout in seconds for automatic abortion of readout'
    use_checksum:
        type: bool
        default: True
        description:
            de: 'Wenn wahr, wird eine Prüfsumme über die ausgelesenen Daten gebildet'
            en: 'if true then a checksum will be calculated of the readout result'
    only_listen:
        type: bool
        default: False
        description:
            de: 'Manche Smartmeter können nicht abgefragt werden sondern senden von sich aus Informationen. Für diese Smartmeter auf True setzen und die Baudrate anpassen'
            en: 'Some smartmeter can not be queried, they send information without request. For those devices set to True and adjust baudrate'
    reset_baudrate:
        type: bool
        default: True
        description:
            de: 'derzeit nicht genutzt'
            en: 'not used currently'
    no_waiting:
        type: bool
        default: False
        description:
            de: 'derzeit nicht genutzt'
            en: 'not used currently'

item_attributes:
    # Definition of item attributes defined by this plugin
    dlms_obis_code:
        type: list(4,str,int,str,str)
        description:
            de: >
                Anweisung welcher Teil einer OBIS Zeile geparst und dem Item zugewiesen werden soll
                * obis Code ``1-1:1.6.2*01``
                * Index
                * Entweder Wert also 'Value' oder Einheit also 'Unit'
                * Wert Konvertierungsart
                    * Z6 (Zeit codiert mit hhmmss),
                    * Z4 (Zeit codiert mit hhmm),
                    * D6 (Datum codiert mit YYMMDD),
                    * ZST10 (Datum und Zeit codiert mit YYMMDDhhmm),
                    * ZST12 (Datum und Zeit codiert mit YYMMDDhhmmss),
                    * str eine Zeichenkette
                    * float eine Fliesskommazahl
                    * int ein ganze Zahl
                    * num Numerisch, entweder Ganzzahl oder Fliesskommazahl
            en: >
                instruction which part of obis line should be parsed and assigned to an item `1-1:1.6.2*01|Index|Value/Unit|Value Type`'
                * obis Code ``1-1:1.6.2*01``
                * Index
                * Either 'Value' or 'Unit'
                * Value conversion
                    * Z6 (time coded with hhmmss),
                    * Z4 (time coded with hhmm),
                    * D6 (date coded with YYMMDD),
                    * ZST10 (date and time coded with YYMMDDhhmm),
                    * ZST12 (date and time coded with YYMMDDhhmmss),
                    * str, a string
                    * float, a floating point number
                    * int an integer
                    * num a number either float or int
    dlms_obis_readout:
        type: str
        description:
            de: 'In Items mit diesem Attribut wird der komplette Auslesepuffer abgelegt für eigene Untersuchungen'
            en: 'in items with this attribut the complete readout will be set for examination with own logics'

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

item_structs: NONE

