plugin:
    type: system                # plugin type (system, gateway, interface, protocol, cloud)
    subtype: core               # plugin subtype (if applicable)
    version: 1.3.5              # Plugin version
#   keywords:                   # keywords, where applicable
    sh_minversion: 1.3          # minimum shNG version to use this plugin
#   sh_maxversion:              # maximum shNG version to use this plugin (if not latest)
    multi_instance: false       # plugin supports multi instance
    description: 'Web Interface zur Anzeige von Informationen zum System und SmartHomeNG Backend-Daten'
#   documentation:              # url of wiki page
    maintainer: psilo909, msinn, bmxp, cmalo      # Who maintains this plugin?
    tester: Sandman60           # Who tests this plugin?

