# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: "Ermöglicht die Verwendung der Join API (https://joaoapps.com/join/api/)"
        en: "This plugin allows to send command to your mobile phone via the Join API: https://joaoapps.com/join/api/"
    maintainer: Knx_fan
    tester: psilo909
    state: ready
#    keywords: iot xyz
    documentation: http://smarthomeng.de/user/plugins_doc/config/join.html        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1113523-neues-plugin-join-tts-sms-phonecall-notification-uvm

    version: 1.4.1.0               # Plugin version
    sh_minversion: 1.3a            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: Join                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    device_id:
        type: str
        mandatory: True
        description:
            de: 'Join Device ID'
            en: 'Your own personal Join device id.'

    api_key:
        type: str
        mandatory: True
        description:
            de: 'Persönlicher Join API key'
            en: 'Your own personal Join api key.'

item_attributes: NONE
    # Definition of item attributes defined by this plugin

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

plugin_functions:
# Definition of plugin functions defined by this plugin
    send:
        description:
            de: "send Funktion"
            en: "send function"
        parameters:
            title:
                type: str
                default: None
                description:
                    de: "Titel"
                    en: "Title"
            text:
                type: str
                default: None
                description:
                    de: "Text"
                    en: "Text"
            icon:
                type: str
                default: None
                description:
                    de: "Icon"
                    en: "Icon"
            find:
                type: str
                default: None
                description:
                    de: "Find"
                    en: "Find"
            smallicon:
                type: str
                default: None
                description:
                    de: "Smallicon"
                    en: "Smallicon"
            device_id:
                type: str
                default: None
                description:
                    de: "Device_id"
                    en: "Device_id"
            device_ids:
                type: str
                default: None
                description:
                    de: "Device_ids"
                    en: "Device_ids"
            device_name:
                type: str
                default: None
                description:
                    de: "Device_names"
                    en: "Device_names"
            url:
                type: str
                default: None
                description:
                    de: "Url"
                    en: "Url"
            image:
                type: str
                default: None
                description:
                    de: "Image"
                    en: "Image"
            sound:
                type: str
                default: None
                description:
                    de: "Sound"
                    en: "Sound"
            group:
                type: str
                default: None
                description:
                    de: "Group"
                    en: "Group"
            clipboard:
                type: str
                default: None
                description:
                    de: "Clipboard"
                    en: "Clipboard"
            file:
                type: str
                default: None
                description:
                    de: "File"
                    en: "File"
            callnumber:
                type: str
                default: None
                description:
                    de: "Callnumber"
                    en: "Callnumber"
            smsnumber:
                type: str
                default: None
                description:
                    de: "Smsnumber"
                    en: "Smsnumber"
            smstext:
                type: str
                default: None
                description:
                    de: "Smstext"
                    en: "Smstext"
            mmsfile:
                type: str
                default: None
                description:
                    de: "Mmsfile"
                    en: "Mmsfile"
            wallpaper:
                type: str
                default: None
                description:
                    de: "Wallpaper"
                    en: "Wallpaper"
            lockwallpaper:
                type: str
                default: None
                description:
                    de: "Lockwallpaper"
                    en: "Lockwallpaper"
            interruptionFilter:
                type: str
                default: None
                description:
                    de: "InterruptionFilter"
                    en: "InterruptionFilter"
            mediaVolume:
                type: str
                default: None
                description:
                    de: "MediaVolume"
                    en: "MediaVolume"
            ringVolume:
                type: str
                default: None
                description:
                    de: "RingVolume"
                    en: "RingVolume"
            alarmVolume:
                type: str
                default: None
                description:
                    de: "AlarmVolume"
                    en: "AlarmVolume"

