# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Husqvarna Automower Plugin (unterstützt das neue API)'
        en: 'Husqvarna automower plugin (supporting the new API)'
    maintainer: gruberth
#    tester:                         # Who tests this plugin?
    state: develop                  # change to ready when done with development
    keywords: mower, husqvarna, automover, lawn
    documentation: https://www.smarthomeng.de/user/plugins/husky2/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1764058-support-thread

    version: 2.1.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.8              # minimum shNG version to use this plugin
    multi_instance: false           # plugin supports multi instance
    restartable: unknown
    classname: Husky2         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    apikey:
        type: str
        mandatory: True
        description:
            de: 'Husqvarna api key'
            en: 'Husqvarna api key'
    apisecret:
        type: str
        mandatory: True
        description:
            de: 'Husqvarna api secret für den Login'
            en: 'Husqvarna api secret login'
    device:
        type: str
        mandatory: False
        default: ''
        description:
            de: '(optional) ID oder Name des Mähroboters, falls mehrere im Benutzkonto registriert sind'
            en: '(optional) Id or name of the automower if there is more than one registered in the user account'
    historylength:
        type: num
        mandatory: False
        default: 200
        description:
            de: '(optional) Anzahl der Statusmeldungen die im Arbeitsspeicher für die Anzeige im Webinterface gespeichert werden sollen'
            en: '(optional) Number of state messages to be saved in ram for history display in the web interface'
    maxgpspoints:
        type: num
        mandatory: False
        default: 20
        description:
            de: '(optional) Anzahl der letzten GPS Punkte die im gpsoints-Item gespeichert werden sollen'
            en: '(optional) Number of last gps points to be saved in the gpspoints item'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    husky_info:
        type: str
        valid_list: ['name', 'id', 'serial', 'model']
        description:
            de: 'Das Item, welches mit allgemeinen Informationen (z.B. Modell) durch das Plugin beschrieben werden soll'
            en: 'Item that shoul receive general information (e.g. model) by the plugin'

    husky_state:
        type: str
        valid_list: ['message', 'state', 'activity', 'mode', 'errormessage', 'batterypercent', 'connection', 'longitude', 'latitude', 'gpspoints']
        description:
            de: 'Das Item, welches mit Status Informationen (z.B. Aktivität) durch das Plugin beschrieben werden soll'
            en: 'Item that should receive status information (e.g. activity) by the plugin'

    husky_control:
        type: str
        valid_list: ['starttime', 'starttime', 'pause', 'parkpermanent', 'parktime', 'parknext', 'resume', 'cuttingheight', 'headlight']
        description:
            de: 'Das Item, mit dem der Mähroboter gesteuert werden soll (z.B. Start Kommando)'
            en: 'Item to control the mower (e.g. start command)'

item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)
    basic:
        name: Default Mower Template

        info:
            name: Mower information

            device:
                husky_info: name
                type: str
                visu_acl: ro

            model:
                husky_info: model
                type: str
                visu_acl: ro

            id:
                husky_info: id
                type: str
                visu_acl: ro

            serial:
                husky_info: serial
                type: num
                visu_acl: ro

        state:
            name: State information

            connection:
                name: mower connection state
                husky_state: connection
                type: bool
                visu_acl: ro

            activity:
                name: activity [ UNKNOWN, NOT_APPLICABLE, MOWING, GOING_HOME, CHARGING, LEAVING, PARKED_IN_CS, STOPPED_IN_GARDEN ] # See locale.yaml
                husky_state: activity
                type: str
                visu_acl: ro

            errormessage:
                husky_state: errormessage
                type: str
                visu_acl: ro
                initial_value: 'no error'

            message:
                husky_state: errormessage
                type: str
                visu_acl: ro
                initial_value: 'Ok'

            mode:
                name: mode [ MAIN_AREA, SECONDARY_AREA, HOME, DEMO, UNKNOWN ] # See locale.yaml
                husky_state: mode
                type: str
                visu_acl: ro

            state:
                name: state [ UNKNOWN, NOT_APPLICABLE, PAUSED, IN_OPERATION, WAIT_UPDATING, WAIT_POWER_UP, RESTRICTED, OFF, STOPPED, ERROR, FATAL_ERROR, ERROR_AT_POWER_UP ] # See locale.yaml
                husky_state: state
                type: str
                visu_acl: ro

            batterypercent:
                husky_state: batterypercent
                type: num
                visu_acl: ro

            battery255:
                type: num
                visu_acl: ro
                eval: int(value * 255 / 100)
                eval_trigger: ..batterypercent

            longitude:
                name: mower gps longitude
                husky_state: longitude
                type: num
                visu_acl: ro

            latitude:
                name: mower gps latitude
                husky_state: latitude
                type: num
                visu_acl: ro

            gpspoints:
                name: mower last gps points
                husky_state: gpspoints
                type: list
                visu_acl: ro

        control:
            name: Control commands

            start3H:
                name: Start
                type: num
                husky_control: starttime
                visu_acl: rw
                initial_value: 180
                enforce_updates: True

            resume:
                name: Start
                type: bool
                husky_control: resume
                visu_acl: rw
                enforce_updates: True

            stop:
                name: Stop
                type: bool
                husky_control: pause
                visu_acl: rw
                enforce_updates: True

            park3H:
                name: Park
                type: num
                husky_control: parktime
                visu_acl: rw
                initial_value: 180
                enforce_updates: True

            parkPermantent:
                name: Park
                type: bool
                husky_control: parkpermanent
                visu_acl: rw
                enforce_updates: True

            parkUntilNext:
                name: Park
                type: bool
                husky_control: parknext
                visu_acl: rw
                enforce_updates: True

            cuttingHeight:
                name: cutting height [1, 2, 3, 4, 5, 6, 7, 8, 9]
                husky_control: cuttingheight
                type: num
                visu_acl: rw
                enforce_updates: True
                cache: true

            headLight:
                name: headLight settings [ ALWAYS_ON, ALWAYS_OFF, EVENING_ONLY, EVENING_AND_NIGHT ]
                husky_control: headlight
                type: str
                visu_acl: rw
                enforce_updates: True

item_attribute_prefixes: NONE
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
