# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Integration von 2N SIP-Türsprechanlagen'
        en: 'Control SIP doorstations from 2N'
    maintainer: pfischi
    tester: '?'                    # Who tests this plugin?
#    keywords: iot xyz
    state: ready
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1030539-plugin-2n-intercom

    version: 1.3.0.1               # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: Intercom2n          # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
#    def __init__(self, sh, intercom_ip, ssl=False, auth_type=0, username=None, password=None):
    intercom_ip:
        type: ip
        description:
            de: "Intercom IP Adresse"
            en: "IP address of Intercom"
    ssl:
        type: bool
        default: False
        description:
            de: "ssl Verschlüsselung verwenden"
            en: "Use ssl encryption"
    auth_type:
        type: int
        default: 0
        valid_min: 0
        valid_max: 2
        description:
            de: "Zu verwendender auth_type (0: no authentication, 1: Basic Authentication, 2: Digest Authentication)"
            en: "auth_type to use (0: no authentication, 1: Basic Authentication, 2: Digest Authentication)"
    username:
        type: str
        default: None*
        description:
            de: "Benutzername, falls auth_type > 0"
            en: "Usernam, falls auth_type > 0"
    password:
        type: str
        default: None*
        description:
            de: "Passwort, falls auth_type > 0"
            en: "Password, falls auth_type > 0"

item_attributes:
    # Definition of item attributes defined by this plugin

item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

