# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Sendet Kommandos an lircd das wiederum IR-Signale an Geräte mit IR-Schnittstelle versendet'
        en: 'Sends commands to lircd that sends IR-signals to any device that has an IR-interface'
    maintainer: E3EAT
    tester: Onkelandy
    keywords: infrared
    state: ready
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/lirc/....md
#    support:

    version: 1.4.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    classname: LIRC                # class containing the plugin


parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    lirc_host:
        type: str
        mandatory: True
        description:
            de: 'IP oder Hostname des lircd'
            en: 'IP or hostname of the lircd'

    lirc_port:
        type: int
        default: 8765
        description:
            de: 'Der Port auf dem lircd lauscht.'
            en: 'The port that is used by lircd.'

item_attributes:
    # Definition of item attributes defined by this plugin
    lirc_remote:
        type: str
        description:
            de: 'Name der Fernbedienung. Der Name muss dem Namen der Fernbedienung in lircrc entsprechen.'
            en: 'The name of the remote. This name has to match the name of the remote in lircd.'

    lirc_key:
        type: str
        description:
            de: 'Name der Taste auf der Fernbedienung. Der Name muss dem Namen der Fernbedienung in lircrc entsprechen.'
            en: 'The name of the key on the given remote. This name has to match the name of the key in lircd. '

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

plugin_functions: NONE
# Definition of plugin functions defined by this plugin

