# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung von Kodi (ehemals XBMC) v12 (Frodo) oder neuer'
        en: 'Connecting Kodi (formerly XBMC) v12 (Frode) or newer'
    maintainer: ggf. msinn
    tester: onkelandy
    state: develop
    keywords: mediacenter
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

# Following entries are for Smart-Plugins:
    version: 1.3c.0                 # Plugin version
    sh_minversion: 1.3c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True
    classname: Kodi                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    host:
        type: ipv4
        mandatory: True

    port:
        type: int
        valid_min: 0
        default: 9090
        description:
            en: 'English description'

    instance:
        type: str
        default: ''
        description:
            de: 'Eindeutiger Identifier für die Instanz des Plugins. Kann bei nur einer konfigurierten Instanz des Plugins entfallen.'
            en: 'Unique identifier for each instance of the plugin. Can be omitted if only one device instance of the plugin is configured.'


item_attributes:
    # Definition of item attributes defined by this plugin

    kody_item:
        type: str
        valid_list: ['on_off', 'volume', 'mute', 'title', 'media', 'state', 'favorites', 'input']
        description:
            de: ''
            en: ''

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin

    notify:
        type: str
        description:
            de: "Diese Funktion ermöglicht es, Mitteilungen an Kodi zu schicken. Beispiel: sh.living.kodi.notify('Door', 'Ding Dong')"
            en: "This function provies the functionallity to send notification messages to Kodi. Example: sh.living.kodi.notify('Door', 'Ding Dong')"

        parameters:
            title:
                type: str
                description:
                    de: 'Überschrift der Mitteilung'
                    en: ''

            message:
                type: str
                description:
                    de: 'Text der Mitteilung'
                    en: ''

            image:
                type: str
                default: None*
                description:
                    de: "Url des anzuzeigenden Bildes (z.B.: 'http://smarthome.local/img/phone.png')"
                    en: ''

            display_time:
                type: int
                default: 10000
                description:
                    de: 'Dauer der Anzeige in msec'
                    en: ''

