# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Auslesen der Web-Seite eines SolarLog mit Firmware <= 2'
        en: 'Read content of Solarlog webpage with firmware <= 2'
    maintainer: bmxp
    tester: nobody                  # Who tests this plugin?
    state: develop                  # change to ready when done with development
    keywords: solarlog photovoltaic solar pv
    documentation: http://smarthomeng.de/user/plugins/solarlog/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1442978-support-thread-f체r-solarlog-plugin-fw-2-x

    version: 1.6.0                  # Plugin version
    sh_minversion: 1.4              # minimum shNG version to use this plugin
    # sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: unknown
    classname: SolarLog             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    host:
        type: ip
        mandatory: True
        description:
            de: 'Hostadresse des SolarLog Ger채tes'
            en: 'Host address of SolarLog device'

    cycle:
        type: int
        default: 300
        description:
            de: 'Zeit zwischen zwei Updatel채ufen. Default ist 300 Sekunden.'
            en: 'Time period between two update cycles. Default is 300 seconds.'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    solarlog:
        type: str
        description:
            de: 'Variablendefinition f체r die Abfrage'
            en: 'variable name for query'

item_structs: NONE

plugin_functions: NONE

logic_parameters: NONE
