# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin um Yamaha RX-V und RX-S Receiver via XML API zu kontrollieren'
        en: 'Plugin to control Yamaha RX-V and RX-S receiver via XML API'
    maintainer: bmxp
    tester: None
    state: ready
    keywords: Yamaha receiver music
    documentation: ''
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/896468-plugin-yamaha

    version: 1.0.3                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: True
    classname: Yamaha              # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml

item_attributes:
    yamaha_host:
        type: ip
        description:
            de: 'Hostname oder IP-Adresse des Yamaha Receivers mit dem kommuniziert werden soll'
            en: 'Hostname or ip of Yamaha receiver to communicate with'

    yamaha_cmd:
        type: str
        description:
            de: 'Kommando das an den Yamaha Receiver gesendet werden soll'
            en: 'Command to send to Yamaha receiver'
        valid_list:
            - 'state'
            - 'power'
            - 'input'
            - 'volume'
            - 'mute'

item_structs: NONE
# Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
# Definition of plugin functions defined by this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

