# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: protocol                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'SNMP Queries'
        en: 'SNMP Queries'
    maintainer: Michael Wenzel
    state: develop                 # change to ready when done with development
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1455436-support-thread-f%C3%BCr-snmp-plugin
    
    version: 1.6.0                 # Plugin version
    sh_minversion: 1.6.0           # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: Snmp                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    cycle:
        type: int
        default: 300
        description:
            de: 'Zeitlicher Abstand in Sekunden zwischen zwei Abfragen'
            en: 'Time in seconds between two queries'
            
    snmp_host:
        type: str
        default: ''
        description:
            de: 'IP-Adresse des abzufragenden Gerätes'
            en: 'ip adress pf device to be queried'

    snmp_port:
        type: num
        default: 161
        description:
            de: 'Port für SNMP Abfrage'
            en: 'port for snmp queries'
            
    snmp_community:
        type: str
        default: ''
        description:
            de: 'Community für SNMP Abfrage'
            en: 'commnity for snmp queries'

item_attributes:
    # Definition of item attributes defined by this plugin
    snmp_oid:
        type: str
        description:
            de: 'Definiert den OID Code, mit dem das Geräte angefragt werden soll'
            en: 'This assigns the OID code to the item, which will be used to query the device.'
    snmp_prop:
        type: str
        description:
            de: 'Definiert, wie das Plugin die Geräteantwort verarbeiten soll (value oder string'
            en: 'This tells the plugin, how the response from the device should be handled. (value or string)'

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

plugin_functions: NONE
# Definition of plugin functions defined by this plugin
