# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'SNMP'
        en: ''
    maintainer: tbd
    state: develop                 # change to ready when done with development

    version: 1.6.0                 # Plugin version
    sh_minversion: 1.4.2           # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: Snmp                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    cycle:
        type: int
        default: 300
        description:
            de: 'Zeitlicher Abstand in Sekunden zwischen zwei Abfragen'
            en: 'Time in seconds between two queries'
            
    snmp_host:
        type: str
        default: ''
        description:
            de: 'IP-Adresse des abzufragenden Gerätes'
            en: ''

    snmp_port:
        type: num
        default: 161
        description:
            de: 'Port für SNMP Abfrage'
            en: ''
            
    snmp_community:
        type: str
        default: ''
        description:
            de: 'Community für SNMP Abfrage'
            en: ''

item_attributes:
    # Definition of item attributes defined by this plugin
    snmp_oid:
        type: str
        description:
            de: 'OID des Elements'
            en: ''
    snmp_prop:
        type: str
        description:
            de: 'Eigenschaft des Elements'
            en: ''

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

plugin_functions: NONE
# Definition of plugin functions defined by this plugin
