# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Erlaubt das Senden von Notifications an Plex Clients (wie RasPlex)'
        en: 'Send notifications to Plex clients'
    maintainer: rthill
    tester: '?'                    # Who tests this plugin?
    state: ready
    keywords: mediacenter
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: Plex                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    displaytime:
        type: int
        default: 6000
        description:
            de: "Anzeigedauer in Millisekunden"
            en: "Displaytime in milli-seconds"


item_attributes:
    # Definition of item attributes defined by this plugin
    plex_host:
        type: str
        description:
            de: "Hostname oder IP Adresse des Plax Hosts"
            en: "Hostname or IP address of the Plex host"

    plex_port:
        type: int
        default: 3005
        valid_min: 0
        valix_max: 65535
        description:
            de: "Port Nummer auf dem Plex Host"
            en: "port number on the plex hosts"

item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions:
# Definition of plugin functions defined by this plugin
    notify:
        type: void
        description:
            de: "Nachrichten an Plex senden"
            en: "Send notifications to Plex"
        parameters:
            title:
                type: str
                description:
                    de: "Titel der Nachricht"
                    en: "Title of the message"
            message:
                type: str
                description:
                    de: "Nachrichten-text"
                    en: "Body of the message"
            image:
                type: str
                default: 'info'
                valid_list:
                  - 'info'
                  - 'warning'
                  - 'error'
                description:
                    de: "Name des Biled, welches im Nachrichten Dialgo angezeigt werden soll"
                    en: "Name of the image to display on message dialog"


logic_parameters: NONE
# Definition of logic parameters defined by this plugin

