# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Implementierung seperater Logs'
        en: 'Implementation of additional logs'
    maintainer: '? (JanT112)'
    tester: Sandman60, onkelandy
#    keywords: iot xyz
    state: ready
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page

    version: 1.3.0                 # Plugin version
    sh_minversion: 1.4c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: OperationLog        # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    name:
        type: str
        description:
            de: 'Definiert den Namen des Logs'
            en: 'Defines the name of the log'
    maxlen:
        type: int
        default: 50
        description:
            de: 'Gibt an, wieviele Einträge im Speicher vorgehalten werden'
            en: 'Specifies how many log entries will be kept in memory'
    cache:
        type: bool
        default: True
        description:
            de: 'Aktiviert die Caching-Funktion für das Log (Log bleibt bei Neustart erhalten)'
            en: 'Activates the caching for the log (log will be restored on restarts)'
    logtofile:
        type: bool
        default: True
        description:
            de: 'Aktiviert das Schreiben des Logs in eine Datei'
            en: 'Activates logging to file'
    filepattern:
        type: str
        default: '{year:04}-{month:02}-{day:02}-{name}.log'
        description:
            de: 'Definiert das Namensformat für die Logdateien'
            en: 'Defines the name patter for the log files'
    logger:
        type: str
        default: ''
        description:
            de: 'Logt zusätzlich in den angegebenen Logger (z.B. "plugins.operationlog.logger")'
            en: 'Additionally log to the given logger (e.g. "plugins.operationlog.logger")'

item_attributes:
    # Definition of item attributes defined by this plugin
    olog:
        type: str
        description:
            de: 'Wenn gesetzt, werden Item-Änderungen in das angegebene Log geloggt'
            en: 'When set, item changes will be logged to the given log'
    olog_txt:
        type: str
        description:
            de: 'Gibt den Text an, der bei Änderungen geloggt werden soll'
            en: 'Specifies the text to log on changes'
    olog_level:
        type: str
        valid_list:
          - DEBUG
          - INFO
          - WARNING
          - ERROR
        description:
            de: 'Gibt den Log-Level an (DEBUG, INFO, WARNING, ERROR)'
            en: 'Specifies the log level (DEBUG, INFO, WARNING, ERROR)'
    olog_rules:
        type: str
        description:
            de: 'Definiert bestimmte Regel/Mappings für das Logging'
            en: 'Declares specific rules/mappings for the logging'

logic_parameters:
    # Definition of logic parameters defined by this plugin
    olog:
        type: str
        description:
            de: 'Wenn gesetzt, werden Item-Änderungen in das angegebene Log geloggt'
            en: 'When set, item changes will be logged to the given log'
    olog_txt:
        type: str
        description:
            de: 'Gibt den Text an, der bei Änderungen geloggt werden soll'
            en: 'Specifies the text to log on changes'
    olog_level:
        type: str
        valid_list:
          - DEBUG
          - INFO
          - WARNING
          - ERROR
        description:
            de: 'Gibt den Log-Level an (DEBUG, INFO, WARNING, ERROR)'
            en: 'Specifies the log level (DEBUG, INFO, WARNING, ERROR)'

plugin_functions: NONE
    # Definition of function interface of the plugin

