# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                     # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Ansteuerung von SmartHomeNG via Amazon Echo / Alexa, **seit SmartHomeNG v1.3**'
        en: ''
    maintainer: hotzen
    tester: psilo909
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1021150-amazon-alexa-plugin

    version: 1.3.0.9.0             # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: Alexa               # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    service_host:
        type: ip
        description:
            de: 'IP Adresse des service Hosts'
            en: 'ip address of the service host'

    service_port:
        type: int
        default: 9000
        valid_min: 0
        description:
            de: 'Port Nummer des service Hosts'
            en: 'port number of the service host'

item_attributes:
    # Definition of item attributes defined by this plugin

plugin_functions: NONE
# Definition of plugin functions defined by this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

