# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ansteuerung einer Siemens LOGO PLC'
        en: 'Control a Siemens LOGO PLC'
    maintainer: '?'
    tester: '?'                    # Who tests this plugin?
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.2.3                 # Plugin version
    sh_minversion: 1.2             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: LOGO                # class containing the plugin

parameters:
# Definition of parameters to be configured in etc/plugin.yaml

    io_wait:
        type: int
        default: 5
        valid_min: 1
        valid_max: 600
        description:
            de: 'Zeit zwischen zwei read requests'
            en: 'timeperiod between two read requests'

    host:
        type: str
        default: '192.168.0.76'
        description:
            de: 'Adresse der Siemens LOGO'
            en: 'Address of the Siemens LOGO'

    port:
        type: int
        default: 102
        valid_min: 0
        valid_max: 65535
        description:
            de: 'Von Siemens LOGO benutzter Port'
            en: 'Port used Siemens LOGO'

    version:
        type: str
        default: '0BA7'
        valid_list:
          - '0BA7'
          - '0BA8'
        description:
            de: 'Siemens Hardware Version'
            en: 'Hardware version of the Siemens LOGO'

item_attributes:
    # Definition of item attributes defined by this plugin

    logo_read:
        type: str
        description:
            de: "Lesebefehl für die Siemens LOGO PLC"
            en: "Read command for the Siemens LOGO PLC"
    logo_write:
        type: str
        description:
            de: "Schreibbefehl für die Siemens LOGO PLC"
            en: "Write command for the Siemens LOGO PLC"


item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions: NONE
# Definition of plugin functions defined by this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

