# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Steuerung von Amazon Echo Geräten Zugriff via Web-Browser API und Cookie'
        en: 'Plugin to remote control Echo Show/Spot/Fire'
    maintainer: AndreK
    tester: henfri, juergen, psilo
    documentation: https://www.smarthomeng.de/user/plugins/alexarc4shng/user_doc.html       # url of documentation
    version: 1.0.3                              # Plugin version
    sh_minversion: 1.5.2                        # minimum shNG version to use this plugin
    multi_instance: False                       # plugin supports multi instance
    classname: AlexaRc4shNG                     # class containing the plugin
    keywords: Alexa Amazon Remote Control
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1336416-alexa-text-to-speach
    state: develop                   # State of the Plugin
    restartable: True                # Plugin is restartable

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    cookiefile:
        type: str
        default: ''
        description:
            de: 'Cookiefile mit komplettem Pfad'
            en: 'Cookiefile with complete path'
    host:
        type: str
        default: 'alexa.amazon.de'
        description:
            de: 'Amazon-Host z.b. alexa.amazon.de ohne Protokoll (https)'
            en: 'Amazon-Host a.e. alexa.amazon.de without protocoll (https)'

    item_2_enable_alexa_rc:
        type: str
        default: ''
        description:
            de: 'Ein Item welches verwendet wird um die Freigabe für die Kommunikation zu erteilen (USZU)'
            en: 'An Item to give the plugin permission to remote control the echo-devices (USZU)'

    alexa_credentials:
        type: str
        default: ''
        description:
            de: 'Zugangsdaten für das Amazon-Alexa-Web-Site <USER>:<PWD>, base64 encodiert'
            en: 'credentials for the amazon-alexa-website <USER>:<PWD>, base64 encoded'

    login_update_cycle:
        type: num
        default: 432000
        description:
            de: 'Sekunden bis zum automatischen refreshen des Cookie-files'
            en: 'seconds till the next automatic login to get a new cookie'

    mfa_secret:
        type: str
        default: ''
        description:
            de: 'Das OTP MFA Secret welches auf der Amazon-Login-Seite angegben wird'
            en: 'The OTP MFA Secret from the Amazon Login-Page'

logic_parameters: NONE               # No logic parameters for this plugin
item_structs: NONE                   # no item structure needed
item_attributes: NONE                # no item attributes needed

item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)
    alexa_cmd_:
        type: str
        mandatory: True
        description:
            de: 'String um die Befehle zu definieren (alexa_cmd_01, alexa_cmd_02, ...)'
            en: 'string to define commands (alexa_cmd_01, alexa_cmd_02, ...)'

plugin_functions:
    # Definition of function interface of the plugin

    send_cmd:
        type: str
        description:
            de: "Sendet einen Befehl an Alexa."
            en: "Sends a command to Alexa."
        parameters:
            dvName:
                type: str
                description:
                    de: "Name des Alexa Devices."
                    en: "Name of Alexa device."
            cmdName:
                type: str
                description:
                    de: "Name des Befehls, z.b. Text2Speech."
                    en: "Name of command, e.g. Text2Speech."
            mValue:
                type: str
                description:
                    de: "Wert, der gesendet werden soll, numerische Werte ohne Hochkomma als Zahl"
                    en: "Value to send, numeric Values without Quotes as Num"

    get_list:
        type: str
        description:
            de: "Liefert die Alexa-Shopping-Liste als dict-zurück"
            en: "gives back a dict with the Alexa-Shopping-List"
        parameters:
            type:
                type: str
                description:
                    de: "Art der Liste 'SHOPPING_LIST' oder 'TO_DO'"
                    en: "type of the List 'SHOPPING_LIST' or 'TO_DO'"
                valid_list:
                    - 'SHOPPING_LIST'
                    - 'TO_DO'


            
    get_last_alexa:
        type: str
        description:
            de: "Liefert die Geräte-ID des zuletzt verwendeten Alexa-Gerätes zurück"
            en: "delivers the Device-ID of the last used Alexa-Device"

