# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: "Anbindung von Waterkotte Wärmepumpen der EcoTouch-Reihe mittels Netzwerk"

        en: "Connection of Waterkotte heat pumps of the EcoTouch series via network"

    maintainer: tkastner
    tester: blobo
    state: develop                  # change to ready when done with development
#    keywords:
#    documentation:
#    support:

    version: 1.0.0                 # Plugin version
    sh_minversion: '1.3'             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: unknown
    classname: Waterkotte              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

#def __init__(self, sh, ip, user="waterkotte", passwd="waterkotte",cycle=300 ):

    ip:
        type: ip
        mandatory: True
        description:
            de: "IP Adresse der Wärmepumpe"
            en: "IP address of heat pump"

    user:
        type: str
        default: waterkotte
        description:
            de: "Benutzername"
            en: "User name"

    passwd:
        type: str
        default: waterkotte
        description:
            de: "Passwort"
            en: "Password"

    cycle:
        type: int
        default: 300
        description:
            de: "Zykluszeit"
            en: "Cycle time"


item_attributes:
    # Definition of item attributes defined by this plugin

    waterkotte:
        type: str
        valid_list:
        - temp_aussen
        - temp_aussen_1h
        - temp_aussen_24h
        - temp_quelle_ein
        - temp_quelle_aus
        - temp_verdampfung
        - temp_sauggas
        - druck_verdampfung
        - temp_soll
        - temp_ruecklauf
        - temp_vorlauf
        - temp_kondensation
        - druck_kondensation
        - temp_speicher
        - temp_raum
        - temp_raum_1h
        - temp_ww
        - temp_sk
        - pow_comp
        - pow_therm
        - pow_cool
        - cop_comp
        - cop_cool
        - temp_hk
        - temp_gefordert_hk
        - temp_gefordert_ww
        - temp_soll_ww
        - rpm_hk
        - rpm_sole
        - valve_exp
        - jaz_wp
        - oh1_verdichter
        - oh2_verdichter
        - oh1_heizstab
        - oh2_heizstab
        - oh1_heizpumpe
        - oh2_heizpumpe
        - oh1_solepumpe
        - oh2_solepumpe
        - cop_jan
        - cop_feb
        - cop_mar
        - cop_apr
        - cop_may
        - cop_jun
        - cop_jul
        - cop_aug
        - cop_sep
        - cop_oct
        - cop_nov
        - cop_dec
        - f121

        valid_list_description:
            de:
              - 'Außentemperatur aktuell'
              - 'Außentemperatur Mittelwert 1h'
              - 'Außentemperatur Mittelwert 24h'
              - 'Temperatur Quelle Eingang'
              - 'Temperatur Quelle Ausgang'
              - 'Temperatur Verdampfung'
              - 'Temperatur Sauggas'
              - 'Druck Verdampfung'
              - 'Temperatur Soll ?'
              - 'Temperatur Rücklauf'
              - 'Temperatur Vorlauf'
              - 'Temperatur Kondensation'
              - 'Druck Kondensation'
              - 'Temperatur Speicher ?'
              - 'Raumtemperatur'
              - 'Raumtemperatur Mittelwert 1h'
              - 'Temperatur Warmwasser'
              - 'Temperatur Pool'
              - 'Leistung Kompressor'
              - 'Leistung thermisch gesamt'
              - 'Leistung Kälte'
              - 'Aktueller COP'
              - 'COP Kühlung ?'
              - 'Temperatur Heizkreis'
              - 'Temperatur gefordert Heizkreis'
              - 'Temperatur gefordert Warmwasser'
              - 'Temperatur Soll Warmwasser'
              - 'Drehzahl % Heizkreispumpe'
              - 'Drehzahl % Quellenpumpe'
              - 'Expansionsventil Öffnung %'
              - 'Jahresarbeitszahl Wärmepumpe'
              - 'Betriebsstunden Verdichter 31..16'
              - 'Betriebsstunden Verdichter 15..0'
              - 'Betriebsstunden Heizstab 31..16'
              - 'Betriebsstunden Heizstab 15..0'
              - 'Betriebsstunden Heizkreispumpe 31..16'
              - 'Betriebsstunden Heizkreispumpe 15..0'
              - 'Betriebsstunden Quellenpumpe 31..16'
              - 'Betriebsstunden Quellenpumpe 15..0'
              - 'COP Januar'
              - 'COP Februar'
              - 'COP März'
              - 'COP April'
              - 'COP Mai'
              - 'COP Juni'
              - 'COP Juli'
              - 'COP August'
              - 'COP September'
              - 'COP Oktober'
              - 'COP November'
              - 'COP Dezember'
              - 'Fehler F121'


            en:
              - 'Outside temperature current'
              - 'Outside temperature average 1h'
              - 'Outside temperature average 24h'
              - 'Temperature source in'
              - 'Temperature source out'
              - 'Temperature evaporation'
              - 'Temperature suction gas'
              - 'Pressure evaporation'
              - 'Temperature setpoint ?'
              - 'Temperature return'
              - 'Temperature flow'
              - 'Temperature condensation'
              - 'Pressure condensation'
              - 'Temperature boiler ?'
              - 'Room temperature'
              - 'Room temperature average 1h'
              - 'Temperature hot water'
              - 'Temperature pool'
              - 'Power compressor'
              - 'Power thermal total'
              - 'Power refrigeration'
              - 'Current COP'
              - 'COP refrigeration ?'
              - 'Temperature heating'
              - 'Temperature requested heating'
              - 'Temperature requested hot water'
              - 'Temperature setpoint hot water'
              - 'RPM % heating pump'
              - 'RPM % source pump'
              - 'Expansion valve opening %'
              - 'Seasonal performance factor heat pump'
              - 'Operating hours compressor 31..16'
              - 'Operating hours compressor 15..0'
              - 'Operating hours electrical heater 31..16'
              - 'Operating hours electrical heater 15..0'
              - 'Operating hours heating pump 31..16'
              - 'Operating hours heating pump 15..0'
              - 'Operating hours source pump 31..16'
              - 'Operating hours source pump 15..0'
              - 'COP January'
              - 'COP February'
              - 'COP March'
              - 'COP April'
              - 'COP May'
              - 'COP June'
              - 'COP July'
              - 'COP August'
              - 'COP September'
              - 'COP October'
              - 'COP November'
              - 'COP December'
              - 'Error F121'

        description:
            de: "Derzeit implementierte Tags und deren Bedeutung"
            en: "Currently implemented tags and their meaning"

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin


