# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: protocol                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'MQTT Plugin, welches das MQTT Module von SmartHomeNG zur Kommunikation nutzt.'
        en: 'MQTT plugin which utilizes the MQTT module of SmartHomeNG for communication'
    maintainer: msinn
#    tester:                         # Who tests this plugin?
    state: ready                   # change to ready when done with development
    keywords: iot
#    documentation: http://smarthomeng.de/user/plugins/mqtt2/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1089334-neues-mqtt-plugin

    version: 2.0.1                 # Plugin version
    sh_minversion: 1.6a            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: Mqtt2               # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    mqtt_topic:
        type: str
        description:
            de: 'Topic für Senden und Empfangen'
            en: 'Topic for send and receive'
        description_long:
            de: 'Wenn mqtt_topic konfiguriert ist, wird das Topic für ein- und ausgehende Messages
                 verwendet. Dabei werden evtl. konfigurierte seperate Werte für mqtt_topic_out und
                 mqtt_topic_in überschrieben.
                '
            en: 'If you specify mqtt_topic, it set this topic for in- and outgoing messages.
                 Thus it overwrites seperate values you might have specified for mqtt_topic_out
                 or mqtt_topic_in.
                '

    mqtt_topic_in:
        type: str
        description:
            de: 'Topic für Empfangen'
            en: 'Topic for receive'
        description_long:
            de: 'mqtt_topic_in definiert das MQTT Topic, welches abonniert wird. Bei Empfang
                 einer Message mit diesem Topic, wird die Payload benutzt um den Wert des Items
                 zu setzen.
                '
            en: "mqtt_topic_in defines the MQTT topic to subscribe to. Upon receiving a message
                 with this topic, the payload is used to set the item's value.
                "

    mqtt_topic_out:
        type: str
        description:
            de: 'Topic für Senden'
            en: 'Topic for send'
        description_long:
            de: 'mqtt_topic_out definiert das MQTT Topic unter dem der Wert des Items als
                 Payload publiziert wird.
                '
            en: 'mqtt_topic_out defines the MQTT topic under which the items value is to be
                 published as payload.
                '

    mqtt_topic_init:
        type: str
        description:
            de: 'Topic für Senden (Initial beim Start von SmartHomeNG senden)'
            en: 'Topic for send (send initially when starting up SmartHomeNG'
        description_long:
            de: 'mqtt_topic_init ist äquivalent zu mqtt_topic_out, außer dass das Topic beim
                 Start von SmartHomeNG initialisiert (also eine MQTT message gesendet) wird.
                '
            en: 'mqtt_topic_init is equivalent to mqtt_topic_out, except it initializes the
                 topic when SmartHomeNG ist started.
                '

    mqtt_qos:
        type: int
        valid_list:
          - 0
          - 1
          - 2
        description:
            de: 'Quality of Service'
            en: 'Quality of Service'
        description_long:
            de: 'mqtt_qos definert den Quality of Service Level, der für dieses Item bei der
                 Kommunikation mit dem Broker genutzt wird. Falls nicht angegeben, wird das
                 globale Setting des Plugins genutzt.
                '
            en: "mqtt_qos defines the quality of service level for this item used when communicating
                 with the broker. If not specified, the plugin's default is used.
                "

    mqtt_retain:
        type: bool
        default: ''
        description:
            de: 'Retention Flag für gesendete Telegramme setzen'
            en: 'Set retention flag for sent telegrams'
        description_long:
            de: 'Wenn mqtt_retain auf True gesetzt ist, werden MQTT Messages für dieses Item mit
                 gesetztem Reatin Flag gesendet.\n
                '
            en: 'When set to True, the MQTT message is sent with the retain flag set.\n
                '

    mqtt_bool_values:
        type: list
        default: None*
        description:
            de: "Gewünschte Werte (im MQTT Payload) für boolsche Items (z.B. ['Falsch','Wahr'])"
            en: "Values (in MQTT payload) for boolean items (e.g. ['Wrong','Right'])"

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

