# Metadata for the JSONread-Plugin
plugin:
    # Global plugin attributes
    type: web               # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'json Parser Plugin basierend auf jq'
        en: 'json parser plugin based on jq'
    maintainer: Torsten Dreyer
    tester: none (yet)
    state: develop
    keywords: json jq
    documentation: http://smarthomeng.de/user/plugins_doc/config/not-yet.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/not-yet

    version: 1.0.2                 # Plugin version
    sh_minversion: 1.4             # minimum shNG version to use this plugin
    #sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    #py_minversion: 3.6            # minimum Python version to use for this plugin
    py_maxversion: 3.9             # maximum Python version to use for this plugin (leave empty if latest)
    py_versioncomment: "Die aktuellste Version (2.5.2, released Mai 2021) des benötigten Packages 'pyjq' ist nicht kompatibel mit Python 3.10"
    restartable: True
    multi_instance: True           # plugin supports multi instance
    classname: JSONREAD            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    url:
        type: str
        mandatory: True
        description:
            de: >
                URL der JSON Datenquelle. Aktuell unterstützt werden Webprotokolle https:// und http:// sowie ein Dateiadapter file:/// (benötigt wirklich 3 Schrägstriche)
            en: >
                URL of the JSON source. Currently supported are web protocols https:// and http:// as well as file adapter file:/// (which needs indeed 3 slashes)
    cycle:
        type: int
        default: 30
        valid_min: 0
        description:
            de: 'Das Abfrage-Intervall für die gegebene Datenquelle in Sekunden'
            en: 'The polling interval for the given data source in seconds'


item_attributes:
    # Definition of item attributes defined by this plugin
    jsonread_filter:
        type: str
        description:
            de: 'JQ Pfad um innerhalb eines JSON Datensatzes einen Wert auszuwählen. Dieser Wert wird dem Item dann zugewiesen'
            en: 'JQ path to select a value from JSON dataset. The Item will then receive this value'

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of function interface of the plugin

