# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: gateway                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ansteuerung der meisten USB/Netwerk DMX Adapter'
        en: 'Can control most of USB/network DMX adapters'
    maintainer: mode2k
    tester: ohinckel
    state: qa-passed
    keywords: dmx
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page

    version: 1.3.0                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False
    restartable: unknown
    classname: ArtNet               # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    artnet_net:
        type: int
        default: 0
        description:
            de: 'Gibt das ArtNet Net an'
            en: 'Specifies the ArtNet Net to use'
        valid_min: 0
        valid_max: 127
    artnet_subnet:
        type: int
        default: 0
        description:
            de: 'Gibt das Art-Net Sub-Net an'
            en: 'Specifies the Art-Net Sub-Net to use'
        valid_min: 0
        valid_max: 15
    artnet_universe:
        type: int
        default: 0
        description:
            de: 'Gibt das Art-Net Universe an'
            en: 'Specifies the Art-Net Universe to use'
        valid_min: 0
        valid_max: 15
    ip:
        type: ip
        description:
            de: 'Gibt die Adresse einer Art-Net Node an'
            en: 'Specifies the address of a Art-Net node'
    port:
        type: int
        valid_min: 0
        description:
            de: 'Gibt den Port einer Art-Net Node an'
            en: 'Specifies the port of a Art-Net node'
    
item_attributes: NONE
    # Definition of item attributes defined by this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

