# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: gateway                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ansteuerung der meisten USB/Netwerk DMX Adapter'
        en: 'Can control most of USB/network DMX adapters'
    maintainer: mode2k, jentz1986
    tester: ohinckel
    state: ready
    keywords: dmx
#   documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page

    version: 1.5.1                 # Plugin version
    sh_minversion: 1.5.1           # minimum shNG version to use this plugin
#   sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True
    restartable: True              # Plugin can be restarted safely, however, the data is not re-applied from items to the DMX-Values
    classname: ArtNet              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    ip:
        type: ip
        description:
            de: 'Gibt die Adresse des angesprochenen Art-Net Node an'
            en: 'Specifies the address of a Art-Net node'
    port:
        type: int
        valid_min: 0
        description:
            de: 'Gibt den Port des angesprochenen Art-Net Node an'
            en: 'Specifies the port of a Art-Net node'
    update_cycle:
        type: int
        valid_min: 0
        description:
            de: 'Gibt an, wie oft (Sekunden) die aktuelle Lichtsituation neu verschickt werden soll (optional, 0 deaktiviert dies)'
            en: 'Defines Refresh-cycle for re-sending the current setting in seconds, 0 deactivates this'
    artnet_net:
        type: int
        default: 0
        description:
            de: 'Gibt das ArtNet Net an'
            en: 'Specifies the ArtNet Net to use'
        valid_min: 0
        valid_max: 127
    artnet_subnet:
        type: int
        default: 0
        description:
            de: 'Gibt das Art-Net Sub-Net an'
            en: 'Specifies the Art-Net Sub-Net to use'
        valid_min: 0
        valid_max: 15 
    artnet_universe:
        type: int
        default: 0
        description:
            de: 'Gibt das Art-Net Universe an'
            en: 'Specifies the Art-Net Universe to use'
        valid_min: 0
        valid_max: 15


item_attributes:
    artnet_address:
        type: int
        mandatory: True
        valid_min: 1
        valid_max: 255
        description:
            de: 'Definition der DMX Adresse'
            en: 'Defition of DMX address'

logic_parameters: NONE

plugin_functions: 
    send_single_value:
        type: void
        description:
            de: "Sendet einen einzelnen DMX Kanalwert"
            en: "Sends a single DMX Channel-Value"
        parameters:
            adr:
                type: num
                valid_min: 1
                valid_max: 512
                description:
                    de: "Zu adressierender DMX-Kanal"
                    en: "DMX Channel to be addressed"
            value:
                type: num
                valid_min: 0
                valid_max: 255
                description:
                    de: "Wert auf den der Kanal gesetzt werden soll"
                    en: "Value this Channel is to be set to"
    send_frame_starting_at:
        type: void
        description:
            de: "Sendet einen Satz an DMX Kanalwerten, beginnend bei einer Startadresse"
            en: "Sends a set of DMX-channel-value starting from a certain address"
        parameters:
            adr:
                type: num
                valid_min: 1
                valid_max: 512
                description:
                    de: "Erster zu adressierender DMX-Kanal"
                    en: "First DMX-channel to be addressed"
            values:
                type: list(num)
                description:
                    de: "Werte die ab dem Startkanal gesetzt werden sollen"
                    en: "Values to be transferred"
    send_frame:
        type: void
        description:
            de: "Sendet einen vollständingen DMX-Frame"
            en: "Sends a full DMX-Frame"
        parameters:
            values:
                type: list(num)
                description:
                    de: "Wertemenge"
                    en: "Values to be transferred"

item_structs: NONE
