# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Slack messaging Dienst'
        en: 'Slack messaging service'
    maintainer: rthill
    tester: maddinador
    state: develop
    keywords: messaging
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                # Plugin version
    sh_minversion: 1.4            # minimum shNG version to use this plugin
#    sh_maxversion:               # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True          # plugin supports multi instance
    restartable: True             # restartable: yes
    classname: Slack              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    token:
        type: str
        description:
            de: 'Slack-Token für den API-Zugriff auf einen oder mehrere Kanäle in einem Slack-Workspace'
            en: 'Slack token for API access to one or more channels in a single Slack workspace'
        mandatory: True

    instance:
        type: str
        default: ''
        description:
            de: 'Eindeutiger Identifier für die Instanz des Plugins. Kann bei nur einer konfigurierten Instanz des Plugins entfallen.'
            en: 'Unique identifier for each instance of the plugin. Can be omitted if only one device instance of the plugin is configured.'


item_attributes: NONE
    # Definition of item attributes defined by this plugin

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of public functions defined by this plugin
        notify:
            type: foo
            description:
                de: 'Absetzen einer Messaging-Nachricht an den Slack Workspace'
                en: 'send a messaging text to Slack workspace'
            parameters:
                channel:
                    type: str
                    description:
                        de: 'Slack-Kanal, in den gepostet wird'
                        en: 'Slack channel to be posted to'
                    mandatory: True
                text:
                    type: str
                    description:
                        de: 'Text der Nachricht'
                        en: 'text of your message'
                    mandatory: True
                color:
                    type: str
                    description:
                        de: 'Typ der Nachricht (=Farbe)'
                        en: 'type of message (=color)'
                    mandatory: False
                    default: 'normal'
                    valid_list:
                        - 'normal'
                        - 'good'
                        - 'warning'
                        - 'danger'

