# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Sendet Kommandos an lircd, das wiederum IR-Signale an Geräte mit IR-Schnittstelle versendet'
        en: 'Sends commands to lircd that sends IR-signals to any device that has an IR-interface'
    requirements:
        de: 'laufendes lirc Service'
        en: 'running lirc service'
    requirements_long:
        de: 'Zumindest ein laufender lirc Service mit einem IR-Transmitter, optional ein IR-Receiver (um Remotecodes zu lernen
             oder Befehel via IR zu empfangen), und eine Konfigurationsdatei für die zu simulierende Fernbedienung.\n
             Diese Datei kann durch Einlesen mittels irrecord oder Herunterladen einer passenden Datei aus entsprechenden
             Datenbanken erstellt werden.\n
             Weitere Informationen sind unter http://www.lirc.org/html/lircd.html und http://lirc-remotes.sourceforge.net/
             zu finden.
             '
        en: 'At least a running and listening lircd with an IR-transmitter, optional an IR-receiver (for learning remotes
             or receiving commands from via IR), and the remote configuration file of your remote control. \n
             You can create this file by learning your remote with irrecord or use an existing file from the remotes database.\n
             For more information about lircd and the remotes database see http://www.lirc.org/html/lircd.html and http://lirc-remotes.sourceforge.net/
            '
    maintainer: E3EAT, onkelandy
    tester: onkelandy
    keywords: infrared, lirc, remote
    state: ready
    restartable: True
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1149875-neues-plugin-lirc

    version: 1.5.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    classname: LIRC                # class containing the plugin


parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    host:
        type: str
        mandatory: True
        description:
            de: 'IP oder Hostname des lircd'
            en: 'IP or hostname of the lircd'

    port:
        type: int
        default: 8765
        description:
            de: 'Der Port, auf dem lircd lauscht.'
            en: 'The port that is used by lircd.'

    lirc_host:
        type: str
        description:
            de: 'Veraltet - bitte "host" nutzen'
            en: 'Deprecated - please use "host"'

    lirc_port:
        type: int
        default: 8765
        description:
            de: 'Veraltet - bitte "port" nutzen'
            en: 'Deprecated - please use "port"'

    autoreconnect:
        type: bool
        default: False
        description:
            de: 'Erneuter Verbindungsaufbau, falls Verbindung unterbrochen'
            en: 'Reconnect if connection is broken'

    connect_retries:
        type: int
        default: 2
        valid_min: 0
        description:
            de: 'Anzahl Versuche, die Verbindung erneut aufzubauen'
            en: 'Number of retries to reconnect'

    connect_cycle:
        type: int
        default: 10
        valid_min: 0
        valid_max: 1000
        description:
            de: 'Pause zwischen automatischen Verbindungsversuchen.'
            en: 'Pause between automatic connection retries'

item_attributes:
    # Definition of item attributes defined by this plugin
    lirc_remote:
        type: str
        description:
            de: 'Name der Fernbedienung. Der Name muss dem Namen der Fernbedienung in lircd entsprechen.'
            en: 'The name of the remote. This name has to match the name of the remote in lircd.'

    lirc_key:
        type: str
        description:
            de: 'Name der Taste auf der Fernbedienung. Der Name muss dem Namen der Fernbedienung in lircd entsprechen.'
            en: 'The name of the key on the given remote. This name has to match the name of the key in lircd. '

item_structs: NONE

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

plugin_functions: NONE
# Definition of plugin functions defined by this plugin
