# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Unterstützung für smartUPS Geräte der Firma APC'
        en: 'Support for smartUPS devices sold by APC'
    maintainer: cmalo
    tester: Sandman60
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.3.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: APCUPS              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    host:
        type: ipv4
        default: '127.0.0.1'
        description:
            de: 'IP Adresse bzw. Hostname der UPS'
            en: 'ip address or hostname of the ups'

    port:
        type: int
        default: 3551
        valid_min: 0
        description:
            de: 'Port Nummer der UPS'
            en: 'port number of the ups'

    cycle:
        type: int
        valid_min: 0
        description:
            de: 'Zyklus-Zeit zum Update der Items mit Werten von APCaccess'
            en: time to update the items with values from apcaccess

    instance:
        type: str
        default: ''
        description:
            de: 'Eindeutiger Identifier für die Instanz des Plugins. Kann bei nur einer konfigurierten Instanz des Plugins entfallen.'
            en: 'Unique identifier for each instance of the plugin. Can be omitted if only one device instance of the plugin is configured.'


item_attributes:
    # Definition of item attributes defined by this plugin
    apcups:
        type: str
        description:
            de: 'Für eine Liste gültiger Werte, "apcaccess" auf der Kommandozeile aufrufen. Dieser Befehl gibt einen Textblock zurück, der eine Liste von ``statusname : value`` Einträgen enthält'
            en: 'For a list of values for this attribute call "apcaccess" on the command line. This command will give back a text block containing a list of ``statusname : value`` entries'

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

