# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Steuerung von Buderus Heizkesseln über ein Logamatic web KM200 Modul (noch in der Entwicklung), **seit SmartHomeNG v1.3**'
        en: 'Control Buderus heating through a Logamatic web KM200 module (still under development)'
    maintainer: rthill
#    tester:                        # Who tests this plugin?
    state: develop
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: Buderus             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    host:
        type: ip
        default: False
        description:
            de: "IP Adresse"
            en: "IP address"

    key:
        type: ip
        default: False
        description:
            de: "key - zu erzeugen auf https://ssl-account.com/km200.andreashah"
            en: "key - generated from https://ssl-account.com/km200.andreashah"

    cycle:
        type: int
        default: 900
        description:
            de: "Zykluszeit (in Sekunden)"
            en: "Cycle time (in seconds)"


item_attributes:
    # Definition of item attributes defined by this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

