# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Steuerung von Buderus Heizkesseln über ein Logamatic web KM200 Modul (noch in der Entwicklung), **seit SmartHomeNG v1.3**'
        fr: "Contrôle d'un chauffage Buderus via un module Logamatic web KM200 (en développement)"
        en: 'Control Buderus heating through a Logamatic web KM200 module (still under development)'
    maintainer: sebastianfaulhaber, rthill
    tester: '?'                    # Who tests this plugin?
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.2                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
    #sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    restartable: True
    multi_instance: False          # plugin supports multi instance
    classname: Buderus             # class containing the plugin


parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    host:
        type: ip
        mandatory: True
        description:
            de: "IP Adresse"
            fr: "Adresse IP"
            en: "IP address"

    key:
        type: str
        mandatory: True
        description:
            de: "key - zu erzeugen auf https://ssl-account.com/km200.andreashahn.info/"
            fr: "clé - a générer sur https://ssl-account.com/km200.andreashahn.info/"
            en: "key - generated from https://ssl-account.com/km200.andreashahn.info/"

    cycle:
        type: int
        default: 900
        description:
            de: "Zykluszeit (in Sekunden)"
            fr: "Temps d'un cycle (en secondes)"
            en: "Cycle time (in seconds)"


item_attributes:
    km_id:
        type: str
        description:
            de: 'Pfad zum Datenpunkt des Buderus Gerätes. Siehe /URLs.md für eine Liste der möglichen Werte.'
            en: 'Path of the datapoint within Buderus device. See /URLs.md for a complete list of values.'

item_structs:

  gateway:
    uuid:
        type: str
        visu_acl: ro
        km_id: /gateway/uuid
    datetime:
        type: str
        visu_acl: ro
        km_id: /gateway/DateTime
    firmware:
        type: str
        visu_acl: ro
        km_id: /gateway/versionFirmware
    hardware:
        type: str
        visu_acl: ro
        km_id: /gateway/versionHardware

  heating_system:
    brand:
        type: str
        visu_acl: ro
        km_id: /system/brand
    type:
        type: str
        visu_acl: ro
        km_id: /system/systemType
    bus:
        type: str
        visu_acl: ro
        km_id: /system/bus
    health:
        type: str
        visu_acl: ro
        km_id: /system/healthStatus
#    info:
#        type: dict
#        km_id: /system/info
    actualSupplyTemperature:
        type: num
        visu_acl: ro
        km_id: /system/appliance/actualSupplyTemperature
    powerSetpoint:
        type: num
        visu_acl: ro
        km_id: /system/appliance/powerSetpoint
    actualPower:
        type: num
        visu_acl: ro
        km_id: /system/appliance/actualPower
    pumpModulation:
        type: num
        visu_acl: ro
        km_id: /system/appliance/CHpumpModulation
    numberOfStarts:
        type: num
        visu_acl: ro
        km_id: /system/appliance/numberOfStarts
    gasAirPressure:
        type: num
        visu_acl: ro
        km_id: /system/appliance/gasAirPressure
    systemPressure:
        type: num
        visu_acl: ro
        km_id: /system/appliance/systemPressure
    workingTime:
        totalSystem:
            type: num
            visu_acl: ro
            km_id: /system/appliance/workingTime/totalSystem
        secondBurner:
            type: num
            visu_acl: ro
            km_id: /system/appliance/workingTime/secondBurner
        centralHeating:
            type: num
            visu_acl: ro
            km_id: /system/appliance/workingTime/centralHeating
    nominalBurnerLoad:
        type: num
        visu_acl: ro
        km_id: /system/appliance/nominalBurnerLoad
    sensors:
        outside:
            type: num
            visu_acl: ro
            km_id: /system/sensors/temperatures/outdoor_t1
        supply:
            type: num
            visu_acl: ro
            km_id: /system/sensors/temperatures/supply_t1
        return:
            type: num
            visu_acl: ro
            km_id: /system/sensors/temperatures/return
        hotwater:
            type: num
            visu_acl: ro
            km_id: /system/sensors/temperatures/hotWater_t2
        chimney:
            type: num
            visu_acl: ro
            km_id: /system/sensors/temperatures/chimney
        boiler_flame:
            type: str
            visu_acl: ro
            km_id: /heatSources/flameStatus

  heating_circuit_01:
    room_set:
        type: num
        km_id: /heatingCircuits/hc1/currentRoomSetpoint
    manual_set:
        type: num
        km_id: /heatingCircuits/hc1/manualRoomSetpoint
    active_program:
        type: str
        km_id: /heatingCircuits/hc1/activeSwitchProgram
    mode:
        type: str
        km_id: /heatingCircuits/hc1/operationMode

  hot_water_circuit_01:
    temp:
        type: num
        km_id: /dhwCircuits/dhw1/actualTemp
    set:
        type: num
        km_id: /dhwCircuits/dhw1/currentSetpoint
    flow:
        type: num
        km_id: /dhwCircuits/dhw1/waterFlow
    time:
        type: num
        km_id: /dhwCircuits/dhw1/workingTime

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

