# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Steuerung von Switches, die mit Tasmota Firmware ausgestattet sind. Die Kommunikation erfolgt über das MQTT Module von SmartHomeNG.'
        en: 'Plugin to control switches which are equipped with Tasmote firmware. Communication is handled through the MQTT module of SmartHomeNG.'
    maintainer: sisamiwe
    tester: msinn                  # Who tests this plugin?
    state: ready                   # change to ready when done with development
    keywords: iot
    documentation: http://smarthomeng.de/user/plugins/tasmota/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1520293-support-thread-für-das-tasmota-plugin

    version: 1.5.2                 # Plugin version
    sh_minversion: '1.9.3'           # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion:                # minimum Python version to use for this plugin
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: Tasmota             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    full_topic:
        type: str
        default: '%prefix%/%topic%/'
        description:
            de: 'Vollständiges Topic (Prefix und Topic) zur Kommunikation mit den Tasmota Devices'
            en: 'Full topic (prefix und topic) for communication with tasmota devices'

    telemetry_period:
        type: int
        default: 300
        valid_min: 10
        valid_max: 3600
        description:
            de: 'Zeitabstand in Sekunden in dem die Tasmota Devices Telemetrie Daten senden sollen'
            en: 'Timeperiod in seconds in which Tasmota devices shall send telemetry data'


item_attributes:
    tasmota_topic:
        type: str
        description:
            de: Topic um mit dem Tasmota Device zu kommunizieren (%topic%)
            en: Topic to be used to communicate with the tasmota device (%topic%)

    tasmota_attr:
        type: str
        default: relay
        description:
            de: "Zu lesendes/schreibendes Attribut des Tasmota Devices. Achtung: Nicht jedes Attribut ist auf allen Device-Typen vorhanden."
            en: "Attribute of Tasmota device that shall be read/written. Note: Not every attribute is available on all device types"

    tasmota_relay:
        type: int
        default: 1
        valid_min: 1
        valid_max: 4
        description:
            de: "Nummer des zu schaltenden Relais im Tasmota Device"
            en: "Number of the relay in Tasmota device to use for switching command"

    tasmota_button:
        type: int
        default: 1
        valid_min: 1
        valid_max: 4
        description:
            de: "Nummer der gedrückten Taste im Tasmota Device"
            en: "Number of Button pressed in Tasmota device"

    tasmota_rf_details:
        type: str
        description:
            de: "Nummer des auszulösenden RF Keys im Tasmota Device und Aktion bei Empfang als String; bspw: '16=true' - Bei Empfang des Key16, setze Item auf True"
            en: "Number of rf keys to be used for sending command"

    tasmota_zb_device:
        type: str
        description:
            de: "Friendly Name oder Kurzname des Zigbee Devices. ACHTUNG: Wird der Kurzname verwendet und beginnt dieser mit 0x, muss die Schreibweise '0x9CB9' verwendet werden"
            en: "Friendly Name oder Short Name of Zigbee Devices"

    tasmota_zb_group:
        type: num
        description:
          de: "Zigbee Control Group: Werte werden an diese Gruppe gesendet. Gruppennachrichten werden nicht empfangen. https://tasmota.github.io/docs/Device-Groups/#zigbee"
          en: "Zigbee Control Group: Values will be sent to group. return messages will not be received"

    tasmota_zb_attr:
        type: str
        description:
            de: "Schlüssel der Json-Dict, der vom Zigbee-Device bereitgestellt wird; Key aus dem dict des tasmota_zb_device"
            en: "Dict Key of provided data; can be seen in Plugin WebIF"

    tasmota_zb_cluster:
      type: bool
      default: False
      description:
        de: "Ergänzung des Sendebefehls um entsprechendes Zigbee-Cluster"
        en: "Use zigbee cluster in send command additionally"

    tasmota_sml_device:
      type: str
      description:
        de: "Name des Smartmeter (SML Device)"
        en: "Name of smartmeter (SML Device)"

    tasmota_sml_attr:
      type: str
      description:
        de: "Smartmeter Attribut; muss dem Key des Dictionary dem SML Devices entsprechen"
        en: "Smartmeter attribute; need to be key of SML device dictionary"

    tasmota_admin:
        type: str
        default: delete_retained_messages
        description:
            de: ""
            en: ""
        valid_list:
            - delete_retained_messages

item_structs: NONE

plugin_functions: NONE

logic_parameters: NONE


