# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ansteuerung von HomeMatic Komponenten über eine HomeMatic CCU2 Zentrale. Es werden HomeMatic und HomeMaticIP Geräte unterstützt.'
        en: 'Control HomeMatic devices through a HomeMatic CCU2 (used as gateway). HomeMatic and HomeMaticIP devices are supported.'
    maintainer: msinn             # Who maintains this plugin?
    tester: msinn
    state: qa-passed
#    tester: efgh                   # Who tests this plugin?
#    keywords: kwd1 kwd2            # keywords, where applicable
    documentation: http://smarthomeng.de/user/plugins/homematic/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1501815-support-thread-zum-homematic-plugin

# Following entries are for Smart-Plugins:
    version: 1.5.2                 # Plugin version
    sh_minversion: '1.7'             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    py_minversion: '3.6'             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: True
    restartable: unknown
    classname: Homematic            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    host:
        type: ip
        default: 'homematic-ccu2.local'
        description:
            de: 'IP Adresse bzw. Hostname der HomeMatic CCU2 Zentrale'
            en: 'ip address or hostname of the HomeMatic CCU2 gateway'

    proxyPort:
       type: int
       default: 0
       valid_min: 0
       description:
           de: 'Port Nummer für eingehende Nachrichten von der HomeMatric CCU2 Zentrale'
           en: 'port number for incoming messages from the HomeMatric CCU2 gateway'

    proxyPort_hmip:
       type: int
       default: 0
       valid_min: 0
       description:
           de: 'Port Nummer für eingehende Nachrichten von der HomeMatric CCU2 Zentrale für HomeMaticIP Geräte'
           en: 'port number for incoming messages from the HomeMatric CCU2 gateway for HomeMaticIP Devices'

    customCallbackHost:
        type: bool
        mandatory: False
        description:
            de: 'Legt fest, ob Callbacks umgeleitet werden soll (z.B. Docker Host), default FALSE'
            en: 'determine if callbacks must be reditected (e.g. Docker Host), default FALSE'

    callbackHost:
        type: ip
        default: '127.0.0.1'
        description:
            de: 'IP Adresse bzw. Hostname, an die die HomeMatric CCU2 Zentrale Nachrichten senden soll (z.B. Docker Host)'
            en: 'ip address or hostname, to which the HomeMatric CCU2 gateway has to send messages (e.g. Docker Host)'

    callbackPort:
       type: int
       default: 30000
       valid_min: 0
       description:
           de: 'Port Nummer, an die die HomeMatric CCU2 Zentrale Nachrichten senden soll (z.B. Docker Host)'
           en: 'port number, to which the HomeMatric CCU2 gateway has to send messages (e.g. Docker Host)'

    callbackPort_hmip:
       type: int
       default: 30001
       valid_min: 0
       description:
           de: 'Port Nummer, an die die HomeMatric CCU2 Zentrale Nachrichten senden soll (z.B. Docker Host) für HomeMaticIP Geräte'
           en: 'port number, to which the HomeMatric CCU2 gateway has to send messages for HomeMaticIP Devices (e.g. Docker Host)'
#    port:
#        type: int
#        default: 2001
#        valid_min: 0
#        description:
#            de: 'Port Nummer der HomeMatic CCU2 Zentrale'
#            en: 'port number of the HomeMatic CCU2 gateway'
#
#    port_hmip:
#        type: int
#        default: 2010
#        valid_min: 0
#        description:
#            de: 'Port Nummer der HomeMatic CCU2 Zentrale für HomeMaticIP Geräte'
#            en: 'port number of the HomeMatic CCU2 gateway for HomeMaticIP Devices'

    username:
        type: str
        default: 'Admin'
        description:
            de: 'Username für das Login'
            en: 'Username for the login'

    password:
        type: str
        default: ''
        hide: True
        description:
            de: 'Passwort für das Login'
            en: 'Password for the login'

    learnmode_length:
        type: int
        default: 60
        valid_min: 0
        valid_max: 300
        description:
            de: 'Dauer des Anlernmodus der HomeMatic CCU2 Zentrale nach Aktivierung durch das Web Interface'
            en: 'Duration of learnmode of the HomeMatic CCU2 gateway after activation through the web interface'


item_attributes:
    # Definition of item attributes defined by this plugin

    hm_address:
        type: str
        description:
            de: 'Adresse des HomeMatic Devices, welches über die HomeMatic CCU2 Zentrale angesteuert werden soll'
            en: 'Adress of the HomeMatic device that shall be controlled (through the HomeMatic CCU2 central unit)'

    hm_function:
        type: str
        description:
            de: 'Name der Funktion des HomeMatic Devices, welche genutzt werden soll'
            en: 'Name of the function of the HomeMatic Device that shall be used'

    hm_channel:
        type: int
        description:
            de: 'Optional: Kanal des Devices auf dem die Funktion angesteuert werden soll.
                 Muss nur angegeben werden, wenn die gewünschte Funktion von dem Device mehrfach zur Verfügung gestellt wird'
            en: 'Optional: Channel of the devicemon which the function shall be used.
                 Has only to be specified, if the requested function is implemented more than once on the device.'

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

