%YAML 1.1
# vim: set encoding=utf-8 tabstop=4 softtabstop=4 shiftwidth=4 expandtab
---
plugin:
    # Global plugin attributes
    type: gateway
    description:
        de: 'MultiDevice-Plugin'
        en: 'MultiDevice-Plugin'
    maintainer: Morg
    tester: OnkelAndy
    state: develop
    keywords: iot device
    # documentation: https://github.com/smarthomeNG/smarthome/wiki/MultiDevice-Plugin
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1742619-multidevice-plugin-universelles-plugin-framework
    version: 0.4.0
    sh_minversion: 1.8.2
    py_minversion: 3.6
    multi_instance: false
    restartable: true
    classname: MultiDevice
parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    devices:
        type: list
        description:
            de: 'Liste von Geräten mit Angaben zur Konfiguration:
                 devices:
                     - <Geräte-Typ>         # Geräte-ID = Geräte-Typ
                     - <Geräte-ID>: <Geräte-Typ>
                     - <Geräte-ID>:
                         - device_type: <Geräte-Typ>
                         - <Attribut1>: <Wert1>
                         - ...
                '
            en: 'List of devices and possibly their configuration:
                 devices:
                     - <device type>         # device id = device type
                     - <device id>: <device type>
                     - <device id>:
                         - device_type: <device type>
                         - <attribute1>: <value1>
                         - ...
                 '
        description_long:
            de: 'Liste von Geräten und ggf. deren Konfiguration. Geräte-ID ist eine
                 eindeutige Kennzeichnung, die auch in der Item-Konfiguration in der
                 Option ``md_device`` angegeben wird; Geräte-Typ ist der Name des
                 Gerätes im Ordner ``dev_<Geräte-Typ>``. Mindestangabe ist
                 der Geräte-Typ; wenn keine Geräte-ID vergeben wird, ist diese
                 gleich dem Geräte-Typ (beachte: pro Geräte-Typ nur einmal möglich).
                 Unterhalb der Listenebene der Geräte sind weitere Konfigurations-
                 attribute für die Geräte in der Listenform <Attribut>: <Wert>
                 möglich, z.B. Verbindungsattribute wie `host`, `port`, `serial` o.ä.
                 Genaue Angaben zu den möglichen Konfigurationsattributen sollten bei
                 den jeweiligen Geräte-Dateien vorhanden sein.

                 Beispiel:

                 devices:
                     - <Geräte-Typ>         # Geräte-ID = Geräte-Typ
                     - <Geräte-Typ>:        # Geräte-ID = Geräte-Typ
                         - <Attribut1>: <Wert1>
                         -...
                     - <Geräte-ID>: <Geräte-Typ>
                     - <Geräte-ID>:         # Geräte-Typ = Geräte-ID
                         - <Attribut1>: <Wert1>
                         - ...
                     - <Geräte-ID>:
                         - device_type: <Geräte-Typ>
                         - <Attribut1>: <Wert1>
                         - ...
                '
            en: 'List of devices and possibly their configuration. The device id
                 is a unique identifier, which is also used in the item configuration
                 for the ``md_device`` attribute; device type is the name of the
                 device in the ``dev_<device type>`` folder. Minimal configuration
                 consists of the device type; if no device id is provided, it will
                 be equal to the device type (possible only once per device type).
                 Below the list level with the devices further configuration
                 attributes can be supplied in the form <attribute>: <value>,
                 e.g. connection attributes like `host`, `port` or `serial`.
                 Specific information concerning possible attributes should be
                 provided with their respective device files.

                 Example:

                 devices:
                     - <device type>         # device id = device type
                     - <device type>:        # device id = device type
                         - <attribute1>: <value1>
                         -...
                     - <device id>: <device type>
                     - <device id>:         # device type = device id
                         - <attribute1>: <value1>
                         - ...
                     - <device id>:
                         - device_type: <device type>
                         - <attribute1>: <value1>
                         - ...
                '
item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    md_device:
        type: str
        description:
            de: 'Weist dem Item das Gerät mit dem angegebenen Namen zu'
            en: 'Assigns the item to the device with the supplied name'
    md_command:
        type: str
        description:
            de: 'Legt das angegebene Kommando für das Item fest'
            en: 'Assigns the given command to the item'
    md_read:
        type: bool
        description:
            de: 'Liest/erhält Werte vom Gerät'
            en: 'Reads/receives data from the device'
    md_read_group:
        type: list(str)
        description:
            de: 'Weist das Item der angegebenen Gruppe zum gesammelten Lesen zu. Gruppe kann int oder str sein, mehrere Gruppen können als Liste angegeben werden.'
            en: 'Assigns the item to the given group for collective reading. Groups can be int or str, multiple groups can be provided as a list.'
    md_read_cycle:
        type: num
        description:
            de: 'Konfiguriert ein Intervall in Sekunden für regelmäßiges Lesen'
            en: 'Configures a interval in seconds for cyclic read actions'
    md_read_initial:
        type: bool
        description:
            de: 'Legt fest, dass der Wert beim Start vom Gerät gelesen wird'
            en: 'Sets item value to be read from the device on startup'
    md_write:
        type: bool
        description:
            de: 'Änderung des Items werden an das Gerät gesendet'
            en: 'Changes to this item will be sent to the device'
    md_read_group_trigger:
        type: str
        description:
            de: 'Wenn diesem Item ein beliebiger Wert zugewiesen wird, werden alle zum Lesen konfigurierten Items der angegebenen Gruppe neu vom Gerät gelesen, bei Gruppe 0 werden alle zum Lesen konfigurierten Items neu gelesen. Das Item kann nicht gleichzeitig mit md_command belegt werden.'
            en: 'When set to any value, all items configured for reading for the given group will update their value from the device, if group is 0, all items configured for reading will update. The item cannot be used with md_command in parallel.'
    md_lookup:
        type: str
        description:
            de: 'Der Inhalt der Lookup-Tabelle mit dem angegebenen Namen wird beim Start einmalig als dict oder list in das Item geschrieben.'
            en: 'The lookup table with the given name will be assigned to the item in dict or list format once on startup.'
        description_long:
            de: 'Der Inhalt der Lookup-Tabelle mit dem angegebenen Namen wird beim
                 Start einmalig als dict oder list in das Item geschrieben.

                 Durch Anhängen von "#<mode>" an den Namen der Tabelle kann die Art
                 der Tabelle ausgewählt werden:
                 - fwd liefert die Tabelle Gerät -> SmartHomeNG (Standard)
                 - rev liefert die Tabelle SmartHomeNG -> Gerät
                 - rci liefert die Tabelle SmarthomeNG -> Gerät in Kleinbuchstaben
                 - list liefert die Liste der Namen für SmartHomeNG'
            en: 'The lookup table with the given name will be assigned to the item
                 in dict or list format once on startup.

                 By appending "#<mode>" to the tables name the type of table can
                 be selected:
                 - fwd returns the table device -> SmartHomeNG (default)
                 - rev returns the table SmartHomeNG -> device
                 - rci returns the table SmartHomeNG -> device in lower case
                 - list return the list of names for SmartHomeNG'
    md_custom1:
        type: str
        description:
            de: 'Der Inhalt dieses Items kann vom jeweiligen Gerät für spezielle Zwecke genutzt werden.'
            en: 'For custom use of each device respectively.'
        description_long:
            de: 'Der Inhalt dieses Items kann vom jeweiligen Gerät für spezielle Zwecke genutzt werden. Durch den Parameter "recursive_custom: 1" in der Geräte-Konfiguration wird der Wert rekursiv für alle Unteritems gesetzt.'
            en: 'For custom use of each device respectively. By setting "recursive_custom: 1" in the device configuration, the value of this attribute will be set for all sub-items.'
    md_custom2:
        type: str
        description:
            de: 'Der Inhalt dieses Items kann vom jeweiligen Gerät für spezielle Zwecke genutzt werden.'
            en: 'For custom use of each device respectively.'
        description_long:
            de: 'Der Inhalt dieses Items kann vom jeweiligen Gerät für spezielle Zwecke genutzt werden. Durch den Parameter "recursive_custom: 2" in der Geräte-Konfiguration wird der Wert rekursiv für alle Unteritems gesetzt.'
            en: 'For custom use of each device respectively. By setting "recursive_custom: 2" in the device configuration, the value of this attribute will be set for all sub-items.'
    md_custom3:
        type: str
        description:
            de: 'Der Inhalt dieses Items kann vom jeweiligen Gerät für spezielle Zwecke genutzt werden.'
            en: 'For custom use of each device respectively.'
        description_long:
            de: 'Der Inhalt dieses Items kann vom jeweiligen Gerät für spezielle Zwecke genutzt werden. Durch den Parameter "recursive_custom: 3" in der Geräte-Konfiguration wird der Wert rekursiv für alle Unteritems gesetzt.'
            en: 'For custom use of each device respectively. By setting "recursive_custom: 3" in the device configuration, the value of this attribute will be set for all sub-items.'


item_structs: NONE
# Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
# Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
# Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
