# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                 # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Schalten von 433 MHz Funksteckdosen z.B. für Brennenstuhl RCS 1000 N'
        en: 'Support for 433 MHz wireless sockets e.g. for Brennenstuhl RCS 1000 N'
    maintainer: dafra; hasenradball
    tester: hasenradball          # Who tests this plugin?
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/39094-logic-und-howto-für-433mhz-steckdosen

    version: 2.0.0                # Plugin version
    sh_minversion: 1.8            # minimum shNG version to use this plugin
#    sh_maxversion:               # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False         # plugin supports multi instance
    restartable: unknown
    classname: RCswitch           # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    rcswitch_dir:
        type: str
        default: '/usr/local/bin/python/rcSwitch-python'
        description:
            de: "Pfad des auf das src Direktory der Lib rcSwitch-python"
            en: "path of the src directory of the library rcSwitch-python"

    rcswitch_sendDuration:
        type: num
        default: 0.5
        valid_min: 0.0
        valid_max: 2.0
        description:
            de: "Minimale Zeit in Sekunden zwischen dem Senden von verschiedenen Befehlen"
            en: "Minimum time in s between sending of different commands"

    rcswitch_host:
        type: ip
        description:
            de: "IP oder HOSTNAME des rcswitch hosts, falls der Sender SmartHomeNG-Maschine angeschlossen ist\
                Achtung: Auf dem Remote Host muss ein SSH Server installiert sein."
            en: "IP or HOSTNAME of rcswitch host, in case the sender device is installed on a remote machine, if IP the IPv4 address has to be \
                 specified. Note: a SSH server has to be installed on the remote machine."

    rcswitch_user:
        type: str
        description:
            de: "User auf dem Remote Host"
            en: "user on the remote host"

    rcswitch_password:
        type: str
        description:
            de: "Passwort auf dem Remote Host"
            en: "password for user on the remote host"


item_attributes:
    # Definition of item attributes defined by this plugin
    rc_device:
        type: str
        valid_list:
            - 'A'
            - 'B'
            - 'C'
            - 'D'
            - 'E'
            - '10000'
            - '01000'
            - '00100'
            - '00010'
            - '00001'
        description:
            de: "ButtonCode (oder Buchstabe) des Gerätes"
            en: "ButtonCode (or letter) of the device"

    rc_code:
        type: str
        description:
            de: "SystemCode des Gerätes - Muss in der Form von 5 binären Digits angegeben werden [00000 - 11111]"
            en: "SystemCode of device - Must be 5 binary digits [00000 - 11111]"


item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

