# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Integration einer SQLite Datenbank - kompatibel mit smartVISU v2.7'
        en: 'Integration of a SQLite database - use this version of the plugin for smartVISU v2.7'
    maintainer: '?'
#    tester:                        # Who tests this plugin?
    keywords: database
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page

    version: 1.3.1.2               # Plugin version
    sh_minversion: 1.3c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: SQL                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
