# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Integration einer SQLite Datenbank - kompatibel mit smartVISU v2.7'
        en: 'Integration of a SQLite database - use this version of the plugin for smartVISU v2.7'
    maintainer: '?'
    tester: '?'                    # Who tests this plugin?
    state: deprecated
    keywords: database
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page

    version: 1.3.1.2               # Plugin version
    sh_minversion: 1.3c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: SQL                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    cycle:
        type: int
        valid_min: 0
        default: 300
        description:
            de: 'Zyklus-Zeit in dem die Datanbank Daten auf den Datentr채ger geschrieben werden'
            en: 'cycle time for data beeing written to disc'

    path:
        type: str
        description:
            de: "Pfad zur Datenbank Datei (Pfad ohne Dateiname)"
            en: "Path to the database file (path without filename)"
        default: None*

item_attributes:
    # Definition of item attributes defined by this plugin
    sqlite:
        type: str
        description:
            de: "Falls auf 'yes' gesetzt, wird der Wert des Items in die sqlite Datenbank geschrieben."
            en: "If set to 'yes', the value of the item will be written to the sqlite database"
        valid_list: ['', 'yes', 'init', 'True', 'no', 'False']

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin
    db:
        type: num
        description:
            de: "Diese Methode liefert einen Wert, f체r die gew채hlte Zeitspanne. Die Funktion legt fest, wie der Wert berechnet wird."
            en: "This method returns an value for the specified function and timeframe."
        parameters:
            function:
                type: str
                valid_list: ['avg', 'max', 'min', 'avg', 'sum']
                description:
                    de: "Funktion die genutzt wird um den R체ckgabewert zu berechnen"
                    en: "function used to calculate the return value"
            start:
                type: str
                description:
                    de: "Beginn der Zeitspanne"
                    en: "start of timeframe"
            end:
                type: str
                default: now
                description:
                    de: "Ende der Zeitspanne"
                    en: "end of timeframe"
