# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ansteuerung von Panasonic Klimaanlagen über die Panasonic Comfort Cloud'
        en: 'Control Panasonic air conditioning systems using the Panasonc comfort cloud'
    maintainer: msinn
#    tester:                         # Who tests this plugin?
    state: develop                    # change to ready when done with development
    keywords: panasonic cloud air-condition
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1976353-support-thread-für-das-panasonic_ac-plugin

    version: 0.3.1                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: '1.10.0'         # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: unknown
    configuration_needed: False     # False: The plugin will be enabled by the Admin GUI without configuration
    classname: PanComfortCloud      # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    username:
        type: str
        description:
            de: 'Login name für die Panasonic Comfort Cloud'
            en: 'Login name for the Panasonic comfort cloud'

    password:
        type: str
        description:
            de: 'Login Password für die Panasonic Comfort Cloud'
            en: 'Login password for the Panasonic comfort cloud'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

    pcc_index:
        type: str
        description:
            de: "Index der anzusteuernden Klimaanlage"
            en: "Index of the air conditioning unit"

    pcc_parameter:
        type: str
        valid_list:
            - name
            - temperatureInside
            - temperatureOutside
            - temperature
            - power
            - mode
            - fanSpeed
            - airSwingHorizontal
            - airSwingVertical
            - eco
            - nanoe
            - connected
        description:
            de: "Parameter der über pcc_index gewählten Klimaanlage"
            en: "Parameter of the air conditioning unit selected by pcc_index"


item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)
    air_condition:
        type: str
        #pcc_index: 1
        pcc_parameter: name
        device_connected:
            type: bool
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: connected
        temp_inside:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: temperatureInside
        temp_outside:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: temperatureOutside
        temp:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: temperature
        power:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: power
        mode:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: mode
        fanspeed:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: fanSpeed
        swing_hor:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: airSwingHorizontal
        swing_vert:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: airSwingVertical
        eco:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: eco
        nanoe:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: nanoe

    air_condition_enum:
        type: str
        #pcc_index: 2
        pcc_parameter: name
        device_connected:
            type: bool
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: connected
        temp_inside:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: temperatureInside
        temp_outside:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: temperatureOutside
        temp:
            type: num
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: temperature
        power:
            type: str
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: power
        mode:
            type: str
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: mode
        fanspeed:
            type: str
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: fanSpeed
        swing_hor:
            type: str
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: airSwingHorizontal
        swing_vert:
            type: str
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: airSwingVertical
        eco:
            type: str
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: eco
        nanoe:
            type: str
            enforce_updates: True
            pcc_index: ..:.
            pcc_parameter: nanoe


#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

