# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    subtype: core                 # plugin subtype (if applicable)
    description:                  # Alternative: description in multiple languages
        de: 'Web Interface zur Anzeige von Informationen zum System und SmartHomeNG Backend-Daten'
        en: 'webinterface for displaying system information and SmartHomeNG backend data'
    maintainer: psilo909, msinn, bmxp
    tester: Sandman60
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/959964-support-thread-für-das-backend-plugin

    version: 1.4.9                 # Plugin version
    sh_minversion: 1.4.1           # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: BackendServer       # class containing the plugin
    
parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    updates_allowed:
        type: bool
        default: True
        description:
            de: 'Update von Werten durch das Backend Plugin ist erlaubt'
            en: 'Update of values through the backend plugin is allowed'

    developer_mode:
        type: bool
        default: no
        description:
            de: 'Entwickler Modus aktiviert'
            en: 'Developer mode is activated'

    pypi_timeout:
        type: int
        default: 5
        description:
            de: 'Timeout bei der Abfrage der pypi Website'
            en: 'Timeout for getting data from the pypi website'

item_attributes:
    # Definition of item attributes defined by this plugin
    
