# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: system                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Installation von Plugins aus fremden GitHub-Repositories'
        en: 'Plugin to install plugins from foreign GitHub repositories'
    maintainer: Morg42
#    tester:                         # Who tests this plugin?
    state: develop                  # Initial 'develop'. change to 'ready' when done with development
    keywords: git github plugin
#    documentation: ''              # An url to optional plugin doc - NOT the url to user_doc!!!
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)

    # these min/max-versions MUST be given in quotes, or e.g. 3.10 will be interpreted as 3.1 (3.1 < 3.9 < 3.10)
    sh_minversion: '1.10'           # minimum shNG version to use this plugin
#    sh_maxversion: '1.11'          # maximum shNG version to use this plugin (omit if latest)
#    py_minversion: '3.10'          # minimum Python version to use for this plugin
#    py_maxversion: '4.25'          # maximum Python version to use for this plugin (omit if latest)

    multi_instance: false           # plugin supports multi instance
    restartable: true            # plugin supports stopping and starting again, must be implemented
    #configuration_needed: False     # False: The plugin will be enabled by the Admin GUI without configuration
    classname: GithubPlugin         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    app_token:
        type: str
        default: ''
        description:
            de: 'App-Token zum Zugriff auf GitHub (optional)'
            en: 'App token for accessing GitHub (optional)'


item_attributes: NONE

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
