# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                 # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Bang & Olufsen Masterlink Gateway'
        en: 'Bang & Olufsen Masterlink Gateway'
    maintainer: msinn
    tester: '?'                    # Who tests this plugin?
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page

    version: 1.1.1                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: False
    classname: Mlgw                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    host:
        type: ip
        default: 'mlgw.local'
        description:
            de: 'IP Adresse bzw. Hostname des Masterlink Gateways'
            en: 'ip address or hostname of the masterlink gateway'

    port:
        type: int
        default: 9000
        valid_min: 0
        description:
            de: 'Port Nummer des Masterlink Gateways'
            en: 'port number of the masterlink gateway'

    username:
        type: str
        default: 'mlgw'
        description:
            de: 'Username für das Login'
            en: 'Username for the login'

    password:
        type: str
        default: 'mlgw'
        description:
            de: 'Passwort für das Login'
            en: 'Password for the login'

    rooms:
        type: list
        default: []
        description:
            de: 'Liste der Räume'
            en: 'List of rooms'

    mlns:
        type: str
        default: []
        description:
            de: 'Liste der MLNs'
            en: 'List of MLNs'

    log_mlgwtelegrams:
        type: int
        default: 0
        valid_min: 0
        valid_max: 4
        description:
            de: 'Loglevel für die mlgw Telegramme'
            en: 'Loglevel for mlgw telegrams'

item_attributes:
    # Definition of item attributes defined by this plugin
    mlgw_send:
        type: str
        default: []
        description:
            de: 'Kommando welches gesendet werden soll'
            en: 'Command to be sent'

    mlgw_mln:
        type: str
        default: []
        description:
            de: 'MLN an die das Kommando gesendet werden soll'
            en: 'Destination MLN for the command'

    mlgw_listen:
        type: str
        default: []
        description:
            de: 'Befehlstyp auf den gehört werden soll (LIGHT/COMMAND)'
            en: 'Type of command (LIGHT/COMMAND)'

    mlgw_room:
        type: str
        default: []
        description:
            de: 'Raum aus dem der Befehl kommt'
            en: 'Room where the command is originating from'

    mlgw_cmd:
        type: str
        default: []
        description:
            de: 'Befehl auf den reagiert werden soll'
            en: 'Command to listen for'


item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

