# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Aufnahme und Abspielen von Aktionsreihenfolgen.'
        en: 'Recording And Replay of Actions on Items.'
    maintainer:  MichaelBu (?)
    tester: psilo909, Sandman60, cmalo
    state: ready
#    keywords: iot xyz
    documentation: https://www.smarthomeng.de/developer/plugins/simulation/README.html        # url of documentation (wiki) page
    support: 'https://knx-user-forum.de/forum/supportforen/smarthome-py/841097-anwesenheitssimulation-0-1'
    version: 1.5.0.7               # Plugin version
    sh_minversion: 1.4c             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: Simulation          # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    data_file:
        type: str
        mandatory: True
        description:
            de: 'Voller Pfad zum Datenfile (Textdatei).'
            en: 'Full path to data file (text file).'
    callers:
        type: list(str)
        mandatory: False
        description:
            de: '(optional) Liste von Event-Sourcen, um Events aufzuzeichnen. Wenn ein Item geändert wird, werden nur
            Events von Callern aus der Liste mit dem Plugin aufgezeichnet.'
            en: '(optional) List of event sources for recording of events. Only item changed with a caller in the list
            are recorded to the simulation file.'

item_attributes:
    # Definition of item attributes defined by this plugin
    sim:
        type: str
        mandatory: True
        description:
            de: 'Entweder der Wert "track", "state", "control", "message" oder "tank". Außer "track" dürfen die Werte
            nur exakt einem Item zugeordnet werden. Sie dienen der internen Datenhaltung des Plugins. "track"
            dient dazu, den Wert eines Items mit dem Plugin aufzuzeichnen. Es darf daher auch in mehreren Items gesetzt
            werden.'
            en: 'May be either the value "track", "state", "control", "message" or "tank". Besides "track" the values
            may only be assigned one time over all items. They are used for plugin internal information storage.
            "track" may be assigned to multiple items and is used to record the value changes of that item.'

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

