# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: "Anbindung eines KOSTAL-Wechselrichters  [KOSTAL](http://www.kostal-solar-electric.com/) \

             Das Plugin funktioniert aktuell mit den folgenden Inverter Moduln von KOSTAL:

               * KOSTAL PIKO 3.0 UI-Version 06.20 (datastructure=json)
               * KOSTAL PIKO 5.5 UI-Version 05.xx (datastructure=html)

               (should work with all KOSTAL PIKO inverters)"
        en: "This plugin is designed to retrieve data from a [KOSTAL](http://www.kostal-solar-electric.com/) inverter \
             module (e.g. PIKO inverters). Since UI-version (communication-board) 6 json-format is supported.

             Is currently working with the following KOSTAL inverter modules:

               * KOSTAL PIKO 3.0 UI-Version 06.20 (datastructure=json)
               * KOSTAL PIKO 5.5 UI-Version 05.xx (datastructure=html)

               (should work with all KOSTAL PIKO inverters)"
    maintainer: ohinckel
    tester: ohinckel, datenschuft
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1109697-kostal-plugin-piko-wechselrichter

    version: 1.3.1.2               # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: Kostal              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

#def __init__(self, sh, ip, user="pvserver", passwd="pvwr",cycle=300, datastructure="html"):

    ip:
        type: ip
        mandatory: True
        description:
            de: "IP Adresse des Konverters"
            en: "IP address of converter"

    user:
        type: str
        default: pvserver
        description:
            de: "Benutzername"
            en: "Username"

    passwd:
        type: str
        default: pvwr
        description:
            de: "Passwort"
            en: "Password"

    cycle:
        type: int
        default: 300
        description:
            de: "Zykluszeit"
            en: "Cycle time"

    datastructure:
        type: str
        default: html
        valid_list:
            - html
            - json
        description:
            de: "Format der Datenstrukturen (Falls json verwendet wird, sind keine Credentials notwendig)"
            en: "Format of datastructues (If json is used, no credentials are requred)"


item_attributes:
    # Definition of item attributes defined by this plugin

    kostal:
        type: str
        valid_list:
          - operation_status
          - dcpower
          - dc1_v
          - dc2_v
          - dc3_v
          - dc1_a
          - dc2_a
          - dc3_a
          - dc1_w
          - dc2_w
          - dc3_w
          - actot_w
          - actot_cos
          - actot_limitation
          - ac1_v
          - ac2_v
          - ac3_v
          - ac1_a
          - ac2_a
          - ac3_a
          - ac1_w
          - ac2_w
          - ac3_w
          - yield_day_kwh
          - yield_tot_kwh
          - operationtime_h
        valid_list_description:
            de:
              - 'Status des Kostal Inverters (On, Off, Feed in, starting)'
              - 'Summe DC Leistung (alle DC Eingänge); Einheit: Watt'
              - 'DC-Spannung Eingang 1; Einheit: Volt'
              - 'DC-Spannung Eingang 2; Einheit: Volt'
              - 'DC-Spannung Eingang 3; Einheit: Volt'
              - 'DC-Strom Eingang 1; Einheit: Ampere'
              - 'DC-Strom Eingang 2; Einheit: Ampere'
              - 'DC-Strom Eingang 3; Einheit: Ampere'
              - 'DC-Leistung Eingang 1; Einheit: Watt'
              - 'DC-Leistung Eingang 2; Einheit: Watt'
              - 'DC-Leistung Eingang 3; Einheit: Watt'
              - 'Summe AC Leistung (alle AC Phasen); Einheit: Watt'
              - 'Summe AC Cos φ'
              - 'Summe AC Limitierung; Einheit %'
              - 'AC Phase 1 Spannung; Einheit: Volt'
              - 'AC Phase 2 Spannung; Einheit: Volt'
              - 'AC Phase 3 Spannung; Einheit: Volt'
              - 'AC Phase 1 Strom; Einheit: Ampere'
              - 'AC Phase 2 Strom; Einheit: Ampere'
              - 'AC Phase 3 Strom; Einheit: Ampere'
              - 'AC Phase 1 Leistung; Einheit: Watt'
              - 'AC Phase 2 Leistung; Einheit: Watt'
              - 'AC Phase 3 Leistung; Einheit: Watt'
              - 'Ergebnis heute; Einheit kWh'
              - 'Ergebnis Gesamt; Einheit kWh'
              - 'Inverter Betriebszeit; Einheit Stunden'
            en:
              - 'status of the Kostal inverter (On, Off, Feed in, starting)'
              - 'total dc power (all dc inputs); unit: Watt'
              - 'DC-voltage input 1; unit: Voltage'
              - 'DC-voltage input 2; unit: Voltage'
              - 'DC-voltage input 3; unit: Voltage'
              - 'DC-current input 1; unit: Ampere'
              - 'DC-current input 2; unit: Ampere'
              - 'DC-current input 3; unit: Ampere'
              - 'DC-power input 1; unit: Watt'
              - 'DC-power input 2; unit: Watt'
              - 'DC-power input 3; unit: Watt'
              - 'total ac power (all ac phases); unit: Watt'
              - 'total ac Cos φ'
              - 'total ac limitation; unit %'
              - 'AC phase 1 voltage; unit: Voltage'
              - 'AC phase 2 voltage; unit: Voltage'
              - 'AC phase 3 voltage; unit: Voltage'
              - 'AC phase 1 current; unit: Ampere'
              - 'AC phase 2 current; unit: Ampere'
              - 'AC phase 3 current; unit: Ampere'
              - 'AC phase 1 power; unit: Watt'
              - 'AC phase 2 power; unit: Watt'
              - 'AC phase 3 power; unit: Watt'
              - 'Yield today; unit kWh'
              - 'Yield total; unit kWh'
              - 'Inverter operation time; unit hours'
        description:
            de: "Art der KOSTAL Daten, die im Item gespeichert werden"
            en: "Kind ao KOSTAL data to be stored in the item"


item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

