# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ansteuerung von AVM FRITZ!Boxen, WLAN-Repeatern, DECT Steckdosen, etc.'
        en: 'Get and send data from/to AVM devices such as the FRITZ!Box, Wifi Repeaters or DECT sockets.'
    maintainer: psilo909
    tester: Sandman60, cmalo
#    keywords: iot xyz
    state: 'qa-passed'
    documentation: http://smarthomeng.de/user/plugins/avm/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/934835-avm-plugin

    version: 1.5.9                 # Plugin version
    sh_minversion: 1.5b            # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: True
    classname: AVM                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    username:
        type: str
        default: ''
        description:
            de: '(optional) Nutzername für den Login. Kann für manche Features benötigt werden! (Speziell für Fritz!OS 7 ist die Konfiguration der Fritz!Box auf `Anmeldung mit FRITZ!Box-Benutzernamen und Kennwort` notwendig'
            en: '(optional) Login information (user). Can be needed to use some features of the AVM device. (Specially for Firtz!OS 7 the Fritz!Box should be configured for login with username and password'
    password:
        type: str
        default: ''
        hide: True
        description:
            de: '(optional) Passwort für den Login. Wird in der Regel immer benötigt und aus Sicherheitsgründen empfohlen.'
            en: '(optional) Password for login. Is normally always needed and recommended due to security reasons'
    host:
        type: str
        default: 'fritz.box'
        description:
            de: '(optional) Hostname oder IP-Adresse des FritzDevice.'
            en: '(optional) Hostname or ip address of the FritzDevice.'
    port:
        type: int
        default: 49443
        description:
            de: '(optional) Port des FritzDevice, normalerweise 49433 für https oder 49000 für http'
            en: '(optional) Port of the FritzDevice, typically 49433 for https or 49000 for http'
    cycle:
        type: int
        default: 300
        description:
            de: '(optional) Zeit zwischen zwei Updateläufen. Default ist 300 Sekunden.'
            en: '(optional) Time period between two update cycles. Default is 300 seconds.'
    ssl:
        type: bool
        default: True
        description:
            de: '(optional) Mit True wird das FritzDevice via https, mit False via http angesprochen.'
            en: '(optional) True will add "https", False "http" to the URLs in the plugin.'
    verify:
        type: bool
        default: False
        description:
            de: '(optional) Schaltet die Zertifikate-Prüfung an oder aus. Normalerweise False.'
            en: '(optional) Turns certificate verification on or off. Typically False'
    call_monitor:
        type: bool
        default: False
        description:
            de: '(optional) Aktiviert oder deaktiviert den MonitoringService, welcher auf den Call Monitor des FritzDevice verbindet. Der Call Monitor muss über ein verbundenes Telefon via #96*5* aktiviert sein.'
            en: '(optional) Activates or deactivates the MonitoringService, which connects to the FritzDevice`s call monitor. The call monitor has to be activated before by a connected telephone via calling #96*5*'
    call_monitor_incoming_filter:
        type: str
        default: ''
        description:
            de: '(optional) Spezielle Rufnummern ausfiltern, die vom Callmonitor ignoriert werden sollen.'
            en: '(optional) Filter only specific numbers to be watched by call monitor'

item_attributes:
    # Definition of item attributes defined by this plugin
    avm_data_type:
        type: str
        mandatory: True
        description:
            de: 'AVM Datentyp des jeweiligen Items.'
            en: 'AVM Data Type of the respective item.'
        valid_list:
        - 'uptime'
        - 'serial_number'
        - 'software_version'
        - 'hardware_version'
        - 'myfritz_status'
        - 'monitor_trigger'
        - 'is_call_incoming'
        - 'call_duration_incoming'
        - 'last_caller_incoming'
        - 'last_number_incoming'
        - 'last_called_number_incoming'
        - 'last_call_date_incoming'
        - 'call_event_incoming'
        - 'is_call_outgoing'
        - 'call_duration_outgoing'
        - 'last_caller_outgoing'
        - 'last_number_outgoing'
        - 'last_called_number_outgoing'
        - 'last_call_date_outgoing'
        - 'call_event_outgoing'
        - 'call_direction'
        - 'call_event'
        - 'tam'
        - 'tam_name'
        - 'tam_old_message_number'
        - 'tam_new_message_number'
        - 'tam_total_message_number'
        - 'wan_connection_status'
        - 'wan_connection_error'
        - 'wan_is_connected'
        - 'wan_uptime'
        - 'wan_ip'
        - 'wan_upstream'
        - 'wan_downstream'
        - 'wan_total_packets_sent'
        - 'wan_total_packets_received'
        - 'wan_current_packets_sent'
        - 'wan_current_packets_received'
        - 'wan_total_bytes_sent'
        - 'wan_total_bytes_received'
        - 'wan_current_bytes_sent'
        - 'wan_current_bytes_received'
        - 'wan_link'
        - 'wlanconfig'
        - 'wlanconfig_ssid'
        - 'wlan_guest_time_remaining'
        - 'network_device'
        - 'device_ip'
        - 'device_connection_type'
        - 'device_hostname'
        - 'aha_device'
        - 'energy'
        - 'power'
        - 'temperature'
        - 'set_temperature'
        - 'set_temperature_reduced'
        - 'set_temperature_compfort'
        - 'hkr_device'
        - 'firmware_version'
        - 'manufacturer'
        - 'product_name'
        - 'device_name'
        - 'connection_status'
        - 'device_id'
        - 'device_function'

    avm_incoming_allowed:
        type: str
        mandatory: False
        description:
            de: '(optional) Definition der erlaubten eingehenden Rufnummer in Items vom avm_data_type `monitor_trigger`.'
            en: '(optional) Definition of the allowed incoming number. Only in items of avm_data_type `monitor_trigger`.'
    avm_target_number:
        type: str
        mandatory: False
        description:
            de: '(optional) Definition der erlaubten angerufenen Rufnummer in Items vom avm_data_type `monitor_trigger`.'
            en: '(optional) Definition of the allowed called number. Only in items of avm_data_type `monitor_trigger`.'
    mac:
        type: mac
        mandatory: False
        description:
            de: 'Definition der MAC Adresse für Items vom avm_data_type `network_device`. Nur für diese Items mandatory!'
            en: 'Definition of the MAC address for items of avm_data_type `network_device`. Only mandatory for these items!'
    ain:
        type: str
        mandatory: False
        description:
            de: 'Definition der Aktor Identifikationsnummer (AIN)Items vom avm_data_type `aha_device`. Nur für diese Items mandatory!'
            en: 'Definition of the actor identification number (AIN) for items of avm_data_type `aha_device`. Only mandatory for these items!'

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin

    cancel_call:
        type: void
        description:
            de: "Beendet einen aktiven Anruf."
            en: "Cancels an active call."
        parameters:
        # This function has no parameters

    get_call_origin:
        type: str
        description:
            de: "Gib den Namen des Telefons zurück, das aktuell als 'call origin' gesetzt ist."
            en: "Gets the phone name, currently set as 'call origin'."
        parameters:
        # This function has no parameters

    get_calllist:
        type: list(dict(str))
        description:
            de: "Ermittelt ein Array mit dicts aller Einträge der Anrufliste (Attribute 'Id', 'Type', 'Caller', 'Called', 'CalledNumber', 'Name', 'Numbertype', 'Device', 'Port', 'Date',' Duration' (einige optional))."
            en: "Returns an array of dicts with all calllist entries (attributes 'Id', 'Type', 'Caller', 'Called', 'CalledNumber', 'Name', 'Numbertype', 'Device', 'Port', 'Date', 'Duration' (some optional))."
        parameters:
            filter_incoming:
                type: str
                default: ''
                description:
                    de: "Filter, um nur die Anrufe zu erhalten, die zu einer bestimmten angerufenen Nummer gehören."
                    en: "Filter to filter calls to a specific destination phone number."
            phonebook_id:
                type: int
                default: 0
                description:
                    de: "ID des Telefonbuchs, in dem nachgeschlagen werden soll."
                    en: "ID of the phone book, in which numbers should be looked up."

    get_contact_name_by_phone_number:
        type: str
        description:
            de: "Durchsucht das Telefonbuch mit einer (vollständigen) Telefonnummer nach Kontakten. Falls kein Name gefunden wird, wird die Telefonnummer zurückgeliefert."
            en: "Searches the phonebook for a contact by a given (complete) phone number. In case no name is found, the phone number is returned."
        parameters:
            phone_number:
                type: str
                description:
                    de: "Vollständige Telefonnummer"
                    en: "Complete phone number"
            phonebook_id:
                type: int
                default: 0
                description:
                    de: "ID des Telefonbuchs, in dem nachgeschlagen werden soll."
                    en: "ID of the phone book, in which numbers should be looked up."

    get_host_details:
        type: dict(str)
        description:
            de: "Ermittelt die Informationen zu einem Host an einem angegebenen Index."
            en: "Gets the information of a hosts at a specific index."
        parameters:
            index:
                type: int
                description:
                    de: "Index"
                    en: "Index"

    get_hosts:
        type: list(dict(str))
        description:
            de: "Ermittelt ein Array mit den Namen aller verbundener Hosts."
            en: "Gets the name of all connected hosts as an array."
        parameters:
            only_active:
                type: bool
                description:
                    de: "True, wenn nur aktuell aktive Hosts zurückgegeben werden sollen."
                    en: "True, if only active hosts shall be returned."

    get_phone_name:
        type: str
        description:
            de: "Gibt den Namen eines Telefons an einem Index zurück. Der zurückgegebene Wert kann in 'set_call_origin' verwendet werden."
            en: "Get the phone name at a specific index. The returend value can be used as phone_name for set_call_origin."
        parameters:
            index:
                type: int
                description:
                    de: "Index"
                    en: "Index"

    get_phone_numbers_by_name:
        type: dict(dict(str))
        description:
            de: "Durchsucht das Telefonbuch mit einem Namen nach nach Kontakten und liefert die zugehörigen Telefonnummern."
            en: "Searches the phonebook for a contact by a given name and returns the corresponding phone numbers."
        parameters:
            name:
                type: str
                description:
                    de: "Anteiliger oder vollständiger Name des Kontakts."
                    en: "Partial or full name of the contact."
            phonebook_id:
                type: int
                default: 0
                description:
                    de: "ID des Telefonbuchs, in dem nachgeschlagen werden soll."
                    en: "ID of the phone book, in which numbers should be looked up."

    is_host_active:
        type: bool
        description:
            de: "Prüft, ob eine MAC Adresse auf dem Gerät aktiv ist. Das kann bspw. für die Umsetzung einer Präsenzerkennung genutzt werden."
            en: "Checks if a MAC address is active on the FritzDevice, e.g. the status can be used for simple presence detection."
        parameters:
            mac_address:
                type: mac
                description:
                    de: "MAC Adresse"
                    en: "MAC address"

    reboot:
        type: void
        description:
            de: "Startet das Gerät neu."
            en: "Reboots the device."
        parameters:
        # This function has no parameters

    reconnect:
        type: void
        description:
            de: "Verbindet das Gerät neu mit dem WAN (Wide Area Network)."
            en: "Reconnects the device to the WAN (Wide Area Network)."
        parameters:
        # This function has no parameters

    set_call_origin:
        type: void
        description:
            de: "Setzt den 'call origin', bspw. vor dem Aufruf von 'start_call'."
            en: "Sets the 'call origin', e.g. before running 'start_call'."
        parameters:
            phone_name:
                type: mac
                description:
                    de: "Identifikator des Telefons, dass als 'call origin' gesetzt werden soll. Bspw. zwei Sterne gefolgt von '610' für ein internes Gerät."
                    en: "Full phone identifier, could be e.g. two asterix followed by '610' for an internal device."

    start_call:
        type: void
        description:
            de: "Startet einen Anruf an eine übergebene Telefonnummer (intern oder extern)."
            en: "Starts a call for a given phone number (internal or external)."
        parameters:
            phone_number:
                type: str
                description:
                    de: "Vollständige Telefonnummer, die angerufen werden soll."
                    en: "Full phone number to call"

    wol:
        type: void
        description:
            de: "Sendet einen WOL (WakeOnLAN) Befehl an eine MAC Adresse."
            en: "Sends a WOL (WakeOnLAN) command to a MAC address."
        parameters:
            mac_address:
                type: mac
                description:
                    de: "MAC Adresse"
                    en: "MAC address"