# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ansteuerung von AVM FRITZ!Boxen, WLAN-Repeatern, DECT Steckdosen, etc.'
        en: 'Get and send data from/to AVM devices such as the FRITZ!Box, Wifi Repeaters or DECT sockets.'
    maintainer: psilo909
    tester: Sandman60, cmalo
#    keywords: iot xyz
    documentation: http://smarthomeng.de/user/plugins_doc/config/avm.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/934835-avm-plugin

    version: 1.4.3                 # Plugin version
    sh_minversion: 1.3c             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    classname: AVM                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
