plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Integration von Systemen die eine Luxtronic-Steuerung haben (z.B Heizungen)'
        en: 'Integration of systems that have a Luxtronic interface (e.g. heating systems)'
    maintainer: '? (2ndsky)'
    tester: ohinckel
    state: qa-passed
#    keywords: kwd1 kwd2            # keywords, where applicable
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.3.3                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: false
    restartable: true
    classname: Luxtronic2           # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    host:
        type: str
        description:
            de: 'Gibt den Host des Gerätes an'
            en: 'Specifies the host of the device'
    port:
        type: int
        default: 8888
        description:
            de: 'Gibt den Port des Gerätes an'
            en: 'Specifies the port of the devices'

    cycle:
        type: int
        default: 300
        description:
            de: 'Zeitintervall zur Datenabfrage'
            en: 'Interval for retrieving data'

item_attributes:
    # Definition of item attributes defined by this plugin
    lux2:
        type: int
        description:
            de: 'Gibt einen Parameterwert an, der automatisch dekodiert werden (z.B. Umwandlung Betriebsart zu einem Text)'
            en: 'Specifies a parameter value which will automatically be decoded (e.g. operation mode to text)'
        valid_list:
          - 10
          - 11
          - 12
          - 14
          - 15
          - 16
          - 18
          - 19
          - 20
          - 56
          - 57
          - 60
          - 63
          - 64
          - 65
          - 119
          - 151
          - 152
          - 159

        valid_list_description:
            de:
              - ''
              - ''
              - ''
              - 'Temperatur Heißgas'
              - ''
              - 'Temperatur Mittelwert'
              - 'Temperatur Warmwasser SOLL'
              - ''
              - ''
              - 'Betriebsstunden Verdichter'
              - 'Impulse Verdichter'
              - 'Betriebsstunden Zusatzheizung'
              - 'Betriebsstunden Wärmepumpe Gesamt'
              - 'Betriebsstunden Wärmepumpe Heizung'
              - 'Betriebsstunden Wärmepumpe Warmwasser'
              - 'Betriebs-Modus'
              - ''
              - ''
              - 'Temperatur Zuluft'
            en:
              - ''
              - ''
              - ''
              - 'Temperature heating gas'
              - ''
              - 'Temperature average'
              - 'TARGET hot water temperature'
              - ''
              - ''
              - 'Compressor operating hours'
              - 'Compressor impulses'
              - 'Operating hours auxiliary heating'
              - 'Total operating hours heat pump'
              - 'Operating hours heat pump heating'
              - 'Operating hours heat pump hot water'
              - 'Operation mode'
              - ''
              - ''
              - 'Temperature supply air'

    lux2_a:
        type: int
        description:
            de: 'Gibt einen Attributwert an, der ausgelesen werden soll (Zugriff ist nur lesend)'
            en: 'Specifies the attribute value which should be read (only read-only access)'
    lux2_c:
        type: int
        description:
            de: 'Gibt einen berechneten Attributwert an (Zugriff ist nur lesend)'
            en: 'Specifies the attribute value which should be calculated (only read-only access)'
    lux2_p:
        type: int
        description:
            de: 'Gibt einen Attributwert für einen Parameter an (Zugriff lesend und schreibend)'
            en: 'Specifies the attribute value for parameter (read and write access)'

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

