# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: system                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ermöglicht Speicherung von Item Werten in einer InfluxData time-series Datenbank'
        en: 'Plugin to store item values in an InfluxData time-series database'
    maintainer: msinn
    tester: msinn                   # Who tests this plugin?
    state: develop                  # change to ready when done with development
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1498207-support-thread-für-influxdb-plugin

    version: 0.1.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.9              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: false           # plugin supports multi instance
    restartable: unknown
    startorder: early               # set start priority of plugin (early/normal/late)
    classname: InfluxDB2            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    host:
        type: str
        default: '127.0.0.1'
        description:
            de: "Hostname/IP-Adresse des Influxdata Servers"
            en: "Hostname/ip address of the Influxdata server"
    http_port:
        type: int
        default: 8086
        valid_min: 0
        valid_max: 65535
        description:
            de: "Portnummer der InfluxData Datenbank für HTTP-Zugr für HTTP-Zugriff"
            en: "Port of the Influxdata server for HTTP access"
    api_token:
        type: str
        mandatory: True
        description:
            de: "Security Token um auf den Influxdata Server zugreifen zu dürfen"
            en: "Security Token for accessing the Influxdata server"
    org:
        type: str
        default: smarthomeng
        description:
            de: "Organisation zum speichern von Zeitserien auf dem Influxdata Server"
            en: "Organization for storing time-series data on the Influxdata server"
    bucket:
        type: str
        default: shng
        description:
            de: "Default-Bucket (benannte Lokation) zum speichern von Zeitserien auf dem Influxdata Server"
            en: "Default-Bucket (named location) for storing time-series data on the Influxdata server"
    tags:
        type: dict
        description:
            de: 'Globale Angabe zusätzlicher Tags, die mit den Werten aller Items gespeichert werden sollen (z.B.: {"raum": "wohnen"})'
            en: 'Specify additional global tags to be stored with the value of all items (e.g.: {"room": "living"}'

    recognize_database:
        type: bool
        description:
            de: 'Steuert ob Items, die das Attribut **database** tragen, in die InfluxDB geschrieben werden sollen'
            en: 'Controls if items that carry the **database** attribute should be written ti the InfluxDB'

    value_field:
        type: str
        default: 'value'
        description:
            de: 'Name des Fields in welches der Item Wert geschrieben werden soll (Sollte normalerweise auf dem Standardwert bleiben)'
            en: "Name of the field, to store the items' value in ("

    str_value_field:
        type: str
        default: 'str_value'
        description:
            de: 'Name des Fields in welches nicht-numerische Item Werte geschrieben werden sollen (Sollte normalerweise auf dem Standardwert bleiben)'
            en: "Name of the field, to store the non-numeric values in"


item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    influxdb2:
        type: str
        valid_list_ci: ['', 'yes', 'init', 'true']
        description:
            de: "Wenn auf 'yes' oder 'true' gesetzt, werden die Werte des Items in die Datenbank geschrieben. Wenn auf 'init' gesetzt, wird zusätzlich beim Start von SmartHomeNG der Wert des Items aus der Datenbank gelesen."
            en: "This attribute enables the database logging when set (just use value 'yes' or 'true'). If value 'init' is used, an item will be initalized from the database after SmartHomeNG is restarted."
    influxdb2_bucket:
        type: str
        description:
            de: "Default-Bucket (benannte Lokation) zum speichern von Zeitserien auf dem Influxdata Server"
            en: "Default-Bucket (named location) for storing time-series data on the Influxdata server"
    influxdb2_name:
        type: str
        description:
            de: "In der InfluxDB verwendeter Name für das Item (Optional)"
            en: "Name for the item to be used in InfluxDB (optional)"
    influxdb2_tags:
        type: str
        description:
            de: 'Angabe weiterer Tags, die mit dem Wert gespeichert werden sollen (z.B.: {"raum": "wohnen"})'
            en: 'Specify additional tags to be stored with the value (e.g.: {"room": "living"}'

    database:
        type: str
        valid_list_ci: ['', 'yes', 'init', 'true']
        duplicate_use: True
        description:
            de: "Wenn auf 'yes' oder 'true' gesetzt, werden die Werte des Items in die Datenbank geschrieben. Wenn auf 'init' gesetzt, wird zusätzlich beim Start von SmartHomeNG der Wert des Items aus der Datenbank gelesen."
            en: "This attribute enables the database logging when set (just use value 'yes' or 'true'). If value 'init' is used, an item will be initalized from the database after SmartHomeNG is restarted."

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
