coil_bereiche = (
    [   0,   39], [  56,   68], [  87,  112], [ 115,  123], [ 129,  167],
    [ 175,  214], [ 221,  237], [ 244,  308], [ 321,  337], [ 997, 1008],
    [1016, 1018], [1024, 1044], [1199, 1208], [1211, 1212], [1216, 1218],
    [1224, 1237], [1799, 1808], [1824, 1844], [9899, 9910],
    [55999, 56006], [65534, 65534] 
)


coil_tabelle = {
    'Sammelstoerung':    { 'ID':     0, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Sammelstoerung, Fehlerstatusregister HR40150 > 0' },
    'Dateneingaktiv':    { 'ID':     1, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Dateneingabe aktiv' },
    'Dateneingstattg':   { 'ID':     2, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Dateneingabe stattgefunden' },
    'SammelEbenenbit':   { 'ID':     3, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Sammel-Ebenenbit CL88-CL121' },
    'StatusHandbRk1':    { 'ID':     4, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Handbetrieb Heizkreis RK1' },
    'StatusHandbRk2':    { 'ID':     5, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Handbetrieb Heizkreis RK2' },
    'Unbekannt-6':       { 'ID':     6, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'StatusHandbTW':     { 'ID':     7, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Handbetrieb TW' },
    'Sommerbetrieb':     { 'ID':     8, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Sommerbetrieb aktiv (CO5, Fb04)' },
    'WMZKomStoer#1':     { 'ID':     9, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Kommunikationsstoerung Zaehlerbus WMZ #1 (CO6, Fb10)' },
    'WMZKomStoer#2':     { 'ID':    10, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Kommunikationsstoerung Zaehlerbus WMZ #2 (CO6, Fb10)' },
    'WMZKomStoer#3':     { 'ID':    11, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Kommunikationsstoerung Zaehlerbus WMZ #3 (CO6, Fb10)' },
    'WMZFehlerWMZ#1':    { 'ID':    12, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Fehler WMZ #1 (CO6, Fb10)' },
    'WMZFehlerWMZ#2':    { 'ID':    13, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Fehler WMZ #2 (CO6, Fb10)' },
    'WMZFehlerWMZ#3':    { 'ID':    14, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Fehler WMZ #3 (CO6, Fb10)' },
    'WMZ-Auslesung#1':   { 'ID':    15, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1 = 1xAuslesung WMZ #1 veranlassen' },
    'WMZ-Auslesung#2':   { 'ID':    16, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1 = 1xAuslesung WMZ #2 veranlassen' },
    'WMZ-Auslesung#3':   { 'ID':    17, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1 = 1xAuslesung WMZ #3 veranlassen' },
    'Unbekannt-18':      { 'ID':    18, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-19':      { 'ID':    19, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-20':      { 'ID':    20, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'WMZDflussBeg#1':    { 'ID':    21, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Durchflussbegrenzung #1 aktiv (CO5,Fb11/CO6,Fb11)' },
    'WMZLeistBeg#1':     { 'ID':    22, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Leistungsbegrenzung #1 aktiv (CO5,Fb10/ CO6,Fb12)' },
    'BinaereingBE01':    { 'ID':    23, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE01' },
    'BinaereingBE02':    { 'ID':    24, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE02' },
    'BinaereingBE03':    { 'ID':    25, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE03' },
    'BinaereingBE04':    { 'ID':    26, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE04' },
    'BinaereingBE05':    { 'ID':    27, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE05' },
    'BinaereingBE06':    { 'ID':    28, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE06' },
    'BinaereingBE07':    { 'ID':    29, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE07' },
    'BinaereingBE08':    { 'ID':    30, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE08' },
    'BinaereingBE09':    { 'ID':    31, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE09' },
    'BinaereingBE10':    { 'ID':    32, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE10' },
    'BinaereingBE11':    { 'ID':    33, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE11' },
    'BinaereingBE12':    { 'ID':    34, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE12' },
    'BinaereingBE13':    { 'ID':    35, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE13' },
    'BinaereingBE14':    { 'ID':    36, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE14' },
    'BinaereingBE15':    { 'ID':    37, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE15' },
    'BinaereingBE16':    { 'ID':    38, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE16' },
    'BinaereingBE17':    { 'ID':    39, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Status Binaereingang BE17' },
    'BinaerausgBA1':     { 'ID':    56, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Umwaelzpumpe Rk1 (UP1 Netzseite, CL96)' },
    'BinaerausgBA2':     { 'ID':    57, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Umwaelzpumpe Rk2 (UP2, Netzseite, CL97)' },
    'Unbekannt-58':      { 'ID':    58, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'BinaerausgBA4':     { 'ID':    59, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Speicherladepumpe TW (SLP, CL99)' },
    'BinaerausgBA5':     { 'ID':    60, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Zirkulationspumpe (ZP, CL100)' },
    'BinaerausgBA6':     { 'ID':    61, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_HZ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Rk13-Pkt Zu-Signal (Vorgabe in HR40107)' },
    'BinaerausgBA7':     { 'ID':    62, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_HA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Rk13-Pkt Auf-Signal (HR40107), 2-Pkt (CL102)' },
    'BinaerausgBA8':     { 'ID':    63, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_HZ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Rk23-Pkt Zu-Signal (Vorgabe in HR40109)' },
    'BinaerausgBA9':     { 'ID':    64, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_HA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Rk23-Pkt Auf-Signal (HR40109), 2-Pkt (CL104)' },
    'Unbekannt-65':      { 'ID':    65, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-66':      { 'ID':    66, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'BinaerausgBA12':    { 'ID':    67, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Pumpenmanagement UP1Ein/Aus (CL107)' },
    'BinaerausgBA13':    { 'ID':    68, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Pumpenmanagement Drehzahl UP1(CL108)' },
    'EBNAussentemAF1':   { 'ID':    87, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Aussentemperatur AF1 (HR40010)' },
    'EBNBetrArtRk1':     { 'ID':    88, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Betriebsart Rk1 (HR40106)' },
    'EBNStellsigRk1':    { 'ID':    89, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Stellsignal Rk1 (HR40107)' },
    'EBNBetrArtRk2':     { 'ID':    90, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Betriebsart Rk2 (HR40108)' },
    'EBNStellsigRk2':    { 'ID':    91, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Stellsignal Rk2 (HR40109)' },
    'Unbekannt-92':      { 'ID':    92, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-93':      { 'ID':    93, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'EBNBetrArtTW':      { 'ID':    94, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Betriebsart TW (HR40112)' },
    'EBNBinaerBA1':      { 'ID':    95, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Umwaelzpumpe Rk1 (UP1, Netzseite, CL57)' },
    'EBNBinaerBA2':      { 'ID':    96, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Umwaelzpumpe Rk2 (UP2, Netzseite, CL58)' },
    'Unbekannt-97':      { 'ID':    97, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'EBNBinaerBA4':      { 'ID':    98, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Speicherladepumpe TW (SLP, CL60)' },
    'EBNBinaerBA5':      { 'ID':    99, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Zirkulationspumpe (ZP, CL61)' },
    'EBNBinaerBA6':      { 'ID':   100, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Binaer BA6' },
    'EBNBinaerBA7':      { 'ID':   101, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Rk12-Pkt-Signal (CL63)' },
    'EBNBinaerBA8':      { 'ID':   102, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Binaer BA8' },
    'EBNBinaerBA9':      { 'ID':   103, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Rk22-Pkt-Signal (CL65)' },
    'Unbekannt-104':     { 'ID':   104, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-105':     { 'ID':   105, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'EBNBinaerBA12':     { 'ID':   106, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Pumpenmanagement UP1 Ein/Aus (CL68)' },
    'EBNBinaerBA13':     { 'ID':   107, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Pumpenmanagement Drehzahl UP1(CL69)' },
    'EBNAA1':            { 'ID':   108, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Analogausgang 1 (0..10V)' },
    'EBNAA2':            { 'ID':   109, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Analogausgang 2 (0..10V)' },
    'Unbekannt-110':     { 'ID':   110, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'EBNSonTWSollw':     { 'ID':   111, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Sonder-Trinkwassersollwert (HR41809)' },
    'EBNSonPuffSollw':   { 'ID':   112, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Sonder-Pufferspeichersollwert (HR41045)' },
    'EBNVorlSollRk1':    { 'ID':   115, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Vorlaufsollwert Rk1 (HR41000)' },
    'EBNRueckSollRk1':   { 'ID':   116, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Ruecklaufsollwert Rk1 (HR41033)' },
    'EBNVorlSollRk2':    { 'ID':   117, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Vorlaufsollwert Rk2 (HR41200)' },
    'EBNRueckSollRk2':   { 'ID':   118, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ebene Ruecklaufsollwert Rk2 (HR41233)' },
    'Unbekannt-119':     { 'ID':   119, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-120':     { 'ID':   120, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-121':     { 'ID':   121, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-122':     { 'ID':   122, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-123':     { 'ID':   123, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB01Pt1000':        { 'ID':   129, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB01: Pt1000- (Pt100)- Fuehler' },
    'FB02NTC':           { 'ID':   130, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB02: NTC- (Pt100)- Fuehler' },
    'FB03Pt500':         { 'ID':   131, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB03: Pt500- (Pt100)- Fuehler' },
    'FB04Sommerbtr':     { 'ID':   132, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB04: Sommerbetrieb' },
    'FB05VerzATAnp':     { 'ID':   133, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB05: Verzoegerte Aussentemperaturanpassung fallend' },
    'FB06VerzATAnp':     { 'ID':   134, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB06: Verzoegerte Aussentemperaturanpassung steigend' },
    'FB07Stoerausgang':  { 'ID':   135, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB07: Stoermeldeausgang BA13' },
    'FB08AutSommZeit':   { 'ID':   136, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB08: Automatische Sommer-/Winterzeitumschaltung' },
    'FB09Frostschutz':   { 'ID':   137, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB09: Frostschutzprogramm (I=>FB09=0, II=>FB09=1)' },
    'FB10LeistBeg':      { 'ID':   138, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB10: Durchfluss-/Leistungsbegrenzung mit Impulsen' },
    'FB11DflussBegmA':   { 'ID':   139, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB11: Durchflussbegrenzung mit 0/4..20mA-Signal' },
    'FB12Schleichmng':   { 'ID':   140, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB12: Schleichmengenunterdrueckung per BE13' },
    'FB13LeistBegmA':    { 'ID':   141, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB13: Leistungsbegr. bas. Volumenstr. 0/4-20mA Rk1' },
    'FB14BetrUP1':       { 'ID':   142, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB14: Betrieb UP1 bei Eigenbedarf' },
    'FB15FrgRegBE15':    { 'ID':   143, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB15: Freigabe Regler an BE15 (Stdby-Betr. bE/1,0)' },
    'FB16Ruecklbegr':    { 'ID':   144, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB16: P-Verhalten bei Ruecklauftemperaturbegrenzung' },
    'FB17UPManagmt':     { 'ID':   145, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB17: Pumpenmanagement Schaltverh. BA13 (ab V1.30)' },
    'Unbekannt-146':     { 'ID':   146, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB19Tempueberw':    { 'ID':   147, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB19: Temperaturueberwachung' },
    'Unbekannt-148':     { 'ID':   148, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB21SperrHand':     { 'ID':   149, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB21: Sperrung der Handebenen' },
    'FB22SperrDreh':     { 'ID':   150, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB22: Sperrung der Drehschalter' },
    'FB23AT0bis10V':     { 'ID':   151, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB23: Aussentemperatur mittels 0 bis 10V erfassen' },
    'FB01Modbus':        { 'ID':   152, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB01: Modbusbetrieb' },
    'FB0216bit':         { 'ID':   153, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB02: Modbus 16-bit-Adressierung' },
    'FB03Modem':         { 'ID':   154, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB03: Modemfunktion' },
    'FB04AutoModem':     { 'ID':   155, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB04: Automatische Modemkonfiguration' },
    'FB05SperrModem':    { 'ID':   156, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB05: Sperrung der GLT-Anwahl' },
    'FB06Anwgehend':     { 'ID':   157, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB06: GLT-Anwahl auch bei gehenden Stoerungen' },
    'FB07TimeoutGLT':    { 'ID':   158, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB07: Leitsystemueberwachung' },
    'FB08SMS':           { 'ID':   159, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB08: SMS-Betrieb' },
    'Unbekannt-160':     { 'ID':   160, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB10Zaehlerbus':    { 'ID':   161, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB10: Zaehlerbus-Betrieb' },
    'FB11DflussBeg':     { 'ID':   162, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB11: Durchflussbegrenzung in Rk1 mittels Zaehlerbus' },
    'FB12LeistBeg':      { 'ID':   163, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB12: Leistungsbegrenzung in Rk1 mittels Zaehlerbus' },
    'Unbekannt-164':     { 'ID':   164, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-165':     { 'ID':   165, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-166':     { 'ID':   166, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-167':     { 'ID':   167, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB01Geraetebus':    { 'ID':   175, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB01: Geraetebus' },
    'FB02Uhrzeitsync':   { 'ID':   176, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB02: Uhrzeitsynchronisation' },
    'FB03RaumleitRk1':   { 'ID':   177, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB03: Raumleitgeraet TROVIS 5570 in Rk1' },
    'FB04RaumleitRk2':   { 'ID':   178, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB04: Raumleitgeraet TROVIS 5570 in Rk2' },
    'Unbekannt-179':     { 'ID':   179, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB06SendenAF1':     { 'ID':   180, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB06: Wert AF1 senden' },
    'FB07EmpfangAF1':    { 'ID':   181, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB07: Wert AF1 empfangen' },
    'FB08SendenAF2':     { 'ID':   182, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB08: Wert AF2 senden' },
    'FB09EmpfangAF2':    { 'ID':   183, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB09: Wert AF2 empfangen' },
    'FB10SendSollRk1':   { 'ID':   184, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB10: Vorlaufsollwert Rk1 senden' },
    'FB11SendSollRk2':   { 'ID':   185, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB11: Vorlaufsollwert Rk2 senden' },
    'Unbekannt-186':     { 'ID':   186, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB13SendSollTW':    { 'ID':   187, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB13: Vorlaufsollwert TW senden' },
    'FB14SendSollMax':   { 'ID':   188, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB14: Maximalen Vorlaufsollwert senden' },
    'FB15EmpfangBed':    { 'ID':   189, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB15: Bedarf empfangen' },
    'FB16Stoermeldung':  { 'ID':   190, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB16: Stoermeldungen via Geraetebus' },
    'Unbekannt-191':     { 'ID':   191, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-192':     { 'ID':   192, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB19AnhRueckGW':    { 'ID':   193, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB19: Anhebung Ruecklauftemperaturgrenzwert' },
    'FB20SendTW':        { 'ID':   194, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB20: Trinkwassererwaermumg aktiv senden' },
    'FB21FrgRk1Empf':    { 'ID':   195, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Freigabe Rk1 empfangen' },
    'FB22FRgRk2Empf':    { 'ID':   196, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_AE', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Freigabe Rk2 empfangen' },
    'Unbekannt-197':     { 'ID':   197, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB01BE01':          { 'ID':   198, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB01: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB02BE02':          { 'ID':   199, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB02: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB03BE03':          { 'ID':   200, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB03: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB04BE04':          { 'ID':   201, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB04: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB05BE05':          { 'ID':   202, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB05: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB06BE06':          { 'ID':   203, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB06: 1=>Binaereingang/ 0=Sensoreingang' },
    'Unbekannt-204':     { 'ID':   204, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-205':     { 'ID':   205, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB09BE09':          { 'ID':   206, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB09: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB10BE10':          { 'ID':   207, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB10: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB11BE11':          { 'ID':   208, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB11: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB12BE12':          { 'ID':   209, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB12: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB13BE13':          { 'ID':   210, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB13: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB15BE15':          { 'ID':   211, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB15: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB16BE16':          { 'ID':   212, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB16: 1=>Binaereingang/ 0=Sensoreingang' },
    'FB17BE17':          { 'ID':   213, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB17: 1=>Binaereingang/ 0=Sensoreingang' },
    'Unbekannt-214':     { 'ID':   214, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'MeldungBE01':       { 'ID':   221, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE02':       { 'ID':   222, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE03':       { 'ID':   223, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE04':       { 'ID':   224, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE05':       { 'ID':   225, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE06':       { 'ID':   226, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'Unbekannt-227':     { 'ID':   227, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-228':     { 'ID':   228, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'MeldungBE09':       { 'ID':   229, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE10':       { 'ID':   230, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE11':       { 'ID':   231, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE12':       { 'ID':   232, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE13':       { 'ID':   233, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'Unbekannt-234':     { 'ID':   234, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'MeldungBE15':       { 'ID':   235, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE16':       { 'ID':   236, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'MeldungBE17':       { 'ID':   237, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1=>Meldung bei BE=1/ 0=>Meldung bei BE=0' },
    'WMZHTNT-Tarif':     { 'ID':   244, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'WMZ-Tarifumschaltung HT/NT fuer WMZ #1' },
    'WMZKomStoer#4':     { 'ID':   245, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Kommunikationsstoerung Zaehlerbus WMZ #4 (CO6, Fb10)' },
    'WMZKomStoer#5':     { 'ID':   246, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Kommunikationsstoerung Zaehlerbus WMZ #5 (CO6, Fb10)' },
    'WMZKomStoer#6':     { 'ID':   247, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Kommunikationsstoerung Zaehlerbus WMZ #6 (CO6, Fb10)' },
    'WMZFehlerWMZ#4':    { 'ID':   248, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Fehler WMZ #4 (CO6, Fb10)' },
    'WMZFehlerWMZ#5':    { 'ID':   249, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Fehler WMZ #5 (CO6, Fb10)' },
    'WMZFehlerWMZ#6':    { 'ID':   250, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Fehler WMZ #6 (CO6, Fb10)' },
    'WMZ-Auslesung#4':   { 'ID':   251, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1 = 1xAuslesung WMZ #4 veranlassen' },
    'WMZ-Auslesung#5':   { 'ID':   252, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1 = 1xAuslesung WMZ #5 veranlassen' },
    'WMZ-Auslesung#6':   { 'ID':   253, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': '1 = 1xAuslesung WMZ #6 veranlassen' },
    'SummenBegrenzung':  { 'ID':   254, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Summenbegrenzung Leistung/Durchfluss aller WMZs' },
    'Unbekannt-255':     { 'ID':   255, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-256':     { 'ID':   256, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-257':     { 'ID':   257, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-258':     { 'ID':   258, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-259':     { 'ID':   259, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-260':     { 'ID':   260, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-261':     { 'ID':   261, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-262':     { 'ID':   262, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-263':     { 'ID':   263, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-264':     { 'ID':   264, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-265':     { 'ID':   265, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-266':     { 'ID':   266, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-267':     { 'ID':   267, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-268':     { 'ID':   268, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-269':     { 'ID':   269, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-270':     { 'ID':   270, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-271':     { 'ID':   271, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-272':     { 'ID':   272, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-273':     { 'ID':   273, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-274':     { 'ID':   274, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-275':     { 'ID':   275, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-276':     { 'ID':   276, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-277':     { 'ID':   277, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-278':     { 'ID':   278, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-279':     { 'ID':   279, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-280':     { 'ID':   280, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-281':     { 'ID':   281, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-282':     { 'ID':   282, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-283':     { 'ID':   283, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-284':     { 'ID':   284, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-285':     { 'ID':   285, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-286':     { 'ID':   286, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-287':     { 'ID':   287, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-288':     { 'ID':   288, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-289':     { 'ID':   289, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-290':     { 'ID':   290, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-291':     { 'ID':   291, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-292':     { 'ID':   292, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-293':     { 'ID':   293, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-294':     { 'ID':   294, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-295':     { 'ID':   295, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-296':     { 'ID':   296, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-297':     { 'ID':   297, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-298':     { 'ID':   298, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-299':     { 'ID':   299, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'CO9FB05':           { 'ID':   300, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Externe Vorlaufsoll-Korrektur (Techem/Adapterm)' },
    'CO9FB01':           { 'ID':   301, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'NI1000 Sensoren der Firma SIEMENS' },
    'ZyklRelaisinit':    { 'ID':   302, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Zyklische Relaisinitialisierung' },
    'Fliessdruckschalt': { 'ID':   303, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Fliessdruckschalter' },
    'WirksinnStoeraus':  { 'ID':   304, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_FS', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Wirksinn Stoermeldeausgang BA13 (CO5, Fb07)' },
    'Unbekannt-305':     { 'ID':   305, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Schleichmbin':      { 'ID':   306, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Schleichmenge mittels Binaereingang' },
    'CO9FB08':           { 'ID':   307, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'RK1 als Zubringerkreis' },
    'CO9FB09':           { 'ID':   308, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Modbus-Schreibfreigabe' },
    'FB01BE01imFSR':     { 'ID':   321, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB01: 1=> Meldung in Fehlerstatusregister' },
    'FB02BE02imFSR':     { 'ID':   322, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB02: 1=> Meldung in Fehlerstatusregister' },
    'FB03BE03imFSR':     { 'ID':   323, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB03: 1=> Meldung in Fehlerstatusregister' },
    'FB04BE04imFSR':     { 'ID':   324, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB04: 1=> Meldung in Fehlerstatusregister' },
    'FB05BE05imFSR':     { 'ID':   325, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB05: 1=> Meldung in Fehlerstatusregister' },
    'FB06BE06imFSR':     { 'ID':   326, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB06: 1=> Meldung in Fehlerstatusregister' },
    'Unbekannt-327':     { 'ID':   327, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-328':     { 'ID':   328, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB09BE09imFSR':     { 'ID':   329, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB09: 1=> Meldung in Fehlerstatusregister' },
    'FB10BE10imFSR':     { 'ID':   330, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB10: 1=> Meldung in Fehlerstatusregister' },
    'FB11BE11imFSR':     { 'ID':   331, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB11: 1=> Meldung in Fehlerstatusregister' },
    'FB12BE12imFSR':     { 'ID':   332, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB12: 1=> Meldung in Fehlerstatusregister' },
    'FB13BE13imFSR':     { 'ID':   333, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB13: 1=> Meldung in Fehlerstatusregister' },
    'Unbekannt-334':     { 'ID':   334, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB15BE15imFSR':     { 'ID':   335, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB15: 1=> Meldung in Fehlerstatusregister' },
    'FB16BE16imFSR':     { 'ID':   336, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB16: 1=> Meldung in Fehlerstatusregister' },
    'FB17BE17imFSR':     { 'ID':   337, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB17: 1=> Meldung in Fehlerstatusregister' },
    'BtrnichtAuto':      { 'ID':   997, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'mind. 1 Rk ungleich Auto' },
    'BtrSnichtAuto':     { 'ID':   998, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'mind. 1 Rk ungleich Auto mittels Betriebsschalter' },
    'AutoRk1':           { 'ID':   999, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Zeitabhaengiger Betrieb Rk1' },
    'TagbetriebRk1':     { 'ID':  1000, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Tagbetrieb Rk1' },
    'NachtbetriebRk1':   { 'ID':  1001, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Nachtbetrieb Rk1' },
    'HaltebtrRk1':       { 'ID':  1002, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Haltebetrieb Rk1 (mit CO1, Fb07=1)' },
    'StuetzbtrRk1':      { 'ID':  1003, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Stuetzbetrieb Rk1 (mit CO1, Fb07=1)' },
    'AufheizbtrRk1':     { 'ID':  1004, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Aufheizbetrieb Rk1 (mit CO1, Fb07=1)' },
    'RuecklbegRk1':      { 'ID':  1005, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ruecklauftemperaturbegrenzung Rk1 aktiv' },
    'HeizausRk1':        { 'ID':  1006, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'AT-abhaengige Heizungsabschaltung Rk1 aktiv' },
    'StandbyRk1':        { 'ID':  1007, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Standby-Betrieb Rk1' },
    'FrostschutzRk1':    { 'ID':  1008, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Frostschutzbetrieb Rk1' },
    'Unbekannt-1016':    { 'ID':  1016, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-1017':    { 'ID':  1017, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-1018':    { 'ID':  1018, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB01RF1':           { 'ID':  1024, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB01: Raumfuehler RF1' },
    'FB02AF1':           { 'ID':  1025, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB02: Aussenfuehler AF1' },
    'FB03RueF1Rk1':      { 'ID':  1026, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB03: Ruecklauffuehler RueF1 Rk1' },
    'Unbekannt-1027':    { 'ID':  1027, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB05FBHRk1':        { 'ID':  1028, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB05: Fussbodenheizung Rk1' },
    'Unbekannt-1029':    { 'ID':  1029, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB07OptimierRk1':   { 'ID':  1030, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB07: Optimierung Rk1' },
    'FB08AdaptRk1':      { 'ID':  1031, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB08: Adaption Rk1' },
    'FB09KurzztAdRk1':   { 'ID':  1032, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB09: Kurzzeitadaption Rk1' },
    'FB10UPManagmt':     { 'ID':  1033, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB10: Pumpenmanagement Schaltverh BA13 (bis V1.30)' },
    'FB114PHKLRk1':      { 'ID':  1034, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB11: 4-Punkte-Kennlinie Rk1' },
    'FB123PktRegRk1':    { 'ID':  1035, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB12: Regelungsart 3-Pkt (Rk1) / 0...10V (Y1)' },
    'FB13BegxdRk1':      { 'ID':  1036, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB13: Begrenzung d. Regelabweichung AUF-Signal Rk1' },
    'FB14FreigRk1':      { 'ID':  1037, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB14: Freigabe Rk1 an Eingang BE15' },
    'FB15Bedarf':        { 'ID':  1038, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB15: Bedarfsverarbeitung in Rk1' },
    'FB1610VBedarf':     { 'ID':  1039, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB16: Bedarfsverarbeitung 0-10V in Rk1 (Kl. 17/19)' },
    'FB17binBedarf':     { 'ID':  1040, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB17: Bedarfsverarbeitung binaer in Rk1 (Kl. 17/18)' },
    'FB18maxVL-Soll':    { 'ID':  1041, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB18: Max. Vorlaufsollwert mittels 0-10V anfordern' },
    'FB19VL-SollFolg':   { 'ID':  1042, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB19: Max. Vorlaufsollwert in Folge anfordern' },
    'FB20ExtWaermean':   { 'ID':  1043, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB20: Externe Waermeanforderung bei Unterversorgung' },
    'Unbekannt-1044':    { 'ID':  1044, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'AutoRk2':           { 'ID':  1199, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Zeitabhaengiger Betrieb Rk2' },
    'TagbetriebRk2':     { 'ID':  1200, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Tagbetrieb Rk2' },
    'NachtbetriebRk2':   { 'ID':  1201, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Nachtbetrieb Rk2' },
    'HaltebtrRk2':       { 'ID':  1202, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Haltebetrieb Rk2 (mit CO2, Fb07=1)' },
    'StuetzbtrRk2':      { 'ID':  1203, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Stuetzbetrieb Rk2 (mit CO2, Fb07=1)' },
    'AufheizbtrRk2':     { 'ID':  1204, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Aufheizbetrieb Rk2 (mit CO2, Fb07=1)' },
    'RuecklbegRk2':      { 'ID':  1205, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ruecklauftemperaturbegrenzung Rk2 aktiv' },
    'HeizausRk2':        { 'ID':  1206, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'AT-abhaengige Heizungsabschaltung Rk2 aktiv' },
    'StandbyRk2':        { 'ID':  1207, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Standby-Betrieb Rk2' },
    'FrostschutzRk2':    { 'ID':  1208, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Frostschutzbetrieb Rk2' },
    'Unbekannt-1211':    { 'ID':  1211, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-1212':    { 'ID':  1212, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-1216':    { 'ID':  1216, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-1217':    { 'ID':  1217, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-1218':    { 'ID':  1218, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB01RF2':           { 'ID':  1224, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB01: Raumfuehler RF2' },
    'FB02AF2':           { 'ID':  1225, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB02: Aussenfuehler AF2' },
    'FB03RueF2Rk2':      { 'ID':  1226, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB03: Ruecklauffuehler RueF2 Rk2' },
    'FB05FBHRk2':        { 'ID':  1227, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB05: Fussbodenheizung Rk2' },
    'Unbekannt-1228':    { 'ID':  1228, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-1229':    { 'ID':  1229, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB07OptimierRk2':   { 'ID':  1230, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB07: Optimierung Rk2' },
    'FB08AdaptRk2':      { 'ID':  1231, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB08: Adaption Rk2' },
    'FB09KurzztAdRk2':   { 'ID':  1232, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB09: Kurzzeitadaption Rk2' },
    'Unbekannt-1233':    { 'ID':  1233, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'FB114PHKLRk2':      { 'ID':  1234, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB11: 4-Punkte-Kennlinie Rk2' },
    'FB123PktRegRk2':    { 'ID':  1235, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB12: Regelungsart 3-Pkt (Rk2) / 0...10V (Y2)' },
    'FB13BegxdRk2':      { 'ID':  1236, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB13: Begrenzung d. Regelabweichung AUF-Signal Rk2' },
    'FB14FreigRk2':      { 'ID':  1237, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB14: Freigabe Rk2 an Eingang BE16' },
    'AutoTW':            { 'ID':  1799, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Zeitabhaengiger Betrieb Trinkwasser' },
    'ThermDesTW':        { 'ID':  1800, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Thermische Desinfektion Trinkwasserkreis aktiv' },
    'VorrangTW':         { 'ID':  1801, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Vorrangbetrieb Trinkwasserkreis aktiv' },
    'MaxLadetempbgTW':   { 'ID':  1802, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Maximale Ladetemperaturbegrenzung aktiv' },
    'RuecklbegTW':       { 'ID':  1803, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Ruecklauftemperaturbegr. Trinkwasserkreis aktiv' },
    'StandbyTW':         { 'ID':  1804, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Standby-Betrieb Trinkwasser' },
    'FrostschutzTW':     { 'ID':  1805, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Frostschutzbetrieb Trinkwasser' },
    'ZwangsladTW':       { 'ID':  1806, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Zwangsladung Trinkwasserspeicher' },
    'SolarUPTW':         { 'ID':  1807, 'Lesen': 0, 'Art': 'ro', 'Typ': 'Liste_NJ', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Solarkreis-Umwaelzpumpe aktiv' },
    'SF2anstattSF1':     { 'ID':  1808, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Zwangsladung durch Umschaltung von SF1 auf SF2' },
    'FB01SF1':           { 'ID':  1824, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB01: Speicherfuehler SF1' },
    'FB02SF2':           { 'ID':  1825, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB02: Speicherfuehler SF2' },
    'FB03RueF2':         { 'ID':  1826, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB03: Ruecklauffuehler RueF2' },
    'FB04StroemSensor':  { 'ID':  1827, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB04: Wasserstroemungssensor' },
    'FB05VF4':           { 'ID':  1828, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB05: Vorlauffuehler VF4' },
    'FB06ParallelTW':    { 'ID':  1829, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB06: Pumpenparallellauf' },
    'FB07Zwischenhzg':   { 'ID':  1830, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB07: Zwischenheizbetrieb' },
    'FB08VorrangInv':    { 'ID':  1831, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB08: Vorrang durch Inversbetrieb' },
    'FB09VorrangAbs':    { 'ID':  1832, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB09: Vorrang durch Absenkbetrieb' },
    'FB10ZPinWT':        { 'ID':  1833, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB10: ZP in Waermetauscher eingebunden' },
    'FB11ZPbeimLaden':   { 'ID':  1834, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB11: Betrieb der ZP bei Speicherladung' },
    'FB123PktRegTW':     { 'ID':  1835, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB12: Regelungsart 3-Pkt (Rk2) / 0...10V (Y2) TW' },
    'FB13BegRegdiff':    { 'ID':  1836, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB13: Begrenzung der Regelabweichung AUF-Signal TW' },
    'FB14ThermDes':      { 'ID':  1837, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB14: Thermische Desinfektion' },
    'FB15SLPabhRueF':    { 'ID':  1838, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB15: SLP ein in Abhaengigkeit der Ruecklauftemp' },
    'FB16BedPrio':       { 'ID':  1839, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB16: Externer Bedarf hat Prioritaet' },
    'FB17BA12Desinf':    { 'ID':  1840, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB17: BA12 waehrend thermischer Desinfektion ein' },
    'FB18BA12TWAnf':     { 'ID':  1841, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB18: BA12 waehrend Trinkwasseranforderung ein' },
    'FB19ZPSFumsch':     { 'ID':  1842, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB19: Zeitprogrammgest. Speicherfuehlerumschaltung' },
    'FB20Durchgngreg':   { 'ID':  1843, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB20: TW-Kreis nachgeregelt mit Durchgangsventil' },
    'FB21DrehzLadep':    { 'ID':  1844, 'Lesen': 0, 'Art': 'rw', 'Typ': 'Liste_IA', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'FB21: Drehzahlregelung der Ladepumpe' },
    'Unbekannt-9899':    { 'ID':  9899, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9900':    { 'ID':  9900, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9901':    { 'ID':  9901, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9902':    { 'ID':  9902, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9903':    { 'ID':  9903, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9904':    { 'ID':  9904, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9905':    { 'ID':  9905, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9906':    { 'ID':  9906, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9907':    { 'ID':  9907, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9908':    { 'ID':  9908, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9909':    { 'ID':  9909, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-9910':    { 'ID':  9910, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-55999':   { 'ID': 55999, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-56000':   { 'ID': 56000, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-56001':   { 'ID': 56001, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-56002':   { 'ID': 56002, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-56003':   { 'ID': 56003, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-56004':   { 'ID': 56004, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-56005':   { 'ID': 56005, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-56006':   { 'ID': 56006, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' },
    'Unbekannt-65534':   { 'ID': 65534, 'Lesen': 0, 'Art': 'ro', 'Typ': '???', 'Buswert': 0, 'Wert': 0, 'Einheit': '', 'Name': 'Unbekannt' }
}
