# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Abfrage der Abfahrten in Stationen der Münchner Verkehrsbetriebe (MVG)'
        en: 'Retrieval of departure times of stations within the Münchner Verkehrsbetriebe (MVG)'
    maintainer: psilo909
    tester: '?'                    # Who tests this plugin?
    state: ready
    keywords: public transport, departure times, Munich, München
    documentation: http://smarthomeng.de/user/plugins_doc/config/mvg_live.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1108867-neues-plugin-mvg_live

    version: 1.6.0                 # Plugin version
    sh_minversion: 1.5             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: MVG_Live            # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml

item_attributes: NONE
    # Definition of item attributes defined by this plugin

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:

    get_station_departures:
        type: list(dict)
        description:
            de: "Gibt ein Array von DICTs mit Infos Verkehrverbindungen der Münchner Verkehrsbetriebe (MVG) zurück. Keys: 'productsymbol', 'product', 'linesymbol', 'time', 'direction', 'linename', 'productsymbolurl', 'linesymbolurl', 'destination'."
            en: "Returns an Array of DICTs with information on lines of the Münchner Verkehrsbetriebe (MVG). Keys: 'productsymbol', 'product', 'linesymbol', 'time', 'direction', 'linename', 'productsymbolurl', 'linesymbolurl', 'destination'."

        parameters:
            station:
                type: str
                description:
                    de: "Name der Haltestelle. Schauen Sie auf der MVG live Webseite nach gültigen Namen."
                    en: "Name of the stop or station. Visit the MVG live web site to find valid names."

