# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Abfrage der Abfahrten in Stationen der Münchner Verkehrsbetriebe (MVG)'
        en: 'Retrieval of departure times of stations within the Münchner Verkehrsbetriebe (MVG)'
    maintainer: psilo909
    tester: '?'                    # Who tests this plugin?
    state: ready
    keywords: public transport, departure times, Munich, München
    documentation: http://smarthomeng.de/user/plugins_doc/config/mvg_live.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1108867-neues-plugin-mvg_live

    version: 1.5.0.2               # Plugin version
    sh_minversion: 1.5             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: MVG_Live            # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml

item_attributes: NONE
    # Definition of item attributes defined by this plugin

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:

    get_station_departures:
        type: list(dict)
        description:
            de: "Gibt ein Array von DICTs mit Infos Verkehrverbindungen der Münchner Verkehrsbetriebe (MVG) zurück. Keys: 'productsymbol', 'product', 'linesymbol', 'time', 'direction', 'linename', 'productsymbolurl', 'linesymbolurl', 'destination'."
            en: "Returns an Array of DICTs with information on lines of the Münchner Verkehrsbetriebe (MVG). Keys: 'productsymbol', 'product', 'linesymbol', 'time', 'direction', 'linename', 'productsymbolurl', 'linesymbolurl', 'destination'."

        parameters:
            station:
                type: str
                description:
                    de: "Name der Haltestelle. Schauen Sie auf der MVG live Webseite nach gültigen Namen."
                    en: "Name of the stop or station. Visit the MVG live web site to find valid names."

            timeoffset:
                type: int
                description:
                    de: "Keine Verbindungen in weniger als dieser Zeitdauer anzeigen. Sinnvoll, wenn man einige Minuten von der Haltstelle entfernt ist. Default: 0"
                    en: "Do not display connections departing sooner than this number of minutes. Useful if you are a couple of minutes away from the stop. Default: 0"

            entries:
                type: int
                description:
                    de: "Anzahl der Einträge, die geholt werden sollen. Default: 10"
                    en: "Number of entries to retrieve. Default: 10."

            ubahn:
                type: bool
                description:
                    de: "Falls 'False', keine U-Bahn Abfahrtzeiten anzeigen. Default: True."
                    en: "If 'False', do not display U-Bahn (subway) departures. Default: True."

            tram:
                type: bool
                description:
                    de: "Falls 'False', keine Tram Abfahrtzeiten anzeigen. Default: True."
                    en: "If 'False', do not display tram departures. Default: True."

            bus:
                type: bool
                description:
                    de: "Falls 'False', keine Bus Abfahrtzeiten anzeigen. Default: True."
                    en: "If 'False', do not display bus departures. Default: True."

            sbahn:
                type: bool
                description:
                    de: "Falls 'False', keine S-Bahn Abfahrtzeiten anzeigen. Default: True."
                    en: "If 'False', do not display S-Bahn (suburban train) departures. Default: True."
