plugin:
    type: interface
    description:
        de: 'Plugin zur Helios EC x00 Pro / Vallox xx SE Ansteuerung'
        en: 'Plugin for Helios EC x00 Pro / Vallox xx SE control'
    maintainer: 'Tom Bombadil'
    tester: '-'
    keywords: 'helios vallox ventilation'
    documentation: https://github.com/Tom-Bom-badil/helios/wiki
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/40092-erweiterung-helios-vallox-plugin
    version: 1.4.2                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
    multi_instance:  False         # plugin supports multi instance
    classname: 'Helios'            # class containing the plugin
# parameters:                        # Definition of parameters to be configured in etc/plugin.yaml
#    tty:
#        type: str
#        default: '/dev/ttyUSB0'
#        description:
#            de: 'Port für die Kommunikation'
#            en: 'Port for communication'
#    cycle: 'Polling interval in seconds'
#        type: num
#        default: 300
#        description:
#            de: 'Abfrage-Intervall'
#            en: 'Polling interval'
# item_attributes:
