plugin:
    type: interface
    description:
        de: 'Plugin zur Helios EC x00 Pro / Vallox xx SE Ansteuerung'
        en: 'Plugin for Helios EC x00 Pro / Vallox xx SE control'
    maintainer: 'Tom Bombadil'
    tester: '-'
    state: ready
    keywords: 'helios vallox ventilation'
    documentation: https://github.com/Tom-Bom-badil/helios/wiki
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/40092-erweiterung-helios-vallox-plugin
    version: 1.4.2
    sh_minversion: 1.1
    multi_instance:  False
    restartable: unknown
    classname: 'Helios'

parameters:
    tty:
        type: str
        default: '/dev/ttyUSB0'
        description:
            de: 'Port für die Kommunikation'
            en: 'Port for communication'

    cycle:
        type: int                   # used to be num until 1.6, then caused error
        default: 60
        description:
            de: 'Abfrage-Intervall in Sekunden'
            en: 'Polling interval in seconds'


item_attributes:
    helios_var:
        type: str
        description:
            de: 'Keine Beschreibung angegeben. (Bitte in den Support Thread im SmatHomeNG Forum schauen)'
            en: 'No description given (Please visit the support thread in the SmartHomeNG Forum)'

    e0:  # These attributes have been used by the plugin for 9 years - included only to prevent startup errors
        type: str
        description:
            de: 'Kein Fehler, Anlage arbeitet normal'
            en: 'No error, device is working properly'

    e1:
        type: str
        description:
            de: 'Nicht dokumentierter Fehler 1'
            en: 'Unknown error 1'

    e2:
        type: str
        description:
            de: 'Nicht dokumentierter Fehler 2'
            en: 'Unknown error 2'

    e3:
        type: str
        description:
            de: 'Nicht dokumentierter Fehler 3'
            en: 'Unknown error 3'

    e4:
        type: str
        description:
            de: 'Nicht dokumentierter Fehler 4'
            en: 'Unknown error 4'

    e5:
        type: str
        description:
            de: '5:Zuluftsensor defekt'
            en: 'Supply air sensor defect'

    e6:
        type: str
        description:
            de: 'CO2-Alarm'
            en: 'CO2 alarm'

    e7:
        type: str
        description:
            de: 'Außenluftsensor defekt'
            en: 'Outside air sensor defect'

    e8:
        type: str
        description:
            de: 'Abluftsensor defekt'
            en: 'Extract air sensor defect'

    e9:
        type: str
        description:
            de: 'Frostwarnung - Außenluft <0°C'
            en: 'Frost warning - outside air <0°C'

    e10:
        type: str
        description:
            de: 'Fortluftsensor defekt'
            en: 'Exhaust air sensor defect'
            
    filter_warning:
        type: str
        description:
            de: 'Filter wechseln'
            en: 'Exchange filter'

item_structs: NONE
plugin_functions: NONE
logic_parameters: NONE
