# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin für den Rapberry Pi. Erlaubt den einfachen Zugriff auf 1-Wire Sensoren. Getestet mit Raspberry Pi B und dem Temperatursensor DS18B20'
        en: 'Plugin developed for the Raspberry Pi. It allows easy access to 1-Wire sensors. Tested with the Raspberry Pi B and the temperature sensor DS18B20'
        fr: 'Support de 1-Wire à travers Raspberry Pi sur SmartHomeNG v1.5 et plus'

    maintainer: bmxp
    tester: sisamiwe, ElektroRudi   # Who tests this plugin?
    state: develop                  # change to ready when done with development
    keywords: 1wire onewire raspberry pi dallas temperature sensor
    documentation: https://github.com/smarthomeNG/plugins/rpi1wire/Readme.md        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1451916-support-thread-für-rpi1wire-plugin

    version: 1.6.0                  # Plugin version
    sh_minversion: 1.5              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: True
    classname: Rpi1Wire             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    cycle:
        type: int
        valid_min: 1
        default: 120
        description:
            de: 'Zeitlicher Abstand zwischen zwei Abfragen des OneWire'
            en: 'Time between two queries of onewire'
    dirname:
        type: str
        default: '/sys/bus/w1/devices'
        description:
            de: 'Verzeichnis des Onewire'
            en: 'Directory of onewire provided'


item_attributes:
    rpi1wire_id:
        type: str
        description:
            de: 'Sensoradresse im Format xx-yyyyyyyyyyyy (Bitte darauf achten, dass bei rein numerischen Sensoradressen diese in '' eingeschlossen werden müssen) oder ein Alias'
            en: 'Sensor address in xx-yyyyyyyyyyyy format (Please note: If the sensor address is numerical, it has to be enclosed in quotes) or an alias'
            fr: 'Adresse du capteur au format xx-yyyyyyyyyyyy'

    rpi1wire_update:
        type: bool
        description:
            de: 'Started bei Triggerung ein Update der Sensorliste'
            en: 'Rereads the sensor list after being triggered'

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

