# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: system                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Executor Plugin für SmartHomeNG v1.5 und höher'
        en: 'Executor plugin for SmartHomeNG v1.5 and up'
    maintainer: bmxp
#    tester:                         # Who tests this plugin?
    state: develop                  # change to ready when done with development
    keywords: Python eval code
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1425152-support-thread-plugin-executor

    version: 0.0.2                  # Plugin version
    sh_minversion: 1.4              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: True
    classname: Executor             # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)

item_attributes:  NONE
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

