# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: system                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ausführen von Python Statements im Kontext von SmartHomeNG v1.5 und höher'
        en: 'Execute Python statements in the context of SmartHomeNG v1.5 and up'
    maintainer: bmxp
    tester: nobody                  # Who tests this plugin?
    state: ready                    # change to ready when done with development
    keywords: Python eval exec code test
    documentation: https://www.smarthomeng.de/user/plugins/executor/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1425152-support-thread-plugin-executor

    version: 1.1.0                  # Plugin version
    sh_minversion: 1.9              # minimum shNG version to use this plugin
    #sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    py_minversion: 3.8              # minimum Python version to use for this plugin, use f-strings for debug
    #py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: True
    classname: Executor             # class containing the plugin

parameters:
    scripts:
        type: str
        default: executor_scripts
        description:
            de: 'relative Pfadangabe unterhalb *var* wo im Bedarfsfall die Skripte für das Executor Plugin abgelegt werden'
            en: 'relative path below *var* to script files for executor plugin if needed'
    script_entries:
        type: int
        default: 6
        valid_min: 0
        valid_max: 50
        description:
            de: 'Maximale Anzahl der Zeilen in der Listbox für Skripte. Bei Angabe von 0 wird die Listbox zur Dropdown Liste.'
            en: 'Maximum number of lines in listbox für scripts. If 0 is given the listbox will turn into a dropdown list.'

item_attributes:  NONE
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
