# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Über das CO2Meter Plugin können Daten aus dem Dostmann TFA AirCO2ntrol CO2 Messgerät via USB abgerufen werden.'
        en: 'The CO2Meter Plugin allows to access a Dostmann TFA Dostmann AirCO2ntrol device via its raw USB data.'
    maintainer: psilo909
    tester:
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1165010-supportthread-f%C3%BCr-das-co2meter-plugin

    version: 1.3.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: CO2Meter            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    device:
        type: str
        mandatory: False
        description:
            de: 'Pfad zu den rohen USB Daten (optional, default: /dev/hidraw0)'
            en: 'Path to raw usb data (optional, default: /dev/hidraw0)'

    time_sleep:
        type: str
        mandatory: False
        description:
            de: 'Wartezeit in Sekundento nach jeder Datenanfrage (optional, default: 5)'
            en: 'Seconds to wait after each request (optional, default: 5)'

item_attributes:
    # Definition of item attributes defined by this plugin
    co2meter_data_type:
        type: str
        mandatory: True
        description:
            de: 'Der auszulesende Datentyp, "temperature" oder "co2"'
            en: 'The data type to read: "temperature" or "co2"'
