# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)

    description:
        de: 'Harmony Hub plugin **seit SmartHomeNG v1.3**'
        en: 'Harmony hub plugin'

    maintainer: pfischi
    tester: pfischi
    state: ready
    documentation: https://github.com/smarthomeNG/plugins/blob/develop/harmony/README.md
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1046500-harmony-hub-plugin

    version: 1.4.1                 # Plugin version
    sh_minversion: 1.4             # minimum shNG version to use this plugin
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: Harmony             # class containing the plugin

parameters:
  harmony_ip:
    type: ipv4
    description:
      de: "Harmony Hub IP-Adresse"
      en: "Harmony hub ip address"
    mandatory: true

  harmony_port:
    type: int
    description:
      de: "(optional) Harmony Hub Port. Default: 5222"
      en: "(optional) Harmony hub port. Default: 5222"
    default: 5222
    valid_min: 1
    valid_max: 65535

  sleekxmpp_debug:
    type: bool
    description:
      de: "(optional) Debug-Ausgaben der sleekxmpp-Klasse. Default: false"
      en: "(optional) Debug print of the sleekxmpp class. Default: false"
    default: false


item_attributes: NONE
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
