# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung der Nokia Health API mit Oauth2'
        en: 'Usage of the nokia health api with oauth2'
    maintainer: 'psilo909'
    tester: 'psilo909'
    keywords: health
    documentation: 'http://smarthomeng.de/user/plugins_doc/config/nokia_health.html'
    support: 'https://knx-user-forum.de/forum/supportforen/smarthome-py/1141179-nokia-health-plugin'

    version: 1.5.3                 # Plugin version
    sh_minversion: 1.4c            # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    classname: NokiaHealth         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    access_token:
        type: str
        mandatory: True
        description:
            de: 'Access-Token, via nokia Script von https://github.com/orcasgit/python-nokia'
            en: 'Access token, retrieved via script from https://github.com/orcasgit/python-nokia'

    token_expiry:
        type: str
        mandatory: True
        description:
            de: 'Token expiry, via nokia Script von https://github.com/orcasgit/python-nokia'
            en: 'Token expiry, retrieved via script from https://github.com/orcasgit/python-nokia'

    token_type:
        type: str
        mandatory: True
        description:
            de: 'Token-Type, via nokia Script von https://github.com/orcasgit/python-nokia'
            en: 'Token type, retrieved via script from https://github.com/orcasgit/python-nokia'

    refresh_token:
        type: str
        mandatory: True
        description:
            de: 'Refresh-Token, via nokia Script von https://github.com/orcasgit/python-nokia'
            en: 'Refresh token, retrieved via script from https://github.com/orcasgit/python-nokia'

    user_id:
        type: str
        mandatory: True
        description:
            de: 'Nokia Health User ID (steht in der URL, wenn man als nomraler User einloggt)'
            en: 'Nokia Health User ID (can be found in the URL when you log in)'

    client_id:
        type: str
        mandatory: True
        description:
            de: 'Client ID von https://account.health.nokia.com/partner/dashboard_oauth2'
            en: 'Client ID from https://account.health.nokia.com/partner/dashboard_oauth2'

    consumer_secret:
        type: str
        default: 300
        mandatory: True
        description:
            de: 'Consumer-Geheimnis von https://account.health.nokia.com/partner/dashboard_oauth2'
            en: 'Consumer secret from https://account.health.nokia.com/partner/dashboard_oauth2'

    cycle:
        type: int
        default: 300
        description:
            de: 'Dieser Parameter muss normalerweise nicht angegeben werden. Er erlaubt es die Update-Frquenz anzupassen (Standard: alle 600 Sekunden). Mit dem Standardwert werden die Daten von Nokia Health alle 5 Minuten aktualisiert.'
            en: "This parameter usually doesn't have to be specified. It allows to change the update frequency (cycle every 300 seconds). As a standard, the plugin updates the Nokia Health data every 5 minutes."


item_attributes:
    # Definition of item attributes defined by this plugin

    nh_type:
        type: str
        description:
            de: 'nh_type kann folgende Werte annehmen: weight, height (wird von Nokia Health nur beim allerersten Messwert geliefert), bmi, bmi_text, fat_ratio, fat_free_mass, fat_mass_weight, heart_pulse, last_update.'
            en: 'nh_type can be out of the following values: weight, height (wird von Nokia Health nur beim allerersten Messwert geliefert), bmi, bmi_text, fat_ratio, fat_free_mass, fat_mass_weight, heart_pulse, last_update.'