# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Wetterdaten über darksky.net.'
        en: 'Weather data via darksky.net.'
    maintainer: psilo909
    tester: psilo909
    state: 'qa-passed'
#    keywords: iot xyz
    documentation: 'https://www.smarthomeng.de/user/plugins/darksky/user_doc.html'
    support: 'https://knx-user-forum.de/forum/supportforen/smarthome-py/1244744-neues-plugin-wetterdaten-via-darksky-net-forecast-io'
    keywords: weather
    version: 1.5.0.1              # Plugin version
    sh_minversion: 1.4c           # minimum shNG version to use this plugin
#    sh_maxversion:               # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True          # plugin supports multi instance
    restartable: unknown
    classname: DarkSky            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    key:
        type: str
        mandatory: True
        description:
            de: 'Persönlicher API Key für darksky.net. Registrierung unter https://darksky.net/dev.'
            en: 'Your own personal API key for darksky.net. For your own key register to https://darksky.net/dev.'
    latitude:
        type: str
        mandatory: False
        default: ''
        description:
            de: 'Latitude des Ortes, für den die Wetterdaten abgerufen werden sollen. Default: SmartHomeNG Settings'
            en: 'Latitude for the location, of which weather data is requested. Default: SmartHomeNG Settings'
    longitude:
        type: str
        mandatory: False
        default: ''
        description:
            de: 'Longitude des Ortes, für den die Wetterdaten abgerufen werden sollen. Default: SmartHomeNG Settings.'
            en: 'Longitude for the location, of which weather data is requested. Default: SmartHomeNG Settings.'
    lang:
        type: str
        mandatory: False
        default: 'de'
        description:
            de: 'Sprache der zurückgelieferten Daten. Mögliche Werte siehe https://darksky.net/dev/docs.'
            en: 'Language of the data to be returned. Possible values see https://darksky.net/dev/docs.'
    units:
        type: str
        mandatory: False
        default: 'auto'
        description:
            de: 'Einheit der zurückgelieferten Daten. Mögliche Werte siehe https://darksky.net/dev/docs.'
            en: 'Unit of the returned data. Possible values see https://darksky.net/dev/docs.'
    cycle:
        type: int
        mandatory: False
        default: 300
        description:
            de: '(optional) Zeit zwischen zwei Updateläufen. Default ist 300 Sekunden.'
            en: '(optional) Time period between two update cycles. Default is 300 seconds.'
    
item_attributes:
    # Definition of item attributes defined by this plugin
    ds_matchstring:
        type: str
        mandatory: True
        description:
            de: 'Matchstring basierend auf der Response des "Forecast Request" aus https://darksky.net/dev/docs (Example Request), bspw. "currently/temperature". Ausnahmen: Im Fall von "alerts" wird ein Item vom Typ "list" benötigt, der Wert "alerts_string" schreibt die Alerts-Liste in einen HTML String. Das Array in "flags/sources" wird in ein "str" Item gemerged.'
            en: 'Matchstring according to the response of the "forecast request" described in https://darksky.net/dev/docs (Example Request), e.g. "currently/temperature". Exceptions: In case of "alerts" an item of type "list" will be filled with raw data, the value "alerts_string" creates a html string with alerts data. The array "flags/sources" will be merged to a string.'

plugin_functions: NONE
    # Definition of function interface of the plugin

