# Metadata for the Xiaomi Saugroboter
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Zugriff und Steuern eines Xiaomi Saugroboter'
        en: 'Control the Xioami Vacuum Robot'
    maintainer: Bonze
    state: develop 
    tester: Bonze, henfri
    keywords: communication, iot
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1453597-support-thread-f%C3%BCr-xiaomi-saugroboter-plugin
# documentation: 
    version: 1.0.0             # Plugin version
    sh_minversion: 1.4           # minimum shNG version to use this plugin
    multi_instance: False          # plugin supports multi instance
    classname: Robvac                # class containing the plugin
    restartable: unknown

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)
    #plugin_functions: NONE

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
    #logic_parameters: NONE

# Definition of parameters to be configured in etc/plugin.yaml
parameters:
    ip:
        type: ipv4
        default: mandatory
        description:
            de: 'IP Adresse des Saug-Roboters '
            en: 'IP Adress of the Vakuum Cleaner'
    read_cycle:
        type: int
        default: 12
        description:
            de: 'Standart Zyklus zum Lesen der Paramter vom Gerät'
            en: 'Default cycle time for reading'
    token:
        type: str
        default: mandatory
        description:
            de: 'Token für die Kommunikation'
            en: 'Token for Communication'  
        
item_structs: #saugroboter
saugroboter:
    live:
        name: 'Aktuelle Werte des Saugroboters'
        batterie_status:
            name: 'Batterie Status'
            type: num
            robvac: 'batt'
        reinigt:
            name: 'aktuell am reinigen?'
            type: bool
            robvac: 'state'
        zustand:
            name: 'Betriebszustand'
            type: str
            robvac: 'status'
        aktiv:
            type: bool
            robvac: 'aktiv'
        flaeche:
            name: 'gereinigte Fläche'
            type: num
            robvac: 'area'
        gereinigt:
            type: num
            robvac: 'gereinigt'
        reinigungszeit:
            type: num
            robvac: 'cleantime'
        carpetmode_high:
            type: num
            robvac: 'carpetmode_high'
        carpetmode_integral:
            type: num
            robvac: 'carpetmode_integral'
        carpetmode_low:
            type: num
            robvac: 'carpetmode_low'
        carpetmode_enabled:
            type: num
            robvac: 'carpetmode_enabled'
        carpetmode_stall_time:
            type: num
            robvac: 'carpetmode_stall_time'
        errorcode:
            type: num
            robvac: 'error'
        error:
            type: bool
            robvac: 'is_error'
        dnd_status:
            type: bool
            robvac: 'dnd_status'
        dnd_start:
            type: foo
            robvac: 'dnd_start'
        dnd_end:
            type: foo
            robvac: 'dnd_end'
        zonen_reinigung:
            type: bool
            robvac: 'zone_cleaning'
        pausiert:
            type: bool
            robvac: 'pause'
        segment_status:
            type: bool
            robvac: 'segment_status'
    befehl:
        name: 'Befehle zum Saugroboter'
        start:
            type: bool
            robvac: 'set_start'
        stop:
            type: bool
            robvac: 'set_stop'
        pause:
            type: bool
            robvac: 'set_pause'
        basis:
            type: bool
            robvac: 'set_home'
        spot_cleaner:
            type: bool
            robvac: 'set_spot'
        find:
            type: bool
            robvac: 'set_find'
        reset_filtertimer:
            type: bool
            robvac: 'reset_filtertimer'
        disable_dnd:
            type: bool
            robvac: 'disbale_dnd'
        set_dnd:
            type: list
            robvac: 'set_dnd'
        goto:
            type: list
            robvac: 'go_to'
    statistik:
        name: 'Reinigungsstatistiken'
        anzahl_reinigungen:
            type: num
            robvac: 'clean_total_count'
        gereinigte_flaeche:
            type: num
            robvac: 'clean_total_area'
        gesamtlaufzeit:
            type: num
            robvac: 'clean_total_duration'
        reinigungsids:
            type: foo
            robvac: 'clean_ids'
        reinigungsdetails0:
            type: foo
            robvac: 'clean_details_last0'
            flaeche:
                name: 'gereinigte Fläche'
                type: num
                robvac: 'last0_area'
            complete:
                type: bool
                robvac: 'last0_complete'
            reinigungszeit:
                type: num
                robvac: 'last0_duration'
            start_date:
                type: str
                robvac: 'last0_start_date'
            start_time:
                type: str
                robvac: 'last0_start_time'
            end_date:
                type: str
                robvac: 'last0_end_date'
            end_time:
                type: str
                robvac: 'last0_end_time'
        reinigungsdetails1:
            type: foo
            robvac: 'clean_details_last1'
            flaeche:
                name: 'gereinigte Fläche'
                type: num
                robvac: 'last1_area'
            complete:
                type: bool
                robvac: 'last1_complete'
            reinigungszeit:
                type: num
                robvac: 'last1_duration'
            start_date:
                type: str
                robvac: 'last1_start_date'
            start_time:
                type: str
                robvac: 'last1_start_time'
            end_date:
                type: str
                robvac: 'last1_end_date'
            end_time:
                type: str
                robvac: 'last1_end_time'
        reinigungsdetails2:
            type: foo
            robvac: 'clean_details_last2'
            flaeche:
                name: 'gereinigte Fläche'
                type: num
                robvac: 'last2_area'
            complete:
                type: bool
                robvac: 'last2_complete'
            reinigungszeit:
                type: num
                robvac: 'last2_duration'
            start_date:
                type: str
                robvac: 'last2_start_date'
            start_time:
                type: str
                robvac: 'last2_start_time'
            end_date:
                type: str
                robvac: 'last2_end_date'
            end_time:
                type: str
                robvac: 'last2_end_time'
        reinigungsdetails3:
            type: foo
            robvac: 'clean_details_last3'
            flaeche:
                name: 'gereinigte Fläche'
                type: num
                robvac: 'last3_area'
            complete:
                type: bool
                robvac: 'last3_complete'
            reinigungszeit:
                type: num
                robvac: 'last3_duration'
            start_date:
                type: str
                robvac: 'last3_start_date'
            start_time:
                type: str
                robvac: 'last3_start_time'
            end_date:
                type: str
                robvac: 'last3_end_date'
            end_time:
                type: str
                robvac: 'last3_end_time'
    einstellungen:
        name: 'Einstellbare Parameter'
        luefter_speed:
            type: num
            robvac: 'fanspeed'
        teppichmodus:
            type: bool
            robvac: 'carpet_mode'
        vol:
            type: num
            robvac: 'vol'
        dnd:
            type: bool
            robvac: 'dnd_onoff'
        serial:
            type: str
            robvac: 'serial'
        timezone:
            type: str
            robvac: 'timezone'
        timer:
            type: foo
            robvac: 'timer'
    stundenzaehler:
        buerste_seite:
            type: num
            robvac: 'side_brush'
        buerste_seite_verbleibend:
            type: num
            robvac: 'side_brush_left'
        buerste_haupt:
            type: num
            robvac: 'main_brush'
        buerste_haupt_verbleibend:
            type: num
            robvac: 'main_brush_left'
        filter:
            type: num
            robvac: 'filter'
        filter_verbleibend:
            type: num
            robvac: 'filter_left'
        sensor_reinigen:
            type: num
            robvac: 'sensor_dirty'
        sensor_reinigen_verbleibend:
            type: num
            robvac: 'sensor_dirty_left'
