# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: "Anbindung an eine UPS über den NUT daemon

            Mehr über NUT unter http://networkupstools.org/"
        en: "This plugin is connecting to NUT daemon and can be used to read ups variables.

            The primary goal of the Network UPS Tools (NUT) project is to provide support for Power Devices, \
            such as Uninterruptible Power Supplies, Power Distribution Units, Automatic Transfer Switch, Power Supply \
            Units and Solar Controllers.

            The plugin can be used standalone to list available variables using command `upsc your_ups_name`. \
            More about NUT: http://networkupstools.org/"
    maintainer: 4d4mu
#    tester:                        # Who tests this plugin?
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.3.0.1               # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: NUT                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
#  def __init__(self, sh, ups, cycle = 60, host = 'localhost', port = 3493, timeout = 5):
    ups:
        type: str
        description:
            de: "Name of the ups"
            en: "ups name"

    cycle:
        type: int
        default: 60
        description:
            de: "Lese-Zyklus"
            en: "read cycle"

    host:
        type: str
        default: 'localhost'
        description:
            de: "Host des ups Daemons"
            en: "ups daemon host"

    port:
        type: int
        default: 3493
        valid_min: 0
        valid_max: 65535
        description:
            de: "Port des ups Daemons"
            en: "ups daemon port"

    timeout:
        type: int
        default: 5
        description:
            de: "Telnet Lese-Timeout"
            en: "telnet read timeout"


item_attributes:
    # Definition of item attributes defined by this plugin
    nut_var:
        type: str
        #valid_list:
        #  - ups.status
        #  - battery.charge
        #  - battery.voltage
        description:
            de: "ups Variable"
            en: "ups variable"

item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

