# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: gateway                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Music Player Deamon (MPD) Unterstützung'
        en: 'Music Player Deamon (MPD) support'
    maintainer: 'E3EAT'
#    tester:                        # Who tests this plugin?
    keywords: MPD Music             # keywords, where applicable
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mpd/...md # url of documentation (wiki) page

# Following entries are for Smart-Plugins:
    version: 1.4.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True
    classname: MPD                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    host:
        type: str
        mandatory: True
        description:
            de: 'IP oder Hostname des MPD'
            en: 'IP or hostname of the MPD'

    port:
        type: int
        mandatory: False
        default: 6600
        description:
            de: 'Der Port auf dem MPD lauscht.'
            en: 'The port that is used by MPD.'

    cycle:
        type: int
        mandatory: False
        default: 2
        description:
            de: 'Gibt an nach wie vielen Sekunden die Statusitems aktualisiert werden'
            en: 'The time interval that will be used for update the status items'
