# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Integration von E-Mail-Accounts - VERALTET, bitte stattdessen die Plugins mailsend und mailrcv benutzen'
        en: 'Integration of E-Mail-Accounts - DEPRECATED, use plugins mailsend and mailrcv instead'
    maintainer: '? (cmalo)'
    tester: psilo909, onkelandy, Sandman60
    state: deprecated
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.3.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
    sh_maxversion: 1.6.9           # To be retired with SmartHomeNG v1.7
    multi_instance: False          # plugin supports multi instance
    classname: SMTP                # class containing the plugin
#    classname: IMAP                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    host:
        type: str
        default: ''
        description:
            de: 'Adresse des SMTP Hosts'
            en: 'Address of SMTP host'

    port:
        type: int
        default: 587
        valid_min: 0
        valid_max: 65535
        description:
            de: 'Port des SMTP service (bitte 25 nutzen, fals tls deaktiviert wird)'
            en: 'Port used by SMTP service (use 25 if tls is set to False)'

    tls:
        type: bool
        default: True
        description:
            de: 'tls zur Verschlüsselung nutzen'
            en: 'Use tls for encyption'

    mail_from:
        type: str
        default: ''
        description:
            de: 'Absender-Adresse der eMails (mail@example.com)'
            en: 'Sender address of the emails (mail@example.com)'

    username:
        type: str
        default: ''
        description:
            de: 'Username für die Anmeldung am SMTP host (optional)'
            en: 'Username for login to the SMTP host (optional)'

    password:
        type: str
        default: ''
        hide: True
        description:
            de: 'Passwort für die Anmeldung am SMTP host (optional)'
            en: 'Password for login to the SMTP host (optional)'


item_attributes: NONE
    # Definition of item attributes defined by this plugin

plugin_functions:
    # Definition of plugin functions defined by this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin


