# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Dieses Plugin erlaubt es SmartTV Geräte wie z.B. Samsung zu steuern. Es hat zwei Implementierungen (für das alte und das neue API der TVs). Für das neue API muss auf dem TV der Zugriff akzeptiert werden, indem ein Button auf dem TV gedrückt wird, wenn der erste Request eingeht.'
        en: 'The plugin allows to control SmartTVs such as Samsung. It has two implementations for old and new versions of the API on the TV. For the new version you will have to accept the access to your TV by pressing a button on your TV on the first request that comes in.'
    maintainer: '? (2ndsky)'
    tester: psilo909
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.3.2                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: SmartTV             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    host:
        type: str
        mandatory: True
        description:
            de: 'IP Adresse des SmartTV Geräts.'
            en: 'Specifies the ip address of your SmartTV device.'

    port:
        type: int
        mandatory: False
        default: 55000
        description:
            de: '(optional) Im Fall eines Ports zu setzen, der nicht dem Standard entspricht (Standardports siehe tv_version). Default: 55000.'
            en: '(optional) Set, if you want to use a nonstandard port (for the standard see tv_version). Default: 55000.'

    tv_version:
        type: str
        mandatory: False
        default: classic
        description:
            de: '(optional) Erlaubte Werte sind "classic" (Port 55000) oder "samsung_m_series" (Standardport: 8001). Default: "classic".'
            en: '(optional) Allowed values are "classic" or "samsung_m_series", depending on the traditional (classic) use of the plugin via port 55000 or the version for the Samsung M series, which use port 8001 and a websocket connection. Default: "classic".'

    delay:
        type: int
        mandatory: False
        default: 1
        description:
            de: '(optional) Verzögerung in Sekunden, falls mehr als eine Taste gesendet wird. Reduziert Probleme, wenn bspw. TV-Programme wie "135" aufgerufen werden. Default: 1'
            en: '(optional) Specify a delay (in seconds), in case more than 1 key is sent. Reduces problems when switching e.g. to TV programs with numbers like "135". Default: 1.'

    instance:
        type: str
        default: ''
        description:
            de: 'Eindeutiger Identifier für die Instanz des Plugins. Kann bei nur einer konfigurierten Instanz des Plugins entfallen.'
            en: 'Unique identifier for each instance of the plugin. Can be omitted if only one device instance of the plugin is configured.'


item_attributes:
    # Definition of item attributes defined by this plugin
    smarttv:
        type: str
        mandatory: True
        description:
            de: 'Es gibt zwei Wege das Attribut zu nutzen.
  * Auf einem Item des Typs `str` mit dem Wert "true": Jeder String der in das Item geschrieben wird, wird an den SmartTV gesendet.
  * Auf einem Item des Typs `bool` mit dem Wert der zu betätigenden Tasten: Immer wenn das Item auf True gesetzt wird, werden die Tasten an den SmartTV gesendet. Je nach Anwendung sollte über das Setzen von `enforce_updates` nachgedacht werden.'
            en: 'There are two possibilities to use this attribute.
  * Define it on a string item and set it to `true`: With this configuration, every string you set to this item will be send to the SmartTV device.
  * Define it on a boolean item and set it to a key value: With this configuration, the specified key value is sent whenever you set the item to `true` (if the item is only for sending a specific command to the tv then you should consider using the `enforce_updates` attribute, too). It is even possible to define several keys separeted with a comma.'

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

