plugin:
    # Global plugin attributes
    type: gateway                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: '1-Wire Unterstützung über owserver'
        en: '1-Wire support via owserver'
        fr: 'Support de 1-Wire à travers owserver'
    maintainer: cmalo (mknx)
    # tester:
    state: ready
    keywords: 1wire onewire
    version: 1.3.2                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
    multi_instance: False
    restartable: unknown
    classname: OneWire              # class containing the plugin

parameters:
    host:
        type: ip
        default: 127.0.0.1
        description:
            de: 'owserver Hostname oder IP Adresse'
            en: 'owserver hostname or ip address'
            fr: "Nom de l'hôte ou adresse IP de l'owserver"

    port:
        type: int
        default: 4304
        description:
            de: 'owserver Port'
            en: 'owserver port'
            fr: "Port de l'owserver"

    cycle:
        type: int
        default: 300
        description:
            de: 'Zeitraum zwischen zwei Sensor-Abfragezyklen. Wenn dieser Wert zu stark gesenkt wird, kann das den Bus durch erhöhten Stromverbrauch destabilisieren.'
            en: 'timeperiod between two sensor cycles. If you decrease the cycle to much you could destabilise the bus, because of the increased power consumption.'

    io_wait:
        type: num
        default: 5
        description:
            de: 'Zeitraum zwischen zwei Anfragen an den 1-wire I/O Chip.'
            en: 'timeperiod between two requests of 1-wire I/O chip.'

    button_wait:
        type: num
        default: 0.5
        description:
            de: 'Zeitraum zwischen zwei Anfragen an einen iButton Busmaster'
            en: 'timeperiod between two requests of ibutton-busmaster.'

            
item_attributes:
    ow_addr:
        type: str
        description:
            de: 'Sensoradresse im Format xx.yyyyyyyyyyyy (Bitte darauf achten, dass bei rein numerischen Sensoradressen diese in '' eingeschlossen werden müssen)'
            en: 'Sensor address in xx.yyyyyyyyyyyy format (Please note: If the sensor address is numerical , it has to be enclosed in quotes)'
            fr: 'Adresse du capteur au format xx.yyyyyyyyyyyy'

    ow_sensor:
        type: str
        valid_list:
          - T
          - T9
          - T10
          - T11
          - T12
          - H
          - L
          - V
          - IA
          - IB
          - OA
          - OB
          - VDD
          - BM
          - B
        description:
            de: 'Sensortyp. Unterstützte Typen sind in der Plugin Readme zu finden'
            en: 'Sensor type. See plugin readme for supported types'
            fr: 'Type du capteur. Voir dans readme du plugin pour formats supportés'

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin

    ibutton_hook:
        type: void
        description:
            de: 'Dieses ist eine spezielle Funktion, die aufgerufen wird, wenn ein unbekannter iButton an den Bus gehängt wird. Falls der unbekannte iButton bereits erkannt wurde, wird die Id gecached und die Funktion nicht erneut aufgerufen. Der Cache wird alle 10 Minuten geleert. Die Funktion muss zwei Argumente akzeptieren.  - Um die Funktionalität zu nutzen, muss eine (sinnvolle) Funktion zugewiesen werden. (z.B.: sh.ow.ibutton_hook = intruder_alert)'
            en: 'This is a special function which is called if an unknown ibutton is attached to the bus. If the unknown ibutton is already seen, the id will be cached and the function is not called again. The cache will be reset every ten minutes. The function must take two arguments. The first will be the id of the ibutton and the second is the item of the ibutton busmaster (e.g. sh.home.key_hanger). - To use it you have to assign a (useful) function. (e.g.: sh.ow.ibutton_hook = intruder_alert)'
        parameter:
            ibutton:
                type: str
            description:
                de: 'Id des iButten der benutzt wurde'
                en: 'Id of the iButton that was used'
            item:
                type: str
            description:
            de: 'Item des Busmasters an dem der iButton genutzt wurde'
            en: 'item of the busmaster at which the ibutton was used'
