# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                 # plugin type (gateway, interface, protocol, system, web)
    description:
        # Alternative: description in multiple languages
        de: 'Anbindung von EnOcean'
        en: 'EnOcean Interface'
    maintainer: Robert Budde / aschwith
    # Who tests this plugin?
    #tester: 
    keywords: EnOcean, Eltako
    # url of documentation (wiki) page
    #documentation: https://...
    # url oof the support thread
    #support: https://...
    
    version: 1.3.3                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
    #sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: EnOcean             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    serialport:
        type: str
        default: /dev/ttyAMA0
        description:
            de: 'Name der Schnittstelle an der sich der EnOcean Adapter befindet'
            en: 'name of the port where the EnOcean adapter is plugged'
        mandatory: 'True'
          
    tx_id:
        type: str
        default: FFFF4680
        description:
            de: 'Unique-ID oder Base-ID des EnOcean Moduls (8-stelliger hex Wert, z.B. FFFF4680)'
            en: 'Unique-ID or Base-ID of the EnOcean Module (8-digit hex value, e.g. FFFF4680)'
        mandatory: 'True'
        
item_attributes:
    # Definition of item attributes defined by this plugin
    enocean_rx_id:
        type: str
        default: 1A794D3
        description:
            de: 'ID des EnOcean Gerätes (Aktor oder Sensor)'
            en: 'ID of the EnOcean device (actor or sensor)'
        mandatory: 'True'
        
    enocean_rx_eep:
        type: str
        default: F6_02_03
        description:
            de: 'EEP Profile des Response Telegramms'
            en: 'EEP Profile of the response meassage'
        mandatory: 'True'
        
    enocean_tx_eep:
        type: str
        default: A5_38_08
        description:
            de: 'EEP Profile des Sende Telegramms'
            en: 'EEP Profile of the send meassage'
        mandatory: 'True'
    
    enocean_tx_id_offset:
        type: int
        default: 0
        description:
            de: 'Offset zur Base-ID auf welche der Aktor reagiert'
            en: 'offset to the Base-ID on which the actor responds to'
        mandatory: 'False'
    
    enocean_rx_key:
        type: str
        default: A
        description:
            de: 'Knopf/Schalter-Bezeichnung des EnOcean Gerätes'
            en: 'actor button name of the EnOcean device'
        mandatory: 'False'
    
    block_switch:
        type: str
        default: 'False'
        description:
            de: 'Wenn True, blockiert den Aktor, so dass dieser nur mit dem gleichen Schalter ausgeschaltet werden kann'
            en: 'If true, blocks the actor. The actor can only switched off with the same switch'
        mandatory: 'False'
        
    block_dim_value:
        type: str
        default: 'False'
        description:
            de: 'Wenn True, blockiert den Aktor, so dass der Dimm-Wert nur mit dem gleichen Dimmer verstellt werden kann'
            en: 'If true, blocks the actor. The dim value can only controlled with the same dimmer'
        mandatory: 'False'
        
    dim_speed:
        type: str
        default: '50'
        Min: 0
        Max: 100
        description:
            de: 'Dimmgeschwindigkeit in %'
            en: 'dimm speed in %'
        mandatory: 'False'
        
    ref_level:
        type: str
        default: '80'
        Min: 0
        Max: 100
        description:
            de: 'Referenzwert in % fuer Dimmwert beim Einschalten'
            en: 'refeence dim value in % when switching on'
        mandatory: 'False'
        
    color:
        type: str
        default: 'red'
        description:
            de: 'Farbe für RGB-Dimmer'
            en: 'color for rgb dimmer'
        mandatory: 'False'
        
    enocean_rtime:
        type: str
        default: '60'
        Min: 0
        Max: 255
        description:
            de: 'Rolladenverstellzeit (runtime) in s'
            en: 'shutter run time in s'
        mandatory: 'False'
