# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                 # plugin type (gateway, interface, protocol, system, web)
    description:
        # Alternative: description in multiple languages
        de: 'Anbindung von EnOcean'
        en: 'EnOcean Interface'
    maintainer: Robert Budde / aschwith
    # Who tests this plugin?
    tester: unknown
    state: ready
    keywords: EnOcean, Eltako
    # url of documentation (wiki) page
    documentation: https://github.com/smarthomeNG/plugins/tree/master/enocean
    # url of the support thread
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/26542-featurewunsch-enocean-plugin/page13

    version: 1.4.0                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
    #sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: EnOcean             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    serialport:
        type: str
        default: /dev/ttyAMA0
        description:
            de: 'Name der Schnittstelle, an der sich der EnOcean Adapter befindet (als Linux-Handle oder RFC2217-URL)'
            en: 'name of the port where the EnOcean adapter is plugged in (as a linux file handle or RFC2217 URL)'

    tx_id:
        type: str
        description:
            de: 'Unique-ID oder Base-ID des EnOcean Moduls (8-stelliger hex Wert, z.B. FFFF4680)'
            en: 'Unique-ID or Base-ID of the EnOcean Module (8-digit hex value, e.g. FFFF4680)'
        mandatory: 'True'

    log_unknown_messages:
        type: bool
        description:
            de: 'Nachrichten von unbekannten Geraeten ins logfile schreiben'
            en: 'Log messages from unknown devices to logfile'
        default: 'False'


item_attributes:
    # Definition of item attributes defined by this plugin
    enocean_rx_id:
        type: str
        description:
            de: 'ID des EnOcean Gerätes (Aktor oder Sensor), z.B. 1A794D3'
            en: 'ID of the EnOcean device (actor or sensor), e.g. 1A794D3'
        mandatory: 'True'

    enocean_rx_eep:
        type: str
        description:
            de: 'EEP Profile des Response Telegramms, z.B. F6_02_03'
            en: 'EEP Profile of the response message, e.g. F6_02_03'
        mandatory: 'True'

    enocean_tx_eep:
        type: str
        description:
            de: 'EEP Profile des Sende Telegramms, z.B. A5_38_08'
            en: 'EEP Profile of the send message, e.g. A5_38_08'
        mandatory: 'True'

    enocean_tx_id_offset:
        type: int
        default: 0
        valid_min: 0
        valid_max: 127
        description:
            de: 'Offset zur Base-ID, auf welche der Aktor reagiert'
            en: 'offset to the Base-ID on which the actor responds to'

    enocean_rx_key:
        type: str
        default: A
        description:
            de: 'Knopf/Schalter-Bezeichnung des EnOcean Gerätes'
            en: 'actor button name of the EnOcean device'

    enocean_rocker_action:
        type: str
        description:
            de: 'Tasteraktion'
            en: 'actor action'
        mandatory: 'False'
        valid_list:
        - 'UNSET'
        - 'TOGGLE'
        - 'SET'

    enocean_rocker_sequence:
        type: str
        description:
            de: 'Tastersequenz'
            en: 'Rocker action sequence'

    enocean_device:
        type: str
        description:
            de: 'Enocean Geraetetyp'
            en: 'Enocean device type'
        mandatory: 'False'
        valid_list:
        - 'FSUD-230V'
        - 'FUD61NPN-230V'
        - 'FSVA-230V'
        - 'FSM60B'
        - 'FLD61'
        - 'FUD70S-230V'
        - 'FBH63TF'
        - 'NodOn-STP-2-1-03'
        - 'SecuSignal'

    block_switch:
        type: str
        default: 'False'
        description:
            de: 'Wenn True, blockiert den Aktor, so dass dieser nur mit dem gleichen Schalter ausgeschaltet werden kann'
            en: 'If true, blocks the actor. The actor can only switched off with the same switch'

    block_dim_value:
        type: str
        default: 'False'
        description:
            de: 'Wenn True, blockiert den Aktor, so dass der Dimm-Wert nur mit dem gleichen Dimmer verstellt werden kann'
            en: 'If true, blocks the actor. The dim value can only controlled with the same dimmer'

    dim_speed:
        type: str
        default: '50'
        Min: 0
        Max: 100
        description:
            de: 'Dimmgeschwindigkeit in %'
            en: 'dimm speed in %'

    ref_level:
        type: str
        default: '80'
        Min: 0
        Max: 100
        description:
            de: 'Referenzwert in % fuer Dimmwert beim Einschalten'
            en: 'reference dim value in % when switching on'

    color:
        type: str
        default: 'red'
        description:
            de: 'Farbe für RGB-Dimmer'
            en: 'color for rgb dimmer'

    enocean_rtime:
        type: str
        default: '60'
        Min: 0
        Max: 255
        description:
            de: 'Rolladenverstellzeit (runtime) in s'
            en: 'shutter run time in s'

plugin_functions: NONE
# Definition of plugin functions defined by this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

item_structs: NONE

