# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Easymeter Q3D Unterstützung - Parameter für serielle Devices sind aktuell fest auf 9600/7E1 gesetzt'
        en: 'Easymeter Q3D support - Parameter for serial device are currently set to fix 9600/7E1'
    maintainer: '?'
    tester: '?'                     # Who tests this plugin?
#    keywords: kwd1 kwd2            # keywords, where applicable
    state: deprecated               # No user or tester for SmartPlugin conversion could be found
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

# Following entries are for Smart-Plugins:
    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.6              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False
    restartable: True
    classname: easymeter            # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    easymeter_code:
        type: str
        description:
            de: 'Obis Protokoll Code'
            en: 'obis protocol code'

    device:
        type: str
        default: /dev/ttyUSB0
        description:
            de: 'USB device für den IR-Readed von volkszaehler.org'
            en: 'USB device for ir-reader from volkszaehler.org'

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

