# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Wetterdaten über darksky.net.'
        en: 'Weather data via darksky.net.'
    maintainer: psilo909
    tester:
#    keywords: iot xyz
    documentation: ''
    support: ''
    keywords: weather
    version: 1.5.0.1              # Plugin version
    sh_minversion: 1.4c           # minimum shNG version to use this plugin
#    sh_maxversion:               # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True          # plugin supports multi instance
    classname: OpenWeatherMap     # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    key:
        type: str
        mandatory: True
        description:
            de: 'Persönlicher API Key für darksky.net. Registrierung unter https://openweathermap.org/.'
            en: 'Your own personal API key for darksky.net. For your own key register to https://openweathermap.org/.'
    latitude:
        type: str
        mandatory: False
        default: ''
        description:
            de: 'Latitude des Ortes, für den die Wetterdaten abgerufen werden sollen. Default: SmartHomeNG Settings'
            en: 'Latitude for the location, of which weather data is requested. Default: SmartHomeNG Settings'
    longitude:
        type: str
        mandatory: False
        default: ''
        description:
            de: 'Longitude des Ortes, für den die Wetterdaten abgerufen werden sollen. Default: SmartHomeNG Settings.'
            en: 'Longitude for the location, of which weather data is requested. Default: SmartHomeNG Settings.'
    lang:
        type: str
        mandatory: False
        default: 'de'
        description:
            de: 'Sprache der zurückgelieferten Daten. Mögliche Werte siehe https://openweathermap.org/api.'
            en: 'Language of the data to be returned. Possible values see https://openweathermap.org/api.'
    units:
        type: str
        mandatory: False
        default: 'metric'
        description:
            de: 'Einheit der zurückgelieferten Daten. Mögliche Werte sind imperial und metric.'
            en: 'Unit of the returned data. Possible values are imperial and metric.'
    cycle:
        type: int
        mandatory: False
        default: 300
        description:
            de: '(optional) Zeit zwischen zwei Updateläufen. Default ist 300 Sekunden.'
            en: '(optional) Time period between two update cycles. Default is 300 seconds.'
    
item_attributes:
    # Definition of item attributes defined by this plugin
    owm_matchstring:
        type: str
        mandatory: True
        description:
            de: 'Matchstring für die OpenWeatherMap Daten, siehe Beispiele in der README.'
            en: 'Matchstring for the OpenWeatherMap data, see examples in README.'