# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: protocol                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Anbindung eines Philips TVs an SmartHomeNG'
        en: 'Plugin to connect a Philips TV with SmartHomeNG'
    maintainer: aschwith 
    tester: 'n/a'
    state: ready
    keywords: Philips, TV
    documentation: https://github.com/smarthomeNG/plugins/blob/develop/philips_tv/user_doc.rst
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1698335-supportthread-f%C3%BCr-philips_tv-plugin

    version: 1.9.1                  # Plugin version
    sh_minversion: 1.8.0            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: unknown
    classname: Philips_TV           # class containing the plugin

parameters:
    ip:
        type: ip
        mandatory: True
        description:
            de: "IP Adresse des Philips Geraetss"
            en: "IP address of Philips tv device"

    deviceID:
        type: str
        gui_type: readonly 
        description:
            de: "Device ID (beim Bindungsvorgang automatisch generiert)"
            en: "Device id (is generated automatically during pairing procedure"
    
    deviceKey:
        type: str
        gui_type: readonly 
        description:
            de: "Passwort (beim Bindungsvorgang automatisch generiert)"
            en: "Password (is generated automatically during pairing procedure"

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    philips_tv_tx_key:
        type: str
        description:
            de: 'Key fuer das Senden von Kommandos an den Philips TV'
            en: 'Key for sending commands to the Philips TV'
        valid_list:
        - 'MUTE'
        - 'POWEROFF'

    philips_tv_rx_key:
        type: str
        description:
            de: 'Key fuer den Empfang von Statusinformationen'
            en: 'Key for receiving status informations'
        valid_list:
        - 'MUTE'
        - 'VOLUME'
        - 'ERROR'
        - 'POWERSTATE'
        - 'POWERSTATEINFO'
        - 'CHANNEL'

plugin_functions: NONE 

logic_parameters: NONE

item_structs: NONE
