# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: system                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Anzeige von Informationen von ESPHome Devices'
        en: 'Plugin to display informationen about ESPHome devices'
    maintainer: msinn
#    tester:                         # Who tests this plugin?
    state: develop                  # Initial 'develop'. change to 'ready' when done with development
#    keywords: iot xyz
#    documentation: ''              # An url to optional plugin doc - NOT the url to user_doc!!!
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 0.0.2                  # Plugin version (must match the version specified in __init__.py)

    # these min/max-versions MUST be given in quotes, or e.g. 3.10 will be interpreted as 3.1 (3.1 < 3.9 < 3.10)
    sh_minversion: '1.10'           # minimum shNG version to use this plugin
#    sh_maxversion: '1.11'          # maximum shNG version to use this plugin (omit if latest)
#    py_minversion: '3.10'          # minimum Python version to use for this plugin
#    py_maxversion: '4.25'          # maximum Python version to use for this plugin (omit if latest)

    multi_instance: false           # plugin supports multi instance
    restartable: unknown            # plugin supports stopping and starting again, must be implemented
    configuration_needed: False     # False: The plugin will be enabled by the Admin GUI without configuration
    classname: EspHome              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)

    # item to toggle plugin execution, remove if not wanted
    # (needs plugin to be restartable)
    pause_item:
        type: str
        default: ''
        description:
            de: 'Item, um die Ausführung des Plugins zu steuern'
            en: 'item for controlling plugin execution'

    param1:
        type: str
        description:
            de: 'Demo Parameter'
            en: 'Parameter for demonstration purposes'

    param2:
        type: str
        default: 'value2'
        valid_list:
            - 'value1'
            - 'value2'
            - 'value3'
            - 'value4'
            - 'value5'
        description:
            de: 'Demo Parameter mit Gültigkeitsliste und Standardwert'
            en: 'Demonstration parameter with valid-list and default value'

#    param3:
#        type: str
#        # If 'mandatory' is specified, a 'default' attribute must not be specified
#        mandatory: true
#        description:
#            de: 'Demo Parameter der angegeben werden muss'
#            en: 'Demonstration parameter which has to be specified'

item_attributes: NONE
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
