# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung von Russound Audio Geräten'
        en: 'Russound audio device '
    maintainer: bmxp
    tester: alex,fritz              # Who tests this plugin?
    state: develop                  # change to ready when done with development
    keywords: russound audio device multiroom net
    documentation: https://www.smarthomeng.de/developer/plugins/russound/user_doc.html        # url of documentation (wiki) page
    support:       https://knx-user-forum.de/forum/supportforen/smarthome-py/1800440-support-thread-für-das-russound-plugin

    version: 1.7.2                  # Plugin version
    sh_minversion: 1.9.0            # minimum shNG version to use this plugin
    # sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: false           # plugin supports multi instance
    restartable: true
    classname: Russound         # class containing the plugin

parameters:
    host:
        type: ip
        default: 127.0.0.1
        description:
            de: 'Russound Hostname oder IP Adresse'
            en: 'Russound hostname or ip address'
            fr: "Nom de l'hôte ou adresse IP de Russound"

    port:
        type: int
        default: 9621
        description:
            de: 'Russound Port'
            en: 'Russound port'
            fr: "Port de Russound"

    standby_item:
        type: str
        default: ''
        description:
            de: 'Item zum Aktivieren des Suspend-Modus'
            en: 'item for activating suspend mode'

item_attributes:
    rus_path:
        type: str
        description:
            de: >
                Pfad mit Controller, Zone und System Parameter, getrennt durch "."
                Parameter ist
                * status = Zone An oder Aus: Item muss vom Typ "bool" sein
                * volume = Lautstärke der Zone: Item muss vom Typ "num" sein. Gültige Werte im Bereich [0..50]
                * bass = Bass der Zone: Item muss vom Typ "num" sein. Gültige Werte im Bereich [-10..10]
                * treble = Höhen der Zone: Item muss vom Typ "num" sein. Gültige Werte im Bereich [-10..10]
                * balance = Balance der Zone: Item muss vom Typ "num" sein. Gültige Werte im Bereich [-10..10]
                * turnonvolume = Lautstärke der Zone einschalten: Item muss vom Typ "num" sein. Gültige Werte im Bereich [0..50]
                * currentsource = Nummer der Soundquelle: Item muss vom Typ "num" sein.
                * mute = Ausgabeunterdrückung der zone (Mute): Item muss vom Typ "bool" sein
                * loudness = Loudness der zone: Item muss vom Typ "bool" sein
                * partymode = Party Modus Einstellung der Zone: Item muss vom Typ string sein. Gültige Werte [ON/OFF/MASTER]
                * donotdisturb = "Nicht Stören" Einstellung der Zone: Item muss vom Typ string sein
                * name = Name der Zone (nur lesbar)

            en: >
                Path with controller, zone and system parameter, separated by .
                * status = zone On/Off: item type must be bool
                * volume = volume of the zone: item type must be num [0..50]
                * bass = bass of the zone: item type must be num [-10..10]
                * treble = treble of the zone: item type must be num [-10..10]
                * balance = balance of the zone: item type must be num [-10..10]
                * turnonvolume = volume on zone on: item type must be num [0..50]
                * currentsource = number of the source: item type must be num
                * mute = mute the zone volume: item type must be bool
                * loudness = loudness of the zone: item type must be bool
                * partymode = party mode setting of the zone: item type must be string [ON/OFF/MASTER]
                * donotdisturb = do not disturb setting of the zone: item type must be string
                * name = name of the zone (readonly)
                


item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: 
    suspend:
        type: foo
        description:
            de: "Schliesst vorübergehend die Kommunikation mit Russound"
            en: "Closes communication with Russound and does neither send data nor query settings"

    activate:
        type: foo
        description:
            de: "Startet die Kommunikation mit Russound neu"
            en: "Open up communication with Russound again and enable sending data and query settings"

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

