# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: protocol                 # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Wake on LAN'
        en: 'Wake on LAN'
    maintainer: cmalo
    tester: ohinckel
    state: qa-passed
#    tester:                        # Who tests this plugin?
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page

    version: 1.1.2                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: WakeOnLan           # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    instance:
        type: str
        default: ''
        description:
            de: 'Eindeutiger Identifier für die Instanz des Plugins. Kann bei nur einer konfigurierten Instanz des Plugins entfallen.'
            en: 'Unique identifier for each instance of the plugin. Can be omitted if only one device instance of the plugin is configured.'

item_attributes:
    # Definition of item attributes defined by this plugin
    wol_mac:
        type: mac
        mandatory: True
        description:
            de: 'MAC Adresse des per WOL aufzuweckenden Geräts.'
            en: 'MAC address of device that shall be started by WOL.'

    wol_ip:
        type: str
        mandatory: False
        description:
            de: '(optional) IP Adresse des per WOL aufzuweckenden Geräts.'
            en: '(optional) IP address of device that shall be started by WOL.'

item_structs: NONE
  # Definition of item-structure templates for this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin
