# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung einer oder mehrerer SMA-Sunny-WebBox(en)'
        en: ''
    maintainer: '? (Brootux)'
#    tester: efgh                   # Who tests this plugin?
#    keywords: kwd1 kwd2            # keywords, where applicable
    state: deprecated
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page

# Following entries are for Smart-Plugins:
#    version: 1.3.3                 # Plugin version
#    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    multi_instance: False
    classname: SMAWB               # class containing the plugin

#parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

#item_attributes:
    # Definition of item attributes defined by this plugin

