# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                   # plugin type (gateway, interface, protocol, system, web)
    description:                   # Alternative: description in multiple languages
        de: 'Ermöglicht Speicherung von Item Werten in einer InfluxData time-series Datenbank'
        en: 'Plugin to store item values in an InfluxData time-series database'
    requirements:
        de: 'influxdb database'
        en: 'influxdb database'
    maintainer: Kai Meder
    tester: chrisr79, onkelandy                    # Who tests this plugin?
    state: ready
    keywords: database, influx, influxdb
    #documentation: https://www.smarthomeng.de/user/plugins/influxdb/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1498207-support-thread-f%C3%BCr-influxdb-plugin

    version: 1.0.3                 # Plugin version
    sh_minversion: '1.1'             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    startorder: early              # set start priority of plugin (early/normal/late)
    classname: InfluxDB            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    host:
        type: str
        default: 'localhost'
        description:
            de: "Hostname der InfluxData Datenbank"
            en: "Hostname of the InfluxData database"
    udp_port:
        type: int
        default: 8089
        valid_min: 0
        valid_max: 65535
        description:
            de: "Portnummer der InfluxData Datenbank"
            en: "Port of the InfluxData database"
    keyword:
        type: str
        default: 'influxdb'
        description:
            de: "Dieser Parameter legt fest, auf welches Item-Attribut das Plugin reaagiert. \
                 (Wenn hier ein anderer Wert als 'influxdb' angegeben wird, können in Zukunft Items nicht über das \
                 graphische Admin-Interface für dieses Plugin konfiguriert werden)"
            en: "The parameter influx_keyword has a special relevance. Here you can choose which item attribute \
                 the plugin should look for."
    tags:
        type: dict
        description:
            de: "Globale Angabe zusätzlicher Tags"
            en: "specify additional tags globally"
    fields:
        type: dict
        description:
            de: "Globale Angabe zusätzlicher Felder"
            en: "specify additional fields globally"
    value_field:
        type: str
        default: 'value'
        description:
            de: "?"
            en: "?"
    write_http:
        type: bool
        default: False
        description:
            de: "Bei True werden die Werte mit HTTP und bei False mit UDP in die Datenbank geschrieben."
            en: "If True values into the database are written with HTTP, if False with UDP."
    http_port:
        type: int
        default: 8086
        valid_min: 0
        valid_max: 65535
        description:
            de: "Portnummer der InfluxData Datenbank für HTTP-Zugriff"
            en: "Port of the InfluxData database for HTTP access"

item_attributes:
    # Definition of item attributes defined by this plugin
    influxdb:
        type: foo
        description:
            de: "Diesem Attribut einen Wert zuweisen, um den Item Wert durch das influxdata Plugin zu speichern"
            en: "Assign a value to this attribute to store the item value through the influxdata plugin"
    influxdb_name:
        type: str
        description:
            de: "Name unter dem die Werte gespeichert werden sollen"
            en: "Name used to store the values"
    influxdb_tags:
        type: dict
        description:
            de: 'Angabe weitere Tags, die mit dem Wert gespeichert werden sollen (z.B.: {"room": "dining"}'
            en: 'Specify additional tags to be stored with the value (e.g.: {"room": "dining"}'
    influxdb_fields:
        type: dict
        description:
            de: 'Das Schlüssel-Wert-Paar in einer InfluxDB-Datenstruktur, die Metadaten und den tatsächlichen Datenwert aufzeichnet.'
            en: 'The key-value pair in an InfluxDB data structure that records metadata and the actual data value.'

item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin
