# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                   # plugin type (gateway, interface, protocol, system, web)
    description:                   # Alternative: description in multiple languages
        de: 'Ermöglicht Speicherung von Item Werten in einer InfluxData time-series Datenbank (Plugin aus 2017)'
        en: 'Plugin to store item values in an InfluxData time-series database (plugin from 2017)'
    maintainer: Kai Meder
    tester: '?'                    # Who tests this plugin?
    state: ready
    keywords: database
    documentation: https://github.com/smarthomeNG/smarthome/wiki/Installation-Influx-Grafana        # url of documentation (wiki) page

    version: 1.0.0                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: InfluxDB            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    host:
        type: str
        default: 'localhost'
        description:
            de: "Hostname der InfluxData Datenbank"
            en: "Hostname of the InfluxData database"
    udp_port:
        type: int
        default: 8089
        valid_min: 0
        valid_max: 65535
        description:
            de: "Portnummer der InfluxData Datenbank"
            en: "Port of the InfluxData database"
    keyword:
        type: str
        default: 'influxdb'
        description:
            de: "Dieser Parameter legt fest, auf welches Item-Attribut das Plugin reaagiert. \
                 (Wenn hier ein anderer Wert als 'influxdb' angegeben wird, können in Zukunft Items nicht über das \
                 graphische Admin-Interface für dieses Plugin konfiguriert werden)"
            en: "The parameter influx_keyword has a special relevance. Here you can choose which item attribute \
                 the plugin should look for."
    tags:
        type: dict
        description:
            de: "Globale Angabe zusätzlicher Tags"
            en: "specify additional tags globally"
    fields:
        type: dict
        description:
            de: "Globale Angabe zusätzlicher Felder"
            en: "specify additional fields globally"
    value_field:
        type: str
        default: 'value'
        description:
            de: "?"
            en: "?"

item_attributes:
    # Definition of item attributes defined by this plugin
    influxdb:
        type: foo
        default: None'
        description:
            de: "Diesem Attribut einen Wert zuweisen, um den Item Wert durch das influxdata Plugin zu speichern"
            en: "Assign a value to this attribute to store the item value through the influxdata plugin"
    influxdb_name:
        type: str
        description:
            de: "Name unter dem die Werte gespeichert werden sollen"
            en: "Name used to store the values"
    influxdb_tags:
        type: dict
        description:
            de: 'Angabe weitere Tags, die mit dem Wert gespeichert werden sollen (z.B.: {"room": "dining"}'
            en: 'Specify additional tags to be stored with the value (e.g.: {"room": "dining"}'

item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

