# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Einbindung von Enigma2 kompatiblen Sat-Receivern mit openwebif'
        en: 'Plugin to include Enigma2 sat receivers compatible to openwebif'
    maintainer: psilo909
    tester: Sandman60, msinn
    state: 'qa-passed'
#    keywords: iot xyz
    documentation: http://smarthomeng.de/user/plugins_doc/config/enigma2.html        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/943871-enigma2-plugin

    version: 1.4.11                # Plugin version
    sh_minversion: 1.3c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    classname: Enigma2             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    username:
        type: str
        default: ''
        description:
            de: '(optional) Nutzername für den Login.'
            en: '(optional) Login information (user).'
    password:
        type: str
        default: ''
        description:
            de: '(optional) Passwort für den Login. Wird aus Sicherheitsgründen empfohlen.'
            en: '(optional) Password for login. Is recommended due to security reasons'
    host:
        type: str
        default: 'dreambox'
        description:
            de: '(optional) Hostname oder IP-Adresse des Geräts auf dem OpenWebIF läuft.'
            en: '(optional) Hostname or ip address of the device on which OpenWebIF is running.'
    port:
        type: int
        default: 80
        description:
            de: 'Port des OpenWebIF.'
            en: 'Port on which the OpenWebIF is accessible.'
    ssl:
        type: bool
        default: True
        description:
            de: '(optional) Mit True wird das OpenWebIF via https, mit False via http angesprochen.'
            en: '(optional) True will add "https", False "http" to the URLs in the plugin.'
    verify:
        type: bool
        default: False
        description:
            de: '(optional) Schaltet die Zertifikate-Prüfung an oder aus. Normalerweise False.'
            en: '(optional) Turns certificate verification on or off. Typically False'
    cycle:
        type: int
        default: 300
        description:
            de: '(optional) Zeit zwischen zwei Updateläufen. Default ist 300 Sekunden.'
            en: '(optional) Timeperiod between two update cycles. Default is 300 seconds.'
    fast_cycle:
        type: int
        default: 10
        description:
            de: '(optional) Zeit zwischen zwei Updateläufen für besondere Items, die schneller geupdated werden. Default ist 10 Sekunden.'
            en: '(optional) Timeperiod between two update cycles for items, which are updated faster. Default is 10 seconds.'
    instance:
        type: str
        default: ''
        description:
            de: '(optional) Eindeutiger Identifier für die Instanz des Plugins. Kann bei nur einem Gerät / Single Instance Betrieb des Plugins entfallen.'
            en: '(optional) Unique identifier for each instance of the plugin. Can be skipped if only one device is used / the plugin is operated single instance.'

    
item_attributes:
    # Definition of item attributes defined by this plugin
    enigma2_data_type:
        type: str
        description:
            de: 'Datentyp für Plugin-Items. Siehe README.'
            en: 'Data type for plugin items. See README.'

    enigma2_page:
        type: str
        description:
            de: 'Notwendig für bestimmte Plugin-Items. Siehe README.'
            en: 'Required for specific plugin items. See README.'

    sref:
        type: str
        description:
            de: 'Referenz auf Services (bspw. Sender), siehe README.'
            en: 'Service reference, see README.'

plugin_functions:
    # Definition of function interface of the plugin

    get_audio_tracks:
        type: list
        description:
            de: "Diese Funktion liefert eine Liste von dicts mit den folgenden Keys: 'e2audiotrackdescription' (str), 'e2audiotrackid' (int), 'e2audiotrackpid' (int), 'e2audiotrackactive' (bool) - Beispiel: sh.vusolo2.get_audio_tracks()"
            en: "This function returns a list of dicts with the following keys: 'e2audiotrackdescription' (str), 'e2audiotrackid' (int), 'e2audiotrackpid' (int), 'e2audiotrackactive' (bool) - Example: sh.vusolo2.get_audio_tracks()"

        parameters:
            # This function has no parameters

    send_message:
        type: foo
        description:
            de: "Sendet eine Message an das Enigma2 Device - Beispiel: sh.vusolo2.send_message('Testnachricht', 1, 10)"
            en: "Sends a message to the device - Example: sh.vusolo2.send_message('Testmessage', 1, 10)"

        parameters:
            messagetext:
                type: str
                description:
                    de: "Anzuzeignder Text"
                    en: "Text to be displayed"
            messagetype:
                type: int
                default: 1
                valid_min: 0
                valid_max: 3
                description:
                    de: "0=Ja/Nein, 1=Info, 2=Mitteilung, 3=Achtung"
                    en: "0=Yes/No, 1=Info, 2=Message, 3=Attention"
            timeout:
                type: int
                default: 10
                description:
                    de: "Anzeigedauer der Message in Sekunden"
                    en: "Number of seconds the message should stay on the device"

    set_power_state:
        type: foo
        description:
            de: "Setzt den Power-Status auf einen bestimmten Wert - Beispiel (toggle standby): sh.vusolo2.set_power_state(0)"
            en: "Sets the power state to a specific value - Example (toggle standby): sh.vusolo2.set_power_state(0)"

        parameters:
            value:
                type: int
                valid_min: 0
                valid_max: 5
                description:
                    de: "0 = Toggle Standby 1 = Deepstandby 2 = Reboot 3 = Restart Enigma2 4 = Wakeup from Standby 5 = Standby"
                    en: "0 = Toggle Standby 1 = Deepstandby 2 = Reboot 3 = Restart Enigma2 4 = Wakeup from Standby 5 = Standby"

    get_answer:
        type: foo
        description:
            de: "Diese Funktion prüft, ob eine Antwort zu einer gesendeten Message eingegangen ist. Dabei ist ddas timeout zu beachten, bis eine Message beantwortet wird. - Beispiel: sh.vusolo2.get_answer()"
            en: "This function checks for an answer to a sent message. If you call this method, take into account the timeout until the message can be answered and e.g. set a 'while (count < 0)' - Example: sh.vusolo2.get_answer()"

        parameters:
            # This function has no parameters
