# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin zur Steuerung von Switches, die mit Tasmota Firmware ausgestattet sind. Die Kommunikation erfolgt über das MQTT Module von SmartHomeNG.'
        en: 'Plugin to control switches which are equipped with Tasmote firmware. Communication is handled through the MQTT module of SmartHomeNG.'
    maintainer: msinn
    tester: msinn                  # Who tests this plugin?
    state: develop                   # change to ready when done with development
    keywords: iot
    documentation: http://smarthomeng.de/user/plugins/tasmota/user_doc.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1520293-support-thread-für-das-tasmota-plugin

    version: 1.1.0                 # Plugin version
    sh_minversion: 1.7.2           # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    py_minversion: 3.6             # minimum Python version to use for this plugin
    multi_instance: True           # plugin supports multi instance
    restartable: unknown
    classname: Tasmota             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    full_topic:
        type: str
        default: '%prefix%/%topic%/'
        description:
            de: Vollständiges Topic (Prefix und Topic) zur Kommunikation mit den Tasmota Devices
            en: Full topic (prefix und topic) for communication with tasmota devices
    telemetry_period:
        type: int
        default: 300
        valid_min: 10
        valid_max: 3600
        description:
            de: Zeitabstand in Sekunden in dem die Tasmota Devices Telemetrie Daten senden sollen
            en: Timeperiod in seconds in which Tasmota devices shall send telemetry data

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    tasmota_topic:
        type: str
        description:
            de: Topic um mit dem Tasmota Device zu kommunizieren (%topic%)
            en: Topic to be used to communicate with the tasmota device (%topic%)

    tasmota_attr:
        type: str
        default: relay
        description:
            de: "Zu lesendes/schreibendes Attribut des Tasmota Devices. Achtung: Nicht jedes Attribut ist auf allen Device-Typen vorhanden."
            en: "Attribute of Tasmota device that shall be read/written. Note: Not every attribute is available on all device types"
        valid_list_ci:
            - ''
            - relay
            - online
            - voltage
            - current
            - power
            - power_total
            - power_yesterday
            - power_today
            - temp
            - hum
            - dewpoint
            - hsb
            - rf_recv
            - rf_send
            - rf_key_send

        valid_list_description:
            de:
              - "<noch kein Attribut gewählt>"
              - "Schalten des Relais -> bool, r/w"
              - "Online Status des Tasmota Devices -> bool, r/o"
              - "Spannung in Volt bei Tasmota Devices mit ENERGY Sensor -> num, r/o"
              - "Strom in Ampere bei Tasmota Devices mit ENERGY Sensor -> num, r/o"
              - "Leistung in Watt bei Tasmota Devices mit ENERGY Sensor -> num, r/o"
              - "Verbrauch (gesamt) in kWh bei Tasmota Devices mit ENERGY Sensor -> num, r/o"
              - "Verbrauch (gestern) in kWh bei Tasmota Devices mit ENERGY Sensor -> num, r/o"
              - "Verbrauch (heute) in kWh bei Tasmota Devices mit ENERGY Sensor -> num, r/o"
              - "Temperatur in °C bei Tasmota Devices mit TEMP Sensor (DS18B20, AM2301) -> num, r/o"
              - "Luftfeuchtigkeit in %rH bei Tasmota Devices mit HUM Sensor (AM2301) -> num, r/o"
              - "Taupunkt in °C bei Tasmota Devices mit HUM und TEMP Sensor (AM2301) -> num, r/o"
              - "Hue, Saturartion, Brightness (HSB) bei RGBW Tasmota Devices (H801) -> list, r/w"
              - "Empfange RF data bei Tasmota Device mit RF Empfang (SONOFF Bridge) -> str, r/o"
              - "Zu sendende RF Daten bei Tasmota Device mit RF Sendemöglichkeit (SONOFF Bridge) -> dict, r/w"
              - "Zu sendende RF-Key Tasmota Device mit RF Sendemöglichkeit (SONOFF Bridge) -> num [1-16], r/w"

    tasmota_relay:
        type: str
        default: '1'
        valid_list:
          - '1'
          - '2'
          - '3'
          - '4'
        description:
            de: "Nummer des zu schaltenden Relais im Tasmota Device"
            en: "Number of the relay in Tasmota device to use for switching command"

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

