# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung der Nokia Health API mit Oauth2'
        en: 'Usage of the nokia health api with oauth2'
    maintainer: 'psilo909'
    tester: 'psilo909'
    state: ready
    keywords: health
    documentation: 'http://smarthomeng.de/user/plugins_doc/config/withings_health.html'
    support: 'https://knx-user-forum.de/forum/supportforen/smarthome-py/1141179-nokia-health-plugin'

    version: 1.8.1                 # Plugin version
    sh_minversion: 1.7             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    restartable: True
    classname: WithingsHealth         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    user_id:
        type: str
        mandatory: True
        description:
            de: 'Nokia Health User ID (steht in der URL, wenn man als nomraler User einloggt)'
            en: 'Nokia Health User ID (can be found in the URL when you log in)'

    client_id:
        type: str
        mandatory: True
        description:
            de: 'Client ID von https://account.health.nokia.com/partner/dashboard_oauth2'
            en: 'Client ID from https://account.health.nokia.com/partner/dashboard_oauth2'

    consumer_secret:
        type: str
        default: 300
        mandatory: True
        description:
            de: 'Consumer-Geheimnis von https://account.health.nokia.com/partner/dashboard_oauth2'
            en: 'Consumer secret from https://account.health.nokia.com/partner/dashboard_oauth2'

    cycle:
        type: int
        default: 300
        description:
            de: 'Dieser Parameter muss normalerweise nicht angegeben werden. Er erlaubt es die Update-Frquenz anzupassen (Standard: alle 600 Sekunden). Mit dem Standardwert werden die Daten von Nokia Health alle 5 Minuten aktualisiert.'
            en: "This parameter usually doesn't have to be specified. It allows to change the update frequency (cycle every 300 seconds). As a standard, the plugin updates the Nokia Health data every 5 minutes."

item_attributes:
    # Definition of item attributes defined by this plugin

    withings_type:
        type: str
        description:
            de: 'nh_type kann folgende Werte annehmen: Zwingend für OAuth2: access_token, token_expiry, token_type, refresh_token | Optional: weight, height (wird von Nokia Health nur beim allerersten Messwert geliefert), bmi, bmi_text, fat_ratio, fat_free_mass, fat_mass_weight, diastolic_blood_pressure, systolic_blood_pressure, temperature, body_temperature, skin_temperature, spo2, heart_pulse, hydration, bone_mass, pulse_wave_velocity.'
            en: 'nh_type can be out of the following values: Mandatory for OAuth2: access_token, token_expiry, token_type, refresh_token | Optional: weight, height (only supplied on the very first measurement value, set manually if you dont get it), bmi, bmi_text, fat_ratio, fat_free_mass, fat_mass_weight, diastolic_blood_pressure, systolic_blood_pressure, temperature, body_temperature, skin_temperature, spo2, heart_pulse, hydration, bone_mass, pulse_wave_velocity.'
        valid_list:
        - 'weight'
        - 'height'
        - 'bmi'
        - 'bmi_text'
        - 'fat_ratio'
        - 'fat_free_mass'
        - 'fat_mass_weight'
        - 'diastolic_blood_pressure'
        - 'systolic_blood_pressure'
        - 'temperature'
        - 'body_temperature'
        - 'skin_temperature'
        - 'spo2'
        - 'heart_rate'
        - 'hydration'
        - 'bone_mass'
        - 'pulse_wave_velocity'
        - 'access_token'
        - 'token_expiry'
        - 'token_type'
        - 'refresh_token'

item_structs:
  # Definition of item-structure templates for this plugin
    body:
        name: Body data from withings health scale

        weight:
            name: Body weight
            type: num
            withings_type@instance: weight
            database: init

        height:
            name: Body height
            type: num
            withings_type@instance: height
            database: init

        bmi:
            name: Bondy measurement index (BMI) calculated by the plugin from weight and height (might only work after height is retrieved first time)
            type: num
            withings_type@instance: bmi
            database: init

        bmi_text:
            name: Bondy measurement index (BMI) in a textual representation (German/English)
            type: str
            withings_type@instance: bmi_text
            database: init

        fat_ratio:
            name: Fat ratio of the measured body
            type: num
            withings_type@instance: fat_ratio
            database: init

        fat_free_mass:
            name: Fat free mass of the measured body
            type: num
            withings_type@instance: fat_free_mass
            database: init

        fat_mass_weight:
            name: Fat weight of the measured body
            type: num
            withings_type@instance: fat_mass_weight
            database: init

        heart_rate:
            name: Heart rate during measurement
            type: num
            withings_type@instance: heart_rate
            database: init

        access_token:
            name: Stores the access token after oauth authentification
            type: str
            cache: yes
            withings_type@instance: access_token

        token_expiry:
            name: Stores the token expiration time after oauth authentification
            type: num
            cache: yes
            withings_type@instance: token_expiry

        token_type:
            name: Stores the token type after oauth authentification
            type: str
            cache: yes
            withings_type@instance: token_type

        refresh_token:
            name: Stores the refresh token for the next refresh
            type: str
            cache: yes
            withings_type@instance: refresh_token

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin
    get_callback_url:
        type: str
        description:
            de: 'Gibt die Callback URL des Withings Health Plugins zurück.'
            en: 'Returns the callback url of the withings health plugin.'
