# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung des Telegram Service (verwendet python-telegram-bot Package statt telepot Package)'
        en: 'Connects to the telegram service (uses python-telegram-bot package instead of telebot package)'
    maintainer: gamade, ivan73, bmxp
#    tester:
    state: ready
#    tester:                        # Who tests this plugin?
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/...        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.4.4                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: Telegram            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    token:
        type: str
        type: str
        description:
            de: 'geteilter geheimer Schl체ssel zur Authentifizierung bei Telegram'
            en: 'shared secret key to authenticate to telegram network'

    trusted_chat_ids:
        type: str
        description:
            de: 'Liste von Chat IDs denen vertraut wird'
            en: 'list of trusted chat ids'

item_attributes:
    # Definition of item attributes defined by this plugin
    telegram_message:
        type: str
        description:
            de: 'Mitteilung senden wenn sich der Itemwert 채ndert'
            en: 'Send message on item change'

    telegram_info:
        type: str
        description:
            de: 'Item lesen mit bestimmten Itemwerten'
            en: 'read items with specific item-values'

    telegram_text:
        type: str
        description:
            de: 'Mitteilungstext als Itemwert setzen'
            en: 'write message-text into the item'

    telegram_value_match_regex:
        type: str
        description:
            de: 'Itemwert gegen einen regul채n Ausdruck pr체fen vor versenden einer Mitteilung'
            en: 'check a value against a condition before sending a message'

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions: NONE
    # Definition of function interface of the plugin

