# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: gateway                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung einer oder mehrerer Philips HUE Bridges'
        en: 'Gateway for connection to one or more Philips HUE bridges'
    maintainer: mworion, msinn
    tester: Sandman60
    state: ready
#    keywords: kwd1 kwd2            # keywords, where applicable
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/41379-philips-hue-plugin-neu-v1-0-released

    version: 1.4.4                 # Plugin version
    sh_minversion: 1.3c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False
    classname: HUE                  # class containing the plugin

parameters:
# Definition of parameters to be configured in etc/plugin.yaml

    hue_ip:
        type: list(ip)
        description:
            de: 'IP Adresse der Philips HUE Bridge'
            en: 'ip address of the Philips HUE bridge'
        mandatory: True

    hue_port:
        type: list(int)
        default: 80
        valid_min: 0
        description:
            de: 'Port für die the Philips HUE Bridge'
            en: 'Port on the Philips HUE bridge'

    hue_user:
        type: list(str)
        description:
            de: 'User um sich an der Philips HUE Bridge anzumelden'
            en: 'User to login to the Philips HUE bridge'

    cycle_lamps:
        type: int
        default: 10
        valid_min: 5
        description:
            de: 'Abfrage-Zyklus für Leuchten Updates'
            en: 'Cycle time for update of lamps'

    cycle_bridges:
        type: int
        default: 60
        valid_min: 10
        description:
            de: 'Abfrage-Zyklus für Bridge Updates'
            en: 'Cycle time for update of bridges'

    default_transitionTime:
        type: float
        default: 0.4
        valid_min: 0
        description:
            de: 'Zeitraum zwischen den den Checks der Leuchten durch die HUE Bridge selbst'
            en: 'Time in seconds how fast check states of the lamps are changed through the bridge itself'

item_attributes:
# Definition of item attributes defined by this plugin

