# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Plugin, um Yamaha MusicCast-Geräte zu kontrollieren'
        en: 'plugin to control Yamaha MusicCast devices'

    description_lone:
        de: 'Dieses Plugin ermöglicht, Yamaha MusicCast-Geräte in SmartHomeNG einzubinden.\n
             \n
             Dabei ist es möglich, verschiedene Geräte aus SmartHomeNG aus anzusprechen und zu steuern, als auch über SmartHomeNG auszulesen.\n
             \n
             Die Steuerungsmöglichkeiten umfassen (derzeit) unter Anderem:\n
                \n
                - Gerät ein-/ausschalten, Standby, Sleep-Timer,\n
                - Wiedergabequelle auswählen (geräteabhängig, z.B. NetRadio, Radio, NetUSB, Streamingdienste),\n
                - Wiedergabesteuerung (Play/Pause/Stop/nächster,vorheriger Titel/Vor-,Zurückspulen),\n
                - Lautstärkesteuerung\n,
                - Anwahl von Favoriten und Presets (geräteabhängig)\n
            \n
            Die Möglichkeiten, Statusinformationen abzurufen, umfassen (derzeit) u.a.\n
                \n
                - Gerätestatus (an/aus/Standby), \n
                - Lautstärke, Stummschaltung,\n
                - aktuelle Wiedergabequelle,\n
                - aktueller Wiedergabestatus (Play/Pause/...),\n
                - aktueller Titel (quellenabhängig),\n
                - aktuelle Wiedergabeposition (quellenabhängig),\n
                - Coverbild des aktuellen Titels (quellenabhängig)\n
            \n
            Weitere Funktionen werden nach Bedarf und Verfügbarkeit von entsprechenden Geräten implementiert. Grundsätzlich ist die Architektur des Plugins so strukturiert, dass prinzipiell alle verfügbaren Kommandos im entsprechenden Steuerungsstandard implementiert werden können. Für noch nicht implementierte Steuerungsbefehle ist ein genereller "Pass-Thru"-Befehl vorhanden, so dass beliebige Befehlssequenzen an das Gerät gesendet werden können.\n
            '
        en: 'This plugin gives access to Yamaha MusicCast-devices in SmartHomeNG.\n
             \n
             You can access the devices from SmartHomeNG to control them as well as to read status information.\n
             \n
             Control directives implemented (so far) include:\n
                \n
                - switch device on/off, standby, sleep timer,\n
                - select playback source (device dependent, e.g. NetRadio, AM/FM radio, NetUSB, streaming services),\n
                - playback control (play/pause/stop/skip forward,backward/fast forward,reverse),\n
                - volume control,\n
                - selection of favorites and presets (device dependent)\n
             \n
             Status information implemented (so far) include:\n
                \n
                - device status (on/off/standby),\n
                - volume/mute,\n
                - current playback source,\n
                - current playback status (play/pause/...),\n
                - current playback title (depends on pb source),\n
                - current playback position (depends on pb source),\n
                - cover image of current title (depends on pb source)\n
             \n
             New control functions will be implemented as requested and as far as suitable devices are available for testing. Generally, the plugins architecture allows adding any valid control sequence described in the standard. For not yet implemented control directived, a general pass-thru option is available for sending arbitrary control sequences to the device.\n
             '
    maintainer: Morg42
#    tester: Morg42
    keywords: iot yxc yamaha media musiccast
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1174064-plugin-yamaha-musiccast-geräte-neuere-generation

    version: 1.0.5                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: False
    classname: YamahaYXC              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
