# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Implementierung eines Webservice interfaces'
        en: 'Implementation of a webservice interface'
    maintainer: psilo909
#    tester:                        # Who tests this plugin?
    keywords: REST, API, Webservice
    documentation: https://www.smarthomeng.de/?category_name=plugins&s=webservices
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1163886-support-thread-f%C3%BCr-das-webservices-plugin

    version: 1.5.0.5               # Plugin version
    sh_minversion: 1.5             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: WebServices         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    mode:
        type: str
        mandatory: False
        description:
            de: '(optional) Mode des Plugins: "all", wenn die Webservice-Schnittstelle alle Items der SmartHomeNG Instanz verfügbar machen soll (default). Ansonsten werden nur Items ausgeliefert, die einem Set via webservices_set zugeordnet sind.'
            en: '(optional) Mode of the plugin: "all", if standard interface with all items shall be enabled (default if left empty). Otherwise only items are delivered via the interface that are added to a set via webservices_set attribute.'
    
item_attributes:
    # Definition of item attributes defined by this plugin
    webservices_set:
        type: str
        description:
            de: '(optional) webservices_set enthält eine Zeichenkette, die zum Bündeln von Items in sets genutzt wird. Das Set steht unter http://<SmartHomeNG URL>;<WS Port>/[rest|ws]/itemset/<setname> bereit.'
            en: '(optional) webservices_set contains a String, which is used to provide multiple item data via one webservice call. The set is available at http://<SmartHomeNG URL>;<WS Port>/[rest|ws]/itemset/<setname>.'

    webservices_data:
        type: str
        description:
            de: '(optional) webservices_data dient dazu, die Rückgabedaten von Items zu limitieren. Wird als Wert "val" eingegeben, so wird nur der Pfadname und der Wert zurückgegeben, sonst zusätzlich alle Metainformationen.'
            en: '(optional) webservices_data is used, to limit the returned values for an item. If the attribute value "val" is set, only the path name and the item value is returned. Otherwise, also all meta information is returned.'
