# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Implementierung eines Webservice interfaces'
        en: 'Implementation of a webservice interface'
    maintainer: psilo909
#    tester:                        # Who tests this plugin?
    keywords: REST, API, Webservice
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.4.0.1               # Plugin version
    sh_minversion: 1.3a            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: WebServices         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    webservices_set:
        type: str
        description:
            de: 'webservices_set (optional) enth채lt eine Zeichenkette, die zum B체ndeln von Items in sets genutzt wird. Das Set steht unter http://<SmartHomeNG URL>;<WS Port>/[rest|ws]/itemset/<setname> bereit.'
            en: 'webservices_set (optional) contains a String, which is used to provide multiple item data via one webservice call. The set is available at http://<SmartHomeNG URL>;<WS Port>/[rest|ws]/itemset/<setname>.'

    webservices_data:
        type: str
        description:
            de: 'webservices_data (optional) dient dazu, die R체ckgabedaten von Items zu limitieren. Wird als Wert "val" eingegeben, so wird nur der Pfadname und der Wert zur체ckgegeben, sonst zus. alle Metainformationen.'
            en: 'webservices_data (optional) is used, to limit the returned values for an item. If the attribut value "val" is set, only the path name and the item value is returned. Otherwise, also all meta information is returned.'
