# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Universelle Zeitschaltuhr'
        en: 'Universal time switch'
    description_long:                  # Alternative: description in multiple languages
        de: 'Dieses Plugin ermöglicht gezielte Schaltvorgänge von Items zu bestimmten Uhrzeiten oder
             abhängig vom Sonnenstand. Die automatischen Schaltungen können dabei pro Wochentag separat
             definiert werden.\n
             Außerdem ermöglicht eine Interpolationsfunktion das Errechnen von
             Werten zwischen zwei manuell angelegten Schaltzeiten, wodurch z.B. Lichtkurven über den
             Tagesverlauf umgesetzt werden können.
             '
        en: 'This plugin provides specific item changes at a given time or sun position. Those automatic
             switchings can be defined for each day of the week separately.\n
             Furthermore the interpolation function allows the calculation of values between two manual
             settings. You can use this feature for smooth light curves based on the time of the day.
             '
    maintainer: cmalo, bmxp, onkelandy, andrek, morg42
    tester: Sandman60, cmalo, schuma, morg42
    state: ready
    keywords: scheduler uzsu trigger series
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1364692-supportthread-für-uzsu-plugin

    version: 2.0.2                 # Plugin version
    sh_minversion: '1.6'             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    restartable: unknown
    classname: UZSU                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    remove_duplicates:
        type: bool
        default: True
        description:
            de: 'Falls True, werden Einträge mit exakt den selben Einstellungen, aber unterschiedlichem Wert durch einen neu getätigten Eintrag ersetzt'
            en: 'If True, existing entries with exactly the same settings except the value get replaced by the new entry'

    suncalculation_cron:
        type: str
        default: '0 0 * *'
        description:
            de: 'Cron-Angabe, wann für die UZSU Einträge mit Sonnenstandbezug die errechnete Uhrzeit ins dict Item geschrieben werden soll.'
            en: 'Cron definition when the UZSU item should be updated with the calculated times for sun-related UZSU entries.'
        description_long:
            de: 'Cron-Angabe, wann für die UZSU Einträge mit Sonnenstandbezug die errechnete Uhrzeit ins dict Item geschrieben werden soll. Diese "calculated" Einträge sind relevant für diverse UZSU Widgets der SmartVisu.'
            en: 'Cron definition when the UZSU item should be updated with the calculated times for sun-related UZSU entries.There "calculated" entries are relevant for some SmartVisu UZSU widgets.'

    interpolation_interval:
        type: int
        default: 5
        valid_min: 0
        description:
            de: 'Standardintervall in Minuten, in dem ein interpolierter Wert erneut errechnet werden soll. Kann pro UZSU individuell konfiguriert werden.'
            en: 'Standard interval in minutes that is used to re-calculate an interpolated value. Can be configured for each UZSU individually.'

    interpolation_type:
        type: str
        default: 'none'
        valid_list:
          - 'none'
          - 'cubic'
          - 'linear'
        description:
            de: 'Standardintervall in Minuten, in dem ein interpolierter Wert erneut errechnet werden soll. Kann pro UZSU individuell konfiguriert werden.'
            en: 'Standard interval in minutes that is used to re-calculate an interpolated value. Can be configured for each UZSU individually.'

    backintime:
        type: int
        default: 0
        valid_min: 0
        description:
            de: 'Standardmaximalalter eines UZSU Eintrags in Minuten, um beim Plugin-Start versäumte Einträge nachzuholen. Kann pro UZSU individuell konfiguriert werden.'
            en: 'Standard maximum age of an uzsu entry in minutes to be catched up at the plugin start. Can be configured for each UZSU individually'

    interpolation_precision:
        type: int
        default: 2
        valid_min: 0
        valid_max: 4
        description:
            de: 'Anzahl an Dezimalstellen bei der Berechnung der Interpolation'
            en: 'Amount of decimal places when calculating interpolation values'

item_attributes:
    # Definition of item attributes defined by this plugin
    uzsu_item:
        type: str
        description:
            de: 'Das Item, das durch die UZSU geschaltet werden soll. Entweder als komplette ID oder relativer Pfad angegeben.'
            en: 'The item that gets changed by the UZSU. Declare as full ID or relative path.'
        description_long:
            de: '**Das Item, das durch die UZSU geschaltet werden soll:**\n
                Im items Ordner ist pro Item, das geschaltet werden soll, ein UZSU Item-Eintrag mit
                ``type: dict`` zu erstellen. Die Hierarchie spielt dabei keine Rolle, es wird allerdings empfohlen,
                das UZSU Item als Kind des zu schaltenden Items zu deklarieren und die relative Item-Referenzierung
                ``".."`` für den Parameter ``uzsu_item`` zu nutzen. Es wird dringend empfohlen,
                ``cache: True`` zu setzen, damit die Einstellungen bei einem Neustart nicht verloren gehen.
                '
            en: '**The item that gets changed by the UZSU:**\n
                 You have to specify an item with ``type: dict`` and with the ``uzsu_item``
                 attribute set to the path of the item which will be set by this item.
                 The hierarchy does not matter but it is recommended to define the UZSU item
                 as a child of the item to be set and use the relative item reference ``".."``
                 for the uzsu_item parameter. It is highly recommended to specify
                 ``cache: True`` as well for persistent storage of the UZSU information.
                 '

item_structs:
    child:
        name: Vorlage-Struktur für Zeitschaltuhren

        uzsu:
            type: dict
            uzsu_item: ..
            cache: True
            visu_acl: rw
            enforce_updates: True

            last:
                remark: The last set value if UZSU is active
                type: foo
                visu_acl: ro
                eval: sh...lastvalue('uzsu_dict_updated')
                crontab: init = None
                eval_trigger: ..

            active:
                remark: Use this item to easily turn on or off your UZSU
                type: bool
                eval: sh...activate(value)
                visu_acl: rw

                status:
                    type: bool
                    eval: sh....activate()
                    eval_trigger:
                      - ..
                      - ...
                    on_change: .. = value
                    crontab: init = 0
            next:
                remark: The next value and time
                type: dict
                visu_acl: ro
                eval: sh...planned()
                eval_trigger: ..
                initial_value: "{'value': '-', 'next': '-'}"

                value:
                    remark: The next value
                    type: str
                    visu_acl: ro
                    eval: sh...property.value['value']
                    eval_trigger: ..

                time:
                    remark: The next time
                    type: str
                    visu_acl: ro
                    eval: sh...property.value['next']
                    eval_trigger: ..

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin
    planned:
        type: dict
        description:
            de: 'Abfrage des nächsten Aktualisierungszeitpunkts'
            en: 'Query the next scheduled value and time'
        description_long:
            de: 'Abfrage des nächsten Aktualisierungszeitpunkts. Ist keine Aktualisierung geplant, z.B. weil das
                UZSU Item nicht aktiviert ist, wird None zurückgegeben, ansonsten ein Dictionary
                mit den Einträgen Zeit und Wert.
                '
            en: 'Query the next scheduled value and time. If no update is planned, e.g. if the UZSU item
                is not active, the result is None, otherwise a dictionary containing entries for time and value.
                '
        parameters:
            item:
                type: foo
                description:
                    de: "Das Item-Objekt"
                    en: "An item object"

    resume:
        type: foo
        description:
            de: 'Fortsetzen der UZSU Evaluierung: Aktivieren des Items und Setzen des zuletzt festgelegten Wertes.'
            en: 'Resuming the UZSU evaluation: activating the item and setting the last defined value.'
        parameters:
            activevalue:
                type: bool
                description:
                    de: "True, um die UZSU fortzusetzen; False, um sie zu pausieren"
                    en: "True to resume the UZSU, false to pause"
            item:
                type: foo
                description:
                    de: "Das Item-Objekt"
                    en: "An item object"
    lastvalue:
        type: foo
        description:
            de: 'Abfrage des zuletzt gesetzten Werts. Kann z.B. beim Aktivieren der UZSU genutzt werden, um sofort auf den gewünschten Wert zu schalten.'
            en: 'Query the last value. Can be used to immediately set the correct value after activating an UZSU.'
        parameters:
            by:
                type: str
                default: None
                description:
                    de: 'Für eine entsprechende Info im Logfile kann hier z.B. der Itemname, der den Wert abruft eingetragen werden'
                    en: 'For respective info in the log file you can choose to put the item name that queries the value.'
            item:
                type: foo
                description:
                    de: "Das Item-Objekt"
                    en: "An item object"
    clear:
        type: bool
        description:
            de: 'Beim Aufrufen mit dem Parameter True werden die Einträge der UZSU gelöscht.'
            en: 'Using this function with the parameter True clears the UZSU.'
        description_long:
            de: 'Löschen der UZSU Einträge eines Items.\n
                - Leer/False: nichts ausführen\n
                - True: löschen\n
                '
            en: 'Delete the UZSU entries of an item.\n
                - Empty/False: do nothing\n
                - True: delete\n
                '
        parameters:
            clear:
                type: bool
                description:
                    de: "True, um die UZSU Einträge zu löschen."
                    en: "True to clear the UZSU entries."
            item:
                type: foo
                description:
                    de: "Das Item-Objekt"
                    en: "An item object"
    itpl:
        type: dict
        description:
            de: 'Zum Debuggen der Interpolationsfunktion.'
            en: 'For debugging the internal interpolation function.'
        description_long:
            de: 'Löschen oder Abrufen der internen Interpolationswerte.\n
                - Leer/False: Internes Dictionary mit Interpolationswerten\n
                - True: löschen\n
                '
            en: 'Delete or query internal interpolation values.\n
                - Empty/False: Internal dictionary of interpolation values\n
                - True: delete\n
                '
        parameters:
            clear:
                type: bool
                default: False
                description:
                    de: "Löschen oder nicht"
                    en: "Delete or do not delete"
            item:
                type: foo
                description:
                    de: "Das Item-Objekt"
                    en: "An item object"
    activate:
        type: bool
        description:
            de: 'Abfrage oder Setzen, ob die UZSU aktiv ist oder nicht.'
            en: 'query or set whether the UZSU is set active or not.'
        parameters:
            activevalue:
                type: foo
                description:
                    de: "Abfragen oder Setzen des UZSU Status"
                    en: "Query or set UZSU active state"
                valid_list:
                    - None
                    - True
                    - False
                valid_list_description:
                    de:
                        - Abfrage
                        - Aktivieren
                        - Deaktivieren
                    en:
                        - Query
                        - Activate
                        - Deactivate
                valid_list_item_type:
                    - foo
                    - bool
                    - bool
            item:
                type: foo
                description:
                    de: "Das Item-Objekt"
                    en: "An item object"
    interpolation:
        type: dict
        description:
            de: 'Abfrage oder Setzen der Interpolationseinstellungen'
            en: 'Query or set the interpolation settings'
        parameters:
            intpl_type:
                type: foo
                default: None
                description:
                    de: 'Interpolationstyp'
                    en: 'interpolation type'
                valid_list:
                    - None
                    - 'linear'
                    - 'cubic'
                    - 'none'
                valid_list_description:
                    de:
                        - Abfrage
                        - konstant gleiche Zwischenberechnung
                        - Spline-Interpolation mit verzögertem Start und sanftem Verlangsamen
                        - keine Interpolation
                    en:
                        - Query
                        - constant interpolation
                        - spline interpolation with ease in and out
                        - no interpolation
                valid_list_item_type:
                    - foo
                    - str
                    - str
                    - str

            interval:
                type: int
                default: 5
                valid_min: 1
                description:
                    de: 'Intervall in Minuten, in dem der interpolierte Wert aktualisiert werden soll'
                    en: 'Interval in minutes to re-calculate the interpolated value'
            backintime:
                type: int
                default: 0
                valid_min: 0
                description:
                    de: 'Maximales Alter eines UZSU Eintrags in Minuten, um beim Plugin-Start versäumte Einträge nachzuholen.'
                    en: 'maximum age of an uzsu entry in minutes to be catched up at the plugin start'
